import type { BroadcastInfo } from "@/lib/matches"

export const broadcastsByCountry: Record<string, BroadcastInfo[]> = {
  gb: [
    {
      countryCode: "gb",
      countryName: "United Kingdom",
      broadcaster: "BBC / ITV",
      access: "Free",
      url: "https://www.bbc.co.uk/iplayer",
      sourceName: "BBC / ITV official broadcast rights",
      sourceUrl: "https://www.bbc.co.uk/sport/football",
      lastChecked: "2026-04-05",
      hasFullCoverage: true,
      notes: "Free full tournament coverage in the UK",
      commentaryLanguages: ["English"],
    },
  ],

  au: [
    {
      countryCode: "au",
      countryName: "Australia",
      broadcaster: "SBS",
      access: "Free",
      url: "https://www.sbs.com.au/ondemand/fifa-world-cup-2026",
      sourceName: "SBS official World Cup coverage",
      sourceUrl: "https://www.sbs.com.au/ondemand/fifa-world-cup-2026",
      lastChecked: "2026-04-07",
      hasFullCoverage: true,
      notes: "Free full tournament coverage in Australia",
      commentaryLanguages: ["English"],
    },
  ],

  ch: [
    {
      countryCode: "ch",
      countryName: "Switzerland",
      broadcaster: "SRF",
      access: "Free",
      url: "https://www.srf.ch/play/tv",
      sourceName: "SRF / RTS official broadcast rights",
      sourceUrl: "https://www.rts.ch/sport/football/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Free coverage for German-speaking Switzerland",
      commentaryLanguages: ["German"],
    },
    {
      countryCode: "ch",
      countryName: "Switzerland",
      broadcaster: "RTS",
      access: "Free",
      url: "https://www.rts.ch/play/tv",
      sourceName: "SRF / RTS official broadcast rights",
      sourceUrl: "https://www.rts.ch/sport/football/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Free coverage for French-speaking Switzerland",
      commentaryLanguages: ["French"],
    },
  ],

  be: [
    {
      countryCode: "be",
      countryName: "Belgium",
      broadcaster: "RTBF",
      access: "Free",
      url: "https://www.rtbf.be/auvio/",
      sourceName: "RTBF official broadcast rights",
      sourceUrl: "https://www.rtbf.be/sport/football/",
      lastChecked: "2026-04-07",
      hasFullCoverage: true,
      notes: "Free full tournament coverage in Belgium",
      commentaryLanguages: ["French"],
    },
    {
      countryCode: "be",
      countryName: "Belgium",
      broadcaster: "VRT",
      access: "Free",
      url: "https://www.vrt.be/vrtmax/",
      sourceName: "VRT official broadcast rights",
      sourceUrl: "https://www.vrt.be/vrtmax/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Free full tournament coverage in Belgium",
      commentaryLanguages: ["Dutch"],
    },
  ],

  fr: [
    {
      countryCode: "fr",
      countryName: "France",
      broadcaster: "TF1",
      access: "Free",
      url: "https://www.tf1.fr/",
      sourceName: "TF1 official broadcast rights",
      sourceUrl: "https://www.tf1info.fr/",
      lastChecked: "2026-04-05",
      hasFullCoverage: false,
      notes: "Partial free coverage (selected matches)",
      commentaryLanguages: ["French"],
    },
    {
      countryCode: "fr",
      countryName: "France",
      broadcaster: "M6",
      access: "Free",
      url: "https://www.6play.fr/",
      sourceName: "M6 official broadcast rights",
      sourceUrl: "https://www.m6.fr/",
      lastChecked: "2026-04-05",
      hasFullCoverage: false,
      notes: "Partial free coverage (selected matches)",
      commentaryLanguages: ["French"],
    },
    {
      countryCode: "fr",
      countryName: "France",
      broadcaster: "beIN SPORTS",
      access: "Paid",
      url: "https://www.beinsports.com/fr-fr/football/coupe-du-monde-de-la-fifa-2026",
      affiliateUrl: undefined,
      sourceName: "beIN SPORTS France World Cup 2026 page",
      sourceUrl:
        "https://www.beinsports.com/fr-fr/football/coupe-du-monde-de-la-fifa-2026",
      lastChecked: "2026-04-07",
      hasFullCoverage: true,
      notes: "Paid full tournament coverage in France",
      commentaryLanguages: ["French"],
    },
  ],

  ca: [
    {
      countryCode: "ca",
      countryName: "Canada",
      broadcaster: "TSN",
      access: "Paid",
      url: "https://www.tsn.ca/",
      sourceName: "Bell Media FIFA World Cup 26 announcement",
      sourceUrl:
        "https://www.bellmedia.ca/the-lede/press/fifa-world-cup-26-is-one-year-away-and-tsn-counts-down-to-the-tournament-with-preview-specials-all-new-podcasts-and-more/",
      lastChecked: "2026-04-07",
      hasFullCoverage: true,
      notes: "Full tournament coverage in Canada via Bell Media sports ecosystem",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "ca",
      countryName: "Canada",
      broadcaster: "RDS",
      access: "Paid",
      url: "https://www.rds.ca/",
      sourceName: "Bell Media FIFA World Cup 26 announcement",
      sourceUrl:
        "https://www.bellmedia.ca/fr/ventes-publicitaires/ressources/nouvelles/opportunites-publicitaires-pour-la-coupe-du-monde-fifa-2026/",
      lastChecked: "2026-04-07",
      hasFullCoverage: true,
      notes: "Full tournament coverage in Canada for French-language audience",
      commentaryLanguages: ["French"],
    },
  ],

  us: [
    {
      countryCode: "us",
      countryName: "United States",
      broadcaster: "FOX Sports",
      access: "Paid",
      url: "https://www.foxsports.com/",
      sourceName: "FOX Sports FIFA World Cup coverage",
      sourceUrl: "https://www.foxsports.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "English-language World Cup coverage in the United States",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "us",
      countryName: "United States",
      broadcaster: "Telemundo",
      access: "Free",
      url: "https://www.telemundo.com/deportes",
      sourceName: "NBCUniversal Telemundo World Cup coverage",
      sourceUrl:
        "https://www.nbcuniversal.com/article/telemundo-unveils-most-extensive-spanish-language-fifa-world-cuptm-presentation-broadcast-television",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Main Spanish-language broadcast (free over-the-air in some markets)",
      commentaryLanguages: ["Spanish"],
    },
    {
      countryCode: "us",
      countryName: "United States",
      broadcaster: "Universo",
      access: "Paid",
      url: "https://www.telemundo.com/universo",
      sourceName: "NBCUniversal Universo coverage",
      sourceUrl:
        "https://www.nbcuniversal.com/article/telemundo-unveils-most-extensive-spanish-language-fifa-world-cuptm-presentation-broadcast-television",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Cable channel with extended coverage",
      commentaryLanguages: ["Spanish"],
    },
    {
      countryCode: "us",
      countryName: "United States",
      broadcaster: "Peacock",
      access: "Paid",
      url: "https://www.peacocktv.com/",
      sourceName: "NBCUniversal Peacock streaming",
      sourceUrl:
        "https://www.nbcuniversal.com/article/telemundo-unveils-most-extensive-spanish-language-fifa-world-cuptm-presentation-broadcast-television",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Full streaming coverage in Spanish",
      commentaryLanguages: ["Spanish"],
    },
  ],

  es: [
    {
      countryCode: "es",
      countryName: "Spain",
      broadcaster: "RTVE",
      access: "Free",
      url: "https://www.rtve.es/play/",
      sourceName: "RTVE official coverage",
      sourceUrl: "https://www.rtve.es/deportes/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Free-to-air matches including selected key fixtures",
      commentaryLanguages: ["Spanish"],
    },
    {
      countryCode: "es",
      countryName: "Spain",
      broadcaster: "Movistar+",
      access: "Paid",
      url: "https://www.movistarplus.es/",
      sourceName: "Movistar+ football coverage",
      sourceUrl: "https://www.movistarplus.es/deportes/futbol",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Full tournament coverage via subscription",
      commentaryLanguages: ["Spanish"],
    },
  ],

  pt: [
    {
      countryCode: "pt",
      countryName: "Portugal",
      broadcaster: "RTP",
      access: "Free",
      url: "https://www.rtp.pt/play/",
      sourceName: "RTP previous World Cup coverage",
      sourceUrl: "https://www.rtp.pt/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Free-to-air matches including Portugal games and key fixtures",
      commentaryLanguages: ["Portuguese"],
    },
    {
      countryCode: "pt",
      countryName: "Portugal",
      broadcaster: "Sport TV",
      access: "Paid",
      url: "https://www.sporttv.pt/",
      sourceName: "Sport TV historical rights",
      sourceUrl: "https://www.sporttv.pt/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Full tournament coverage via subscription",
      commentaryLanguages: ["Portuguese"],
    },
  ],

  se: [
    {
      countryCode: "se",
      countryName: "Sweden",
      broadcaster: "SVT",
      access: "Free",
      url: "https://www.svtplay.se/",
      sourceName: "SVT World Cup coverage",
      sourceUrl: "https://www.svt.se/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Shared rights, broadcasts many matches",
      commentaryLanguages: ["Swedish"],
    },
    {
      countryCode: "se",
      countryName: "Sweden",
      broadcaster: "TV4",
      access: "Free",
      url: "https://www.tv4play.se/",
      sourceName: "TV4 sports rights",
      sourceUrl: "https://www.tv4.se/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Co-broadcast with SVT",
      commentaryLanguages: ["Swedish"],
    },
  ],

  no: [
    {
      countryCode: "no",
      countryName: "Norway",
      broadcaster: "NRK",
      access: "Free",
      url: "https://tv.nrk.no/",
      sourceName: "NRK sports rights",
      sourceUrl: "https://www.nrk.no/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Free matches including major fixtures",
      commentaryLanguages: ["Norwegian"],
    },
    {
      countryCode: "no",
      countryName: "Norway",
      broadcaster: "TV2",
      access: "Paid",
      url: "https://www.tv2.no/play/",
      sourceName: "TV2 premium sports",
      sourceUrl: "https://www.tv2.no/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Full coverage via subscription",
      commentaryLanguages: ["Norwegian"],
    },
  ],

  dk: [
    {
      countryCode: "dk",
      countryName: "Denmark",
      broadcaster: "DR",
      access: "Free",
      url: "https://www.dr.dk/drtv/",
      sourceName: "DR World Cup coverage",
      sourceUrl: "https://www.dr.dk/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Shared free coverage",
      commentaryLanguages: ["Danish"],
    },
    {
      countryCode: "dk",
      countryName: "Denmark",
      broadcaster: "TV2",
      access: "Free",
      url: "https://play.tv2.dk/",
      sourceName: "TV2 Denmark sports rights",
      sourceUrl: "https://www.tv2.dk/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Co-broadcast with DR",
      commentaryLanguages: ["Danish"],
    },
  ],

  fi: [
    {
      countryCode: "fi",
      countryName: "Finland",
      broadcaster: "YLE",
      access: "Free",
      url: "https://areena.yle.fi/",
      sourceName: "YLE sports rights",
      sourceUrl: "https://yle.fi/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Full or near full tournament coverage",
      commentaryLanguages: ["Finnish"],
    },
  ],

  is: [
    {
      countryCode: "is",
      countryName: "Iceland",
      broadcaster: "RUV",
      access: "Free",
      url: "https://www.ruv.is/sjonvarp",
      sourceName: "RUV World Cup coverage",
      sourceUrl: "https://www.ruv.is/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Full tournament coverage",
      commentaryLanguages: ["Icelandic"],
    },
  ],

  nl: [
    {
      countryCode: "nl",
      countryName: "Netherlands",
      broadcaster: "NOS",
      access: "Free",
      url: "https://nos.nl/",
      sourceName: "NOS World Cup rights",
      sourceUrl: "https://nos.nl/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Free matches including Netherlands games",
      commentaryLanguages: ["Dutch"],
    },
    {
      countryCode: "nl",
      countryName: "Netherlands",
      broadcaster: "ESPN NL",
      access: "Paid",
      url: "https://www.espn.nl/",
      sourceName: "ESPN Netherlands",
      sourceUrl: "https://www.espn.nl/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Full coverage via subscription",
      commentaryLanguages: ["Dutch"],
    },
  ],

  in: [
    {
      countryCode: "in",
      countryName: "India",
      broadcaster: "DD Sports",
      access: "Free",
      url: "https://prasarbharati.gov.in/",
      sourceName: "Prasar Bharati sports rights",
      sourceUrl: "https://prasarbharati.gov.in/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Selected matches on free TV",
      commentaryLanguages: ["Hindi", "English"],
    },
    {
      countryCode: "in",
      countryName: "India",
      broadcaster: "JioCinema",
      access: "Free",
      url: "https://www.jiocinema.com/",
      sourceName: "JioCinema FIFA coverage",
      sourceUrl: "https://www.jiocinema.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Full tournament streaming free in India",
      commentaryLanguages: ["Hindi", "English", "Regional"],
    },
  ],

  cn: [
    {
      countryCode: "cn",
      countryName: "China",
      broadcaster: "CCTV",
      access: "Free",
      url: "https://tv.cctv.com/",
      sourceName: "CCTV sports rights",
      sourceUrl: "https://tv.cctv.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Official broadcaster with wide free coverage",
      commentaryLanguages: ["Chinese"],
    },
    {
      countryCode: "cn",
      countryName: "China",
      broadcaster: "Migu",
      access: "Paid",
      url: "https://www.miguvideo.com/",
      sourceName: "Migu sports streaming",
      sourceUrl: "https://www.miguvideo.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Premium streaming platform",
      commentaryLanguages: ["Chinese"],
    },
  ],

  ma: [
    {
      countryCode: "ma",
      countryName: "Morocco",
      broadcaster: "SNRT",
      access: "Free",
      url: "https://snrt.ma/",
      sourceName: "SNRT sports coverage",
      sourceUrl: "https://snrt.ma/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["Arabic", "French"],
    },
    {
      countryCode: "ma",
      countryName: "Morocco",
      broadcaster: "beIN Sports",
      access: "Paid",
      url: "https://www.beinsports.com/",
      sourceName: "beIN Sports MENA coverage",
      sourceUrl: "https://www.beinsports.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Paid full tournament coverage",
      commentaryLanguages: ["Arabic"],
    },
  ],

  dz: [
    {
      countryCode: "dz",
      countryName: "Algeria",
      broadcaster: "ENTV",
      access: "Free",
      url: "https://www.entv.dz/",
      sourceName: "ENTV sports coverage",
      sourceUrl: "https://www.entv.dz/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["Arabic"],
    },
    {
      countryCode: "dz",
      countryName: "Algeria",
      broadcaster: "beIN Sports",
      access: "Paid",
      url: "https://www.beinsports.com/",
      sourceName: "beIN Sports MENA coverage",
      sourceUrl: "https://www.beinsports.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Paid full tournament coverage",
      commentaryLanguages: ["Arabic"],
    },
  ],

  tn: [
    {
      countryCode: "tn",
      countryName: "Tunisia",
      broadcaster: "Wataniya",
      access: "Free",
      url: "https://www.watania1.tn/",
      sourceName: "Wataniya sports coverage",
      sourceUrl: "https://www.watania1.tn/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["Arabic"],
    },
    {
      countryCode: "tn",
      countryName: "Tunisia",
      broadcaster: "beIN Sports",
      access: "Paid",
      url: "https://www.beinsports.com/",
      sourceName: "beIN Sports MENA coverage",
      sourceUrl: "https://www.beinsports.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Paid full tournament coverage",
      commentaryLanguages: ["Arabic"],
    },
  ],

  eg: [
    {
      countryCode: "eg",
      countryName: "Egypt",
      broadcaster: "ON Time Sports",
      access: "Free",
      url: "https://www.youtube.com/@ONTimeSports",
      sourceName: "ON Time Sports coverage",
      sourceUrl: "https://www.ontime.live/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Selected free coverage",
      commentaryLanguages: ["Arabic"],
    },
    {
      countryCode: "eg",
      countryName: "Egypt",
      broadcaster: "beIN Sports",
      access: "Paid",
      url: "https://www.beinsports.com/",
      sourceName: "beIN Sports MENA coverage",
      sourceUrl: "https://www.beinsports.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Paid full tournament coverage",
      commentaryLanguages: ["Arabic"],
    },
  ],

  sn: [
    {
      countryCode: "sn",
      countryName: "Senegal",
      broadcaster: "RTS",
      access: "Free",
      url: "https://www.rts.sn/",
      sourceName: "RTS Senegal sports coverage",
      sourceUrl: "https://www.rts.sn/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["French"],
    },
    {
      countryCode: "sn",
      countryName: "Senegal",
      broadcaster: "beIN Sports",
      access: "Paid",
      url: "https://www.beinsports.com/",
      sourceName: "beIN Sports MENA coverage",
      sourceUrl: "https://www.beinsports.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Paid full tournament coverage",
      commentaryLanguages: ["Arabic"],
    },
  ],

  ci: [
    {
      countryCode: "ci",
      countryName: "Ivory Coast",
      broadcaster: "RTI",
      access: "Free",
      url: "https://www.rti.ci/",
      sourceName: "RTI sports coverage",
      sourceUrl: "https://www.rti.ci/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["French"],
    },
    {
      countryCode: "ci",
      countryName: "Ivory Coast",
      broadcaster: "beIN Sports",
      access: "Paid",
      url: "https://www.beinsports.com/",
      sourceName: "beIN Sports MENA coverage",
      sourceUrl: "https://www.beinsports.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Paid full tournament coverage",
      commentaryLanguages: ["Arabic"],
    },
  ],

  ng: [
    {
      countryCode: "ng",
      countryName: "Nigeria",
      broadcaster: "NTA",
      access: "Free",
      url: "https://nta.ng/",
      sourceName: "NTA sports coverage",
      sourceUrl: "https://nta.ng/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "ng",
      countryName: "Nigeria",
      broadcaster: "SuperSport",
      access: "Paid",
      url: "https://www.supersport.com/",
      sourceName: "SuperSport coverage",
      sourceUrl: "https://www.supersport.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Paid full coverage",
      commentaryLanguages: ["English"],
    },
  ],

  gh: [
    {
      countryCode: "gh",
      countryName: "Ghana",
      broadcaster: "GTV",
      access: "Free",
      url: "https://www.gbcghanaonline.com/gtv/",
      sourceName: "GTV sports coverage",
      sourceUrl: "https://www.gbcghanaonline.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "gh",
      countryName: "Ghana",
      broadcaster: "SuperSport",
      access: "Paid",
      url: "https://www.supersport.com/",
      sourceName: "SuperSport coverage",
      sourceUrl: "https://www.supersport.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Paid full coverage",
      commentaryLanguages: ["English"],
    },
  ],

  za: [
    {
      countryCode: "za",
      countryName: "South Africa",
      broadcaster: "SABC",
      access: "Free",
      url: "https://www.sabcplus.com/",
      sourceName: "SABC sports coverage",
      sourceUrl: "https://www.sabc.co.za/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Selected free coverage",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "za",
      countryName: "South Africa",
      broadcaster: "SuperSport",
      access: "Paid",
      url: "https://www.supersport.com/",
      sourceName: "SuperSport coverage",
      sourceUrl: "https://www.supersport.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Paid full coverage",
      commentaryLanguages: ["English"],
    },
  ],

  cm: [
    {
      countryCode: "cm",
      countryName: "Cameroon",
      broadcaster: "CRTV",
      access: "Free",
      url: "https://www.crtv.cm/",
      sourceName: "CRTV sports coverage",
      sourceUrl: "https://www.crtv.cm/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["French"],
    },
    {
      countryCode: "cm",
      countryName: "Cameroon",
      broadcaster: "SuperSport",
      access: "Paid",
      url: "https://www.supersport.com/",
      sourceName: "SuperSport coverage",
      sourceUrl: "https://www.supersport.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Paid full coverage",
      commentaryLanguages: ["English"],
    },
  ],

  cd: [
    {
      countryCode: "cd",
      countryName: "DR Congo",
      broadcaster: "RTNC",
      access: "Free",
      url: "https://www.rtnc.cd/",
      sourceName: "RTNC sports coverage",
      sourceUrl: "https://www.rtnc.cd/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["French"],
    },
    {
      countryCode: "cd",
      countryName: "DR Congo",
      broadcaster: "SuperSport",
      access: "Paid",
      url: "https://www.supersport.com/",
      sourceName: "SuperSport coverage",
      sourceUrl: "https://www.supersport.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      notes: "Paid full coverage",
      commentaryLanguages: ["English"],
    },
  ],
};

export const priorityCountryCodes = [
  "gb",
  "au",
  "ch",
  "be",
  "fr",
  "ca",
  "us",
] as const;

export function getAllBroadcasts(): BroadcastInfo[] {
  return Object.values(broadcastsByCountry).flat();
}