import type { Metadata } from "next";
import Link from "next/link";
import Breadcrumbs from "@/components/Breadcrumbs";
import { getPublicEventsSnapshot } from "@/lib/public-events";
import styles from "./sport-hub.module.css";

const COPY:Record<string,{title:string;canonical:string;backdrop:string;familyHref:string}>={motogp:{title:"MotoGP",canonical:"/sports/motogp",backdrop:"/sports/motogp.webp",familyHref:"/motorsports"}};

export function buildRaceSeriesMetadata(sport:string):Metadata{const cfg=COPY[sport];if(!cfg)return{title:"Motorsport | WatchTVSport",robots:{index:false,follow:false}};return{title:`${cfg.title} race calendar & where to watch | WatchTVSport`,description:`Remaining ${cfg.title} race weekends, sessions and official viewing information by country.`,alternates:{canonical:cfg.canonical},robots:{index:true,follow:true},openGraph:{title:`${cfg.title} race calendar | WatchTVSport`,description:`Remaining ${cfg.title} race weekends and session pages.`,url:cfg.canonical,type:"website"},twitter:{card:"summary_large_image",title:`${cfg.title} race calendar | WatchTVSport`,description:`Remaining ${cfg.title} race weekends and session pages.`}};}

export default async function RaceSeriesPage({sport}:{sport:string}){const cfg=COPY[sport];if(!cfg)return null;const snapshot=await getPublicEventsSnapshot();const now=Date.now();const events=snapshot.events.filter(e=>e.sport===sport).sort((a,b)=>Date.parse(a.eventDate)-Date.parse(b.eventDate));const grouped=new Map<string,{id:string;name:string;slug?:string;first:string;last:string;country?:string;venue?:string;sessionCount:number;detailPath:string;hasFuture:boolean}>();for(const event of events){const key=event.eventGroupId??event.eventGroupSlug??event.eventEditionKey??event.slug;const old=grouped.get(key);const future=event.status==="live"||(event.status!=="finished"&&Date.parse(event.eventDate)>=now);if(!old){grouped.set(key,{id:key,name:event.eventGroupName??event.eventEditionLabel??event.title,slug:event.eventGroupSlug,first:event.eventDate,last:event.eventDate,country:event.country,venue:event.venue,sessionCount:1,detailPath:event.detailPath,hasFuture:future});continue;}old.sessionCount++;if(Date.parse(event.eventDate)<Date.parse(old.first)){old.first=event.eventDate;old.detailPath=event.detailPath;}if(Date.parse(event.eventDate)>Date.parse(old.last))old.last=event.eventDate;old.hasFuture=old.hasFuture||future;}
const weekends=Array.from(grouped.values()).filter(w=>w.hasFuture).sort((a,b)=>Date.parse(a.first)-Date.parse(b.first));const jsonLd={"@context":"https://schema.org","@type":"CollectionPage",name:`${cfg.title} race calendar`,url:`https://watchtvsport.com${cfg.canonical}`};return <main id="main-content" className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Motorsports",href:cfg.familyHref},{label:cfg.title}]}/><section className={styles.hero} style={{backgroundImage:`linear-gradient(90deg,rgba(3,10,18,.97),rgba(3,12,22,.68)),url('${cfg.backdrop}')`}}><p>Motorsport championship</p><h1>{cfg.title}</h1><span>Remaining race weekends of the current season. Open a weekend to see its sessions and viewing information.</span><a href="#remaining-races">Remaining races ↓</a></section><section id="remaining-races" className={styles.section}><div className={styles.heading}><div><p>Current season</p><h2>Remaining race weekends</h2></div><span>{weekends.length}</span></div>{weekends.length?<div className={styles.competitionGrid}>{weekends.map((weekend,index)=><Link className={index===0?styles.featuredCard:styles.card} href={weekend.detailPath} key={weekend.id}><span className={styles.cardVisual} style={{backgroundImage:`url('${cfg.backdrop}')`}} aria-hidden="true"/><div><small>{index===0?"Next":"Race weekend"}</small><strong>{weekend.name}</strong></div><span>{new Intl.DateTimeFormat("en",{month:"short",day:"numeric"}).format(new Date(weekend.first))}{weekend.venue?` · ${weekend.venue}`:""}</span><b>{weekend.sessionCount} sessions →</b></Link>)}</div>:<div className={styles.empty}><strong>No future race weekend imported yet</strong><span>The page is ready and verified race weekends will appear automatically when imported.</span></div>}</section></main>;}
