import type { Metadata } from "next";
import Link from "next/link";
import Breadcrumbs from "@/components/Breadcrumbs";
import SportHero from "@/components/SportHero";
import styles from "@/components/sport-hub.module.css";

export const metadata:Metadata={title:"Motorsports – Formula 1, MotoGP & racing | WatchTVSport",description:"Browse motorsports championships including Formula 1 and MotoGP, with race calendars and official viewing information.",alternates:{canonical:"/motorsports"},robots:{index:true,follow:true},openGraph:{title:"Motorsports | WatchTVSport",description:"Formula 1, MotoGP and future racing championships.",url:"/motorsports",type:"website"},twitter:{card:"summary_large_image",title:"Motorsports | WatchTVSport",description:"Formula 1, MotoGP and future racing championships."}};
const AVAILABLE=[{href:"/formula-1",title:"Formula 1",copy:"Remaining Grand Prix weekends, qualifying and races"},{href:"/sports/motogp",title:"MotoGP",copy:"Race weekends, sessions and events"}] as const;
const FUTURE=[{title:"WRC",copy:"World Rally Championship"},{title:"WEC",copy:"World Endurance Championship"},{title:"IndyCar",copy:"IndyCar Series"},{title:"NASCAR",copy:"NASCAR racing"}] as const;
export default function MotorsportsPage(){const jsonLd={"@context":"https://schema.org","@type":"CollectionPage",name:"Motorsports",url:"https://watchtvsport.com/motorsports"};return <main id="main-content" className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Sports",href:"/sports"},{label:"Motorsports"}]}/><SportHero eyebrow="Sport family" title="Motorsports" description="Choose a racing championship first, then open its remaining race weekends and sessions." backdrop="/sports/formula-1.webp" /><section className={styles.section}><div className={styles.heading}><div><p>Racing</p><h2>Championships</h2></div><span>{AVAILABLE.length} available</span></div><div className={styles.competitionGrid}>{AVAILABLE.map(item=><Link className={styles.featuredCard} href={item.href} key={item.href}><span className={styles.cardVisual} style={{backgroundImage:"url('/sports/formula-1.webp')"}} aria-hidden="true"/><div><small>Available</small><strong>{item.title}</strong></div><span>{item.copy}</span><b>Open championship →</b></Link>)}{FUTURE.map(item=><div className={styles.card} aria-disabled="true" key={item.title}><div><small>Future coverage</small><strong>{item.title}</strong></div><span>{item.copy}</span><b>Ready for data import</b></div>)}</div></section></main>}
