import type { BroadcastInfo } from "./matches";

export const broadcastsByCountry: Record<string, BroadcastInfo[]> = {
  gb: [
    {
      countryCode: "gb",
      countryName: "United Kingdom",
      broadcaster: "BBC",
      access: "Free",
      url: "https://www.bbc.co.uk/iplayer",
      sourceName: "STV World Cup TV match schedule",
      sourceUrl:
        "https://news.stv.tv/sport/world-cup-tv-match-schedule-for-stv-and-bbc-full-list-of-where-to-watch-live",
      lastChecked: "2026-06-25",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [
        "haiti-vs-scotland-2026-06-13",
        "cote-divoire-vs-ecuador-2026-06-14",
        "belgium-vs-egypt-2026-06-15",
        "iran-vs-new-zealand-2026-06-15",
        "austria-vs-jordan-2026-06-17",
        "portugal-vs-dr-congo-2026-06-17",
        "uzbekistan-vs-colombia-2026-06-18",
        "czechia-vs-south-africa-2026-06-18",
        "mexico-vs-south-korea-2026-06-19",
        "usa-vs-australia-2026-06-19",
        "netherlands-vs-sweden-2026-06-20",
        "ecuador-vs-curacao-2026-06-20",
        "tunisia-vs-japan-2026-06-21",
        "scotland-vs-brazil-2026-06-24",
        "ecuador-vs-germany-2026-06-25",
        "curacao-vs-cote-d-ivoire-2026-06-25",
        "japan-vs-sweden-2026-06-25",
        "tunisia-vs-netherlands-2026-06-25",
        "new-zealand-vs-belgium-2026-06-26",
        "egypt-vs-ir-iran-2026-06-26",
      ],
      notes: "Shared free-to-air FIFA World Cup 2026 coverage in the UK with ITV. Match allocations confirmed from official STV / UK TV schedule, including BBC fixtures through 2026-06-26. Newly verified on 2026-06-25: New Zealand vs Belgium and Egypt vs IR Iran.",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "gb",
      countryName: "United Kingdom",
      broadcaster: "ITV",
      access: "Free",
      url: "https://www.itv.com/",
      sourceName: "ITV and BBC official World Cup 2026 match split",
      sourceUrl:
        "https://www.itv.com/presscentre/presscentre/media-releases/itv-and-bbc-reveal-blockbuster-match-split-fifa-world-cup-2026",
      lastChecked: "2026-06-26",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [
        "qatar-vs-switzerland-2026-06-13",
        "germany-vs-curacao-2026-06-14",
        "netherlands-vs-japan-2026-06-14",
        "sweden-vs-tunisia-2026-06-14",
        "england-vs-croatia-2026-06-17",
        "scotland-vs-morocco-2026-06-19",
        "brazil-vs-haiti-2026-06-19",
        "turkiye-vs-paraguay-2026-06-19",
        "germany-vs-cote-d-ivoire-2026-06-20",
        "switzerland-vs-canada-2026-06-24",
        "bosnia-and-herzegovina-vs-qatar-2026-06-24",
        "turkiye-vs-usa-2026-06-25",
        "paraguay-vs-australia-2026-06-25",
        "norway-vs-france-2026-06-26",
        "senegal-vs-iraq-2026-06-26",
        "cabo-verde-vs-saudi-arabia-2026-06-26",
        "uruguay-vs-spain-2026-06-27",
        "panama-vs-england-2026-06-27",
        "croatia-vs-ghana-2026-06-27",
      ],
      notes: "Shared free-to-air FIFA World Cup 2026 coverage in the UK with BBC. Confirmed through 2026-06-27, including Norway vs France, Senegal vs Iraq, Cabo Verde vs Saudi Arabia, Uruguay vs Spain, Panama vs England, and Croatia vs Ghana.",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "gb",
      countryName: "United Kingdom",
      broadcaster: "STV",
      access: "Free",
      url: "https://player.stv.tv/",
      sourceName: "STV official FIFA World Cup 2026 fixtures",
      sourceUrl: 
        "https://player.stv.tv/fifa-worldcup-2026",
      lastChecked: "2026-07-10",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [
        "germany-vs-curacao-2026-06-14",
        "netherlands-vs-japan-2026-06-14",
        "sweden-vs-tunisia-2026-06-14",
        "spain-vs-cabo-verde-2026-06-15",
        "saudi-arabia-vs-uruguay-2026-06-15",
        "argentina-vs-algeria-2026-06-17",
        "england-vs-croatia-2026-06-17",
        "ghana-vs-panama-2026-06-18",
        "switzerland-vs-bosnia-and-herzegovina-2026-06-18",
        "canada-vs-qatar-2026-06-18",
        "scotland-vs-morocco-2026-06-19",
        "brazil-vs-haiti-2026-06-19",
        "turkiye-vs-paraguay-2026-06-19",
        "germany-vs-cote-d-ivoire-2026-06-20",
        "switzerland-vs-canada-2026-06-24",
        "bosnia-and-herzegovina-vs-qatar-2026-06-24",
        "turkiye-vs-usa-2026-06-25",
        "paraguay-vs-australia-2026-06-25",
        "norway-vs-france-2026-06-26",
        "senegal-vs-iraq-2026-06-26",
        "cabo-verde-vs-saudi-arabia-2026-06-26",
        "uruguay-vs-spain-2026-06-27",
        "croatia-vs-ghana-2026-06-27",
        "panama-vs-england-2026-06-27",
        "brazil-vs-japan-2026-06-29",
        "netherlands-vs-morocco-2026-06-30",
        "france-vs-sweden-2026-06-30",
        "mexico-vs-ecuador-2026-06-30",
        "belgium-vs-senegal-2026-07-01",
        "argentina-vs-cabo-verde-2026-07-03",
        "colombia-vs-ghana-2026-07-03",
        "argentina-vs-egypt-2026-07-07",
        "switzerland-vs-colombia-2026-07-07",
        "france-vs-morocco-2026-07-09",
        "norway-vs-england-2026-07-11",
        "argentina-vs-switzerland-2026-07-11",
      ],
      notes: "Free-to-air FIFA World Cup 2026 coverage in Scotland on STV and STV Player. Official STV fixture page confirms Norway vs England and Argentina vs Switzerland in the 2026-07-11 quarter-final window. The France semi-final on 2026-07-14 is listed as France vs TBA with TBC status and is not added.",
      commentaryLanguages: ["English"],
    },
  ],

  ie: [
    {
      countryCode: "ie",
      countryName: "Ireland",
      broadcaster: "RTÉ",
      access: "Free",
      url: "https://www.rte.ie/player/",
      sourceName: "FIFA World Cup 2026 licensees",
      sourceUrl: "https://inside.fifa.com/about-fifa/commercial/media-rights/licensees",
      lastChecked: "2026-06-10",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "FIFA World Cup 2026 coverage in Ireland",
      commentaryLanguages: ["English"],
    },
  ],

  au: [
    {
      countryCode: "au",
      countryName: "Australia",
      broadcaster: "SBS",
      access: "Free",
      url: "https://www.sbs.com.au/ondemand/fifa-world-cup-2026",
      sourceName: "SBS official World Cup coverage",
      sourceUrl: "https://www.sbs.com.au/ondemand/fifa-world-cup-2026",
      lastChecked: "2026-04-07",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Free full tournament coverage in Australia",
      commentaryLanguages: ["English"],
    },
  ],

  ch: [
    {
      countryCode: "ch",
      countryName: "Switzerland",
      broadcaster: "SRF",
      access: "Free",
      url: "https://www.srf.ch/play/tv",
      sourceName: "SRF / RTS official broadcast rights",
      sourceUrl: "https://www.rts.ch/sport/football/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Free coverage for German-speaking Switzerland",
      commentaryLanguages: ["German"],
    },
    {
      countryCode: "ch",
      countryName: "Switzerland",
      broadcaster: "RTS",
      access: "Free",
      url: "https://www.rts.ch/play/tv",
      sourceName: "SRF / RTS official broadcast rights",
      sourceUrl: "https://www.rts.ch/sport/football/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Free coverage for French-speaking Switzerland",
      commentaryLanguages: ["French"],
    },
  ],

  at: [
    {
      countryCode: "at",
      countryName: "Austria",
      broadcaster: "ORF",
      access: "Free",
      url: "https://tv.orf.at/",
      sourceName: "FIFA World Cup 2026 licensees",
      sourceUrl: "https://inside.fifa.com/about-fifa/commercial/media-rights/licensees",
      lastChecked: "2026-06-10",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [],
      notes: "FIFA World Cup 2026 coverage in Austria",
      commentaryLanguages: ["German"],
    },
    {
      countryCode: "at",
      countryName: "Austria",
      broadcaster: "ServusTV",
      access: "Free",
      url: "https://www.servustv.com/",
      sourceName: "FIFA World Cup 2026 licensees",
      sourceUrl: "https://inside.fifa.com/about-fifa/commercial/media-rights/licensees",
      lastChecked: "2026-06-10",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [],
      notes: "Shared FIFA World Cup 2026 coverage in Austria with ORF",
      commentaryLanguages: ["German"],
    },
  ],

  be: [
    {
      countryCode: "be",
      countryName: "Belgium",
      broadcaster: "RTBF",
      access: "Free",
      url: "https://www.rtbf.be/auvio/",
      sourceName: "RTBF official broadcast rights",
      sourceUrl: "https://www.rtbf.be/sport/football/",
      lastChecked: "2026-04-07",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Free full tournament coverage in Belgium",
      commentaryLanguages: ["French"],
    },
    {
      countryCode: "be",
      countryName: "Belgium",
      broadcaster: "VRT",
      access: "Free",
      url: "https://www.vrt.be/vrtmax/",
      sourceName: "VRT official broadcast rights",
      sourceUrl: "https://www.vrt.be/vrtmax/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Free full tournament coverage in Belgium",
      commentaryLanguages: ["Dutch"],
    },
  ],

  bg: [
    {
      countryCode: "bg",
      countryName: "Bulgaria",
      broadcaster: "BNT",
      access: "Free",
      url: "https://bnt.bg/",
      sourceName: "BNT official FIFA World Cup 2026 broadcast programme",
      sourceUrl: "https://imedia.bnt.bg/",
      lastChecked: "2026-06-14",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: ["germany-vs-curacao-2026-06-14"],
      notes: "Selected FIFA World Cup 2026 coverage in Bulgaria on BNT channels. Listed for Germany vs Curacao on 2026-06-14 from BNT World Cup broadcast programme.",
      commentaryLanguages: ["Bulgarian"],
    },
  ],

  fr: [
    {
      countryCode: "fr",
      countryName: "France",
      broadcaster: "M6",
      access: "Free",
      url: "https://www.m6.fr/",
      sourceName: "M6 official Coupe du Monde 2026 calendar",
      sourceUrl: 
        "https://actu.m6.fr/sport/calendrier-et-resultats-coupe-du-monde-2026-tous-les-matchs",
      lastChecked: "2026-07-17",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [
        "mexico-vs-south-africa-2026-06-11",
        "canada-vs-bosnia-and-herzegovina-2026-06-12",
        "brazil-vs-morocco-2026-06-13",
        "germany-vs-curacao-2026-06-14",
        "netherlands-vs-japan-2026-06-14",
        "spain-vs-cabo-verde-2026-06-15",
        "belgium-vs-egypt-2026-06-15",
        "saudi-arabia-vs-uruguay-2026-06-15",
        "france-vs-senegal-2026-06-16",
        "portugal-vs-dr-congo-2026-06-17",
        "england-vs-croatia-2026-06-17",
        "czechia-vs-south-africa-2026-06-18",
        "switzerland-vs-bosnia-and-herzegovina-2026-06-18",
        "usa-vs-australia-2026-06-19",
        "scotland-vs-morocco-2026-06-19",
        "netherlands-vs-sweden-2026-06-20",
        "germany-vs-cote-d-ivoire-2026-06-20",
        "spain-vs-saudi-arabia-2026-06-21",
        "belgium-vs-ir-iran-2026-06-21",
        "argentina-vs-austria-2026-06-22",
        "france-vs-iraq-2026-06-22",
        "portugal-vs-uzbekistan-2026-06-23",
        "england-vs-ghana-2026-06-23",
        "switzerland-vs-canada-2026-06-24",
        "scotland-vs-brazil-2026-06-24",
        "ecuador-vs-germany-2026-06-25",
        "tunisia-vs-netherlands-2026-06-25",
        "norway-vs-france-2026-06-26",
        "uruguay-vs-spain-2026-06-27",
        "panama-vs-england-2026-06-27",
        "colombia-vs-portugal-2026-06-27",
        "south-africa-vs-canada-2026-06-28",
        "cote-divoire-vs-norway-2026-06-30",
        "france-vs-sweden-2026-06-30",
        "england-vs-dr-congo-2026-07-01",
        "belgium-vs-senegal-2026-07-01",
        "spain-vs-austria-2026-07-02",
        "australia-vs-egypt-2026-07-03",
        "canada-vs-morocco-2026-07-04",
        "paraguay-vs-france-2026-07-04",
        "brazil-vs-norway-2026-07-05",
        "portugal-vs-spain-2026-07-06",
        "argentina-vs-egypt-2026-07-07",
        "switzerland-vs-colombia-2026-07-07",
        "france-vs-morocco-2026-07-09",
        "spain-vs-belgium-2026-07-10",
        "norway-vs-england-2026-07-11",
        "france-vs-spain-2026-07-14",
        "france-vs-england-2026-07-18",
        "spain-vs-argentina-2026-07-19",
      ],
      notes: "Selected free-to-air FIFA World Cup 2026 matches in France on M6 and M6+. Official M6 calendar confirms France vs England on 2026-07-18 and Spain vs Argentina on 2026-07-19 on M6/M6+.",
      commentaryLanguages: ["French"],
    },
    {
      countryCode: "fr",
      countryName: "France",
      broadcaster: "beIN SPORTS",
      access: "Paid",
      url: "https://www.beinsports.com/fr-fr/football/coupe-du-monde-de-la-fifa-2026",
      affiliateUrl: undefined,
      sourceName: "beIN SPORTS France World Cup 2026 page",
      sourceUrl:
        "https://www.beinsports.com/fr-fr/football/coupe-du-monde-de-la-fifa-2026",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage in France",
      commentaryLanguages: ["French"],
    },
  ],

  ca: [
    {
      countryCode: "ca",
      countryName: "Canada",
      broadcaster: "TSN",
      access: "Paid",
      url: "https://www.tsn.ca/",
      sourceName: "Bell Media FIFA World Cup 26 announcement",
      sourceUrl:
        "https://www.bellmedia.ca/the-lede/press/fifa-world-cup-26-is-one-year-away-and-tsn-counts-down-to-the-tournament-with-preview-specials-all-new-podcasts-and-more/",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Main English-language FIFA World Cup coverage in Canada",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "ca",
      countryName: "Canada",
      broadcaster: "CTV",
      access: "Free",
      url: "https://www.ctv.ca/",
      sourceName: "Bell Media FIFA World Cup 26 announcement",
      sourceUrl:
        "https://www.bellmedia.ca/the-lede/press/fifa-world-cup-26-is-one-year-away-and-tsn-counts-down-to-the-tournament-with-preview-specials-all-new-podcasts-and-more/",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected free-to-air FIFA World Cup coverage in Canada",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "ca",
      countryName: "Canada",
      broadcaster: "RDS",
      access: "Paid",
      url: "https://www.rds.ca/",
      sourceName: "Bell Media FIFA World Cup 26 announcement",
      sourceUrl:
        "https://www.bellmedia.ca/fr/ventes-publicitaires/ressources/nouvelles/opportunites-publicitaires-pour-la-coupe-du-monde-fifa-2026/",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "French-language FIFA World Cup coverage in Canada",
      commentaryLanguages: ["French"],
    },
  ],

  us: [
    {
      countryCode: "us",
      countryName: "United States",
      broadcaster: "FOX",
      access: "Free",
      url: "https://www.foxsports.com/soccer/fifa-world-cup-men",
      sourceName: "FOX official FIFA World Cup 2026 live pages",
      sourceUrl: 
        "https://www.fox.com/soccer/fifa-world-cup",
      lastChecked: "2026-07-17",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [
        "usa-vs-australia-2026-06-19",
        "scotland-vs-morocco-2026-06-19",
        "brazil-vs-haiti-2026-06-19",
        "netherlands-vs-sweden-2026-06-20",
        "germany-vs-cote-d-ivoire-2026-06-20",
        "switzerland-vs-canada-2026-06-24",
        "scotland-vs-brazil-2026-06-24",
        "czechia-vs-mexico-2026-06-24",
        "ecuador-vs-germany-2026-06-25",
        "japan-vs-sweden-2026-06-25",
        "turkiye-vs-usa-2026-06-25",
        "norway-vs-france-2026-06-26",
        "uruguay-vs-spain-2026-06-27",
        "new-zealand-vs-belgium-2026-06-26",
        "south-africa-vs-canada-2026-06-28",
        "brazil-vs-japan-2026-06-29",
        "germany-vs-paraguay-2026-06-29",
        "netherlands-vs-morocco-2026-06-30",
        "cote-divoire-vs-norway-2026-06-30",
        "france-vs-sweden-2026-06-30",
        "mexico-vs-ecuador-2026-06-30",
        "england-vs-dr-congo-2026-07-01",
        "usa-vs-bosnia-and-herzegovina-2026-07-01",
        "spain-vs-austria-2026-07-02",
        "portugal-vs-croatia-2026-07-02",
        "australia-vs-egypt-2026-07-03",
        "argentina-vs-cabo-verde-2026-07-03",
        "colombia-vs-ghana-2026-07-03",
        "brazil-vs-norway-2026-07-05",
        "mexico-vs-england-2026-07-05",
        "argentina-vs-egypt-2026-07-07",
        "switzerland-vs-colombia-2026-07-07",
        "france-vs-morocco-2026-07-09",
        "spain-vs-belgium-2026-07-10",
        "norway-vs-england-2026-07-11",
        "argentina-vs-switzerland-2026-07-11",
        "france-vs-spain-2026-07-14",
        "france-vs-england-2026-07-18",
        "spain-vs-argentina-2026-07-19",
      ],
      notes: "Selected English-language FIFA World Cup coverage in the United States. FOX official pages confirm France vs England on 2026-07-18 and Spain vs Argentina on 2026-07-19 on FOX, FOX One and FOX Sports. Matches listed only on FS1 remain excluded from this partial FOX object.",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "us",
      countryName: "United States",
      broadcaster: "FS1",
      access: "Paid",
      url: "https://www.foxsports.com/live/fs1",
      sourceName: "FOX Sports FIFA World Cup coverage",
      sourceUrl: "https://www.foxsports.com/",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "English-language FIFA World Cup coverage in the United States",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "us",
      countryName: "United States",
      broadcaster: "Telemundo",
      access: "Free",
      url: "https://www.telemundo.com/deportes",
      sourceName: "Telemundo official FIFA World Cup transmission calendar",
      sourceUrl: 
        "https://www.telemundo.com/deportes/copa-mundial-de-la-fifa-2026/calendario-de-transmisiones-de-la-copa-mundial-de-la-fifa-2026-por-tel-rcna261413",
      lastChecked: "2026-07-17",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [
        "usa-vs-australia-2026-06-19",
        "scotland-vs-morocco-2026-06-19",
        "brazil-vs-haiti-2026-06-19",
        "turkiye-vs-paraguay-2026-06-19",
        "netherlands-vs-sweden-2026-06-20",
        "germany-vs-cote-d-ivoire-2026-06-20",
        "ecuador-vs-curacao-2026-06-20",
        "tunisia-vs-japan-2026-06-21",
        "switzerland-vs-canada-2026-06-24",
        "bosnia-and-herzegovina-vs-qatar-2026-06-24",
        "scotland-vs-brazil-2026-06-24",
        "morocco-vs-haiti-2026-06-24",
        "czechia-vs-mexico-2026-06-24",
        "south-africa-vs-south-korea-2026-06-24",
        "ecuador-vs-germany-2026-06-25",
        "japan-vs-sweden-2026-06-25",
        "paraguay-vs-australia-2026-06-25",
        "turkiye-vs-usa-2026-06-25",
        "norway-vs-france-2026-06-26",
        "senegal-vs-iraq-2026-06-26",
        "uruguay-vs-spain-2026-06-27",
        "cabo-verde-vs-saudi-arabia-2026-06-26",
        "new-zealand-vs-belgium-2026-06-26",
        "egypt-vs-ir-iran-2026-06-26",
        "panama-vs-england-2026-06-27",
        "colombia-vs-portugal-2026-06-27",
        "south-africa-vs-canada-2026-06-28",
        "brazil-vs-japan-2026-06-29",
        "germany-vs-paraguay-2026-06-29",
        "netherlands-vs-morocco-2026-06-30",
        "cote-divoire-vs-norway-2026-06-30",
        "france-vs-sweden-2026-06-30",
        "mexico-vs-ecuador-2026-06-30",
        "england-vs-dr-congo-2026-07-01",
        "belgium-vs-senegal-2026-07-01",
        "usa-vs-bosnia-and-herzegovina-2026-07-01",
        "spain-vs-austria-2026-07-02",
        "portugal-vs-croatia-2026-07-02",
        "switzerland-vs-algeria-2026-07-02",
        "australia-vs-egypt-2026-07-03",
        "argentina-vs-cabo-verde-2026-07-03",
        "colombia-vs-ghana-2026-07-03",
        "brazil-vs-norway-2026-07-05",
        "mexico-vs-england-2026-07-05",
        "argentina-vs-egypt-2026-07-07",
        "switzerland-vs-colombia-2026-07-07",
        "france-vs-morocco-2026-07-09",
        "spain-vs-belgium-2026-07-10",
        "norway-vs-england-2026-07-11",
        "argentina-vs-switzerland-2026-07-11",
        "france-vs-spain-2026-07-14",
        "france-vs-england-2026-07-18",
        "spain-vs-argentina-2026-07-19",
      ],
      notes: "Spanish-language FIFA World Cup coverage in the United States. Official Telemundo transmission calendar confirms France vs England on 2026-07-18 and Spain vs Argentina on 2026-07-19 on Telemundo and Peacock.",
      commentaryLanguages: ["Spanish"],
    },
    {
      countryCode: "us",
      countryName: "United States",
      broadcaster: "Universo",
      access: "Paid",
      url: "https://www.telemundo.com/universo",
      sourceName: "NBCUniversal Universo coverage",
      sourceUrl:
        "https://www.nbcuniversal.com/article/telemundo-unveils-most-extensive-spanish-language-fifa-world-cuptm-presentation-broadcast-television",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Spanish-language cable coverage in the United States",
      commentaryLanguages: ["Spanish"],
    },
    {
      countryCode: "us",
      countryName: "United States",
      broadcaster: "Peacock",
      access: "Paid",
      url: "https://www.peacocktv.com/",
      sourceName: "NBCUniversal Peacock World Cup streaming",
      sourceUrl:
        "https://www.nbcuniversal.com/article/telemundo-unveils-most-extensive-spanish-language-fifa-world-cuptm-presentation-broadcast-television",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Spanish-language streaming coverage in the United States",
      commentaryLanguages: ["Spanish"],
    },
  ],

  es: [
    {
      countryCode: "es",
      countryName: "Spain",
      broadcaster: "RTVE",
      access: "Free",
      url: "https://www.rtve.es/play/",
      sourceName: "RTVE official Mundial 2026 direct schedule",
      sourceUrl: 
        "https://www.rtve.es/play/videos/directo/mundial-2026-partidos-programas/",
      lastChecked: "2026-07-17",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [
        "brazil-vs-morocco-2026-06-13",
        "germany-vs-curacao-2026-06-14",
        "france-vs-senegal-2026-06-16",
        "england-vs-croatia-2026-06-17",
        "usa-vs-australia-2026-06-19",
        "scotland-vs-brazil-2026-06-24",
        "ecuador-vs-germany-2026-06-25",
        "uruguay-vs-spain-2026-06-27",
        "spain-vs-austria-2026-07-02",
        "argentina-vs-cabo-verde-2026-07-03",
        "brazil-vs-norway-2026-07-05",
        "argentina-vs-egypt-2026-07-07",
        "spain-vs-belgium-2026-07-10",
        "france-vs-spain-2026-07-14",
        "france-vs-england-2026-07-18",
        "spain-vs-argentina-2026-07-19",
      ],
      notes: "Free-to-air / RTVE Play selected FIFA World Cup coverage in Spain. RTVE official live schedule confirms France vs England on 2026-07-18 and Spain vs Argentina on 2026-07-19 via RTVE en directo / RTVE Play.",
      commentaryLanguages: ["Spanish"],
    },
    {
      countryCode: "es",
      countryName: "Spain",
      broadcaster: "Movistar+",
      access: "Paid",
      url: "https://www.movistarplus.es/",
      sourceName: "Movistar+ football coverage",
      sourceUrl: "https://www.movistarplus.es/deportes/futbol",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Full tournament coverage via subscription",
      commentaryLanguages: ["Spanish"],
    },
  ],

  pt: [
    {
      countryCode: "pt",
      countryName: "Portugal",
      broadcaster: "RTP1",
      access: "Free",
      url: "https://www.rtp.pt/play/",
      sourceName: "RTP FIFA World Cup coverage",
      sourceUrl: "https://www.rtp.pt/",
      lastChecked: "2026-05-30",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected FIFA World Cup 2026 matches in Portugal",
      commentaryLanguages: ["Portuguese"],
    },
    {
      countryCode: "pt",
      countryName: "Portugal",
      broadcaster: "Sport TV",
      access: "Paid",
      url: "https://www.sporttv.pt/mundial-fifa-2026",
      sourceName: "Sport TV official FIFA World Cup 2026 coverage",
      sourceUrl: "https://www.sporttv.pt/mundial-fifa-2026",
      lastChecked: "2026-06-26",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      matchSlugs: [],
      notes: "Paid full tournament coverage in Portugal. Sport TV official page confirms all 104 FIFA World Cup 2026 matches, with 70 exclusive matches, mainly on SPORT.TV5 and the remaining matches on SPORT.TV1.",
      commentaryLanguages: ["Portuguese"],
    },
  ],

  tr: [
    {
      countryCode: "tr",
      countryName: "Turkey",
      broadcaster: "TRT 1",
      access: "Free",
      url: "https://www.trt1.com.tr/",
      sourceName: "TRT 1 official Germany vs Curacao match page",
      sourceUrl:
        "https://www.trt1.com.tr/tv/2026-dunya-kupasi/almanya-curacao-or-2026-dunya-kupasi-grup-maci",
      lastChecked: "2026-06-14",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: ["germany-vs-curacao-2026-06-14"],
      notes: "Selected FIFA World Cup 2026 coverage in Turkey. Confirmed by TRT 1 for Germany vs Curacao on 2026-06-14.",
      commentaryLanguages: ["Turkish"],
    },
  ],

  se: [
    {
      countryCode: "se",
      countryName: "Sweden",
      broadcaster: "SVT",
      access: "Free",
      url: "https://www.svtplay.se/",
      sourceName: "SVT World Cup coverage",
      sourceUrl: "https://www.svt.se/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Shared rights, broadcasts many matches",
      commentaryLanguages: ["Swedish"],
    },
    {
      countryCode: "se",
      countryName: "Sweden",
      broadcaster: "TV4",
      access: "Free",
      url: "https://www.tv4play.se/",
      sourceName: "TV4 sports rights",
      sourceUrl: "https://www.tv4.se/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Co-broadcast with SVT",
      commentaryLanguages: ["Swedish"],
    },
  ],

  no: [
    {
      countryCode: "no",
      countryName: "Norway",
      broadcaster: "NRK",
      access: "Free",
      url: "https://tv.nrk.no/",
      sourceName: "NRK sports rights",
      sourceUrl: "https://www.nrk.no/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free matches including major fixtures",
      commentaryLanguages: ["Norwegian"],
    },
    {
      countryCode: "no",
      countryName: "Norway",
      broadcaster: "TV2",
      access: "Paid",
      url: "https://www.tv2.no/play/",
      sourceName: "TV2 premium sports",
      sourceUrl: "https://www.tv2.no/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Full coverage via subscription",
      commentaryLanguages: ["Norwegian"],
    },
  ],

  dk: [
    {
      countryCode: "dk",
      countryName: "Denmark",
      broadcaster: "DR",
      access: "Free",
      url: "https://www.dr.dk/drtv/",
      sourceName: "DR World Cup coverage",
      sourceUrl: "https://www.dr.dk/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Shared free coverage",
      commentaryLanguages: ["Danish"],
    },
    {
      countryCode: "dk",
      countryName: "Denmark",
      broadcaster: "TV2",
      access: "Free",
      url: "https://play.tv2.dk/",
      sourceName: "TV2 Denmark sports rights",
      sourceUrl: "https://www.tv2.dk/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Co-broadcast with DR",
      commentaryLanguages: ["Danish"],
    },
  ],

  fi: [
    {
      countryCode: "fi",
      countryName: "Finland",
      broadcaster: "YLE",
      access: "Free",
      url: "https://areena.yle.fi/",
      sourceName: "YLE sports rights",
      sourceUrl: "https://yle.fi/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Full or near full tournament coverage",
      commentaryLanguages: ["Finnish"],
    },
  ],

  is: [
    {
      countryCode: "is",
      countryName: "Iceland",
      broadcaster: "RUV",
      access: "Free",
      url: "https://www.ruv.is/sjonvarp",
      sourceName: "RUV World Cup coverage",
      sourceUrl: "https://www.ruv.is/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Full tournament coverage",
      commentaryLanguages: ["Icelandic"],
    },
  ],

  nl: [
    {
      countryCode: "nl",
      countryName: "Netherlands",
      broadcaster: "NOS",
      access: "Free",
      url: "https://nos.nl/sport",
      sourceName: "NOS FIFA World Cup rights",
      sourceUrl:
        "https://www.insideworldfootball.com/2024/09/16/nos-keeps-hold-world-cup-rights-2026-2030/",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Free FIFA World Cup coverage in the Netherlands",
      commentaryLanguages: ["Dutch"],
    },
  ],

  in: [
    {
      countryCode: "in",
      countryName: "India",
      broadcaster: "DD Sports",
      access: "Free",
      url: "https://prasarbharati.gov.in/",
      sourceName: "Prasar Bharati sports rights",
      sourceUrl: "https://prasarbharati.gov.in/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected matches on free TV",
      commentaryLanguages: ["Hindi", "English"],
    },
    {
      countryCode: "in",
      countryName: "India",
      broadcaster: "ZEE5",
      access: "Paid",
      url: "https://www.zee5.com/sports/football/fifa-world-cup/2026",
      sourceName: "ZEE5 official FIFA World Cup 2026 help center",
      sourceUrl:
        "https://helpcenter.zee5.com/portal/en/kb/articles/watch-fifa-world-cup-2026-on-zee5",
      lastChecked: "2026-06-18",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      matchSlugs: [],
      notes:
        "Official digital streaming coverage in India. ZEE5 help center confirms all 104 FIFA World Cup 2026 matches live on ZEE5 with subscription plans starting at ₹799.",
      commentaryLanguages: ["English", "Hindi", "Bangla", "Malayalam"],
    },
    {
      countryCode: "in",
      countryName: "India",
      broadcaster: "JioCinema",
      access: "Free",
      url: "https://www.jiocinema.com/",
      sourceName: "JioCinema FIFA coverage",
      sourceUrl: "https://www.jiocinema.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Full tournament streaming free in India",
      commentaryLanguages: ["Hindi", "English", "Regional"],
    },
  ],

  cn: [
    {
      countryCode: "cn",
      countryName: "China",
      broadcaster: "CCTV",
      access: "Free",
      url: "https://tv.cctv.com/",
      sourceName: "CCTV sports rights",
      sourceUrl: "https://tv.cctv.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Official broadcaster with wide free coverage",
      commentaryLanguages: ["Chinese"],
    },
    {
      countryCode: "cn",
      countryName: "China",
      broadcaster: "Migu",
      access: "Paid",
      url: "https://www.miguvideo.com/",
      sourceName: "Migu sports streaming",
      sourceUrl: "https://www.miguvideo.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Premium streaming platform",
      commentaryLanguages: ["Chinese"],
    },
  ],

  ma: [
    {
      countryCode: "ma",
      countryName: "Morocco",
      broadcaster: "SNRT",
      access: "Free",
      url: "https://snrt.ma/",
      sourceName: "SNRT sports coverage",
      sourceUrl: "https://snrt.ma/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["Arabic", "French"],
    },
    {
      countryCode: "ma",
      countryName: "Morocco",
      broadcaster: "beIN Sports",
      access: "Paid",
      url: "https://www.beinsports.com/",
      sourceName: "beIN Sports MENA coverage",
      sourceUrl: "https://www.beinsports.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage",
      commentaryLanguages: ["Arabic"],
    },
    {
      countryCode: "ma",
      countryName: "Morocco",
      broadcaster: "Arryadia TNT",
      access: "Free",
      url: "https://arryadia.snrt.ma/",
      sourceName: "SNRT Arryadia",
      sourceUrl: "https://arryadia.snrt.ma/",
      lastChecked: "2026-06-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      matchSlugs: [],
      notes: "Free-to-air terrestrial coverage via Arryadia TNT",
      commentaryLanguages: ["Arabic"],
    },
  ],

  dz: [
    {
      countryCode: "dz",
      countryName: "Algeria",
      broadcaster: "ENTV",
      access: "Free",
      url: "https://www.entv.dz/",
      sourceName: "ENTV sports coverage",
      sourceUrl: "https://www.entv.dz/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["Arabic"],
    },
    {
      countryCode: "dz",
      countryName: "Algeria",
      broadcaster: "beIN Sports",
      access: "Paid",
      url: "https://www.beinsports.com/",
      sourceName: "beIN Sports MENA coverage",
      sourceUrl: "https://www.beinsports.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage",
      commentaryLanguages: ["Arabic"],
    },
  ],

  tn: [
    {
      countryCode: "tn",
      countryName: "Tunisia",
      broadcaster: "Wataniya",
      access: "Free",
      url: "https://www.watania1.tn/",
      sourceName: "Wataniya sports coverage",
      sourceUrl: "https://www.watania1.tn/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["Arabic"],
    },
    {
      countryCode: "tn",
      countryName: "Tunisia",
      broadcaster: "beIN Sports",
      access: "Paid",
      url: "https://www.beinsports.com/",
      sourceName: "beIN Sports MENA coverage",
      sourceUrl: "https://www.beinsports.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage",
      commentaryLanguages: ["Arabic"],
    },
  ],

  eg: [
    {
      countryCode: "eg",
      countryName: "Egypt",
      broadcaster: "ON Time Sports",
      access: "Free",
      url: "https://www.youtube.com/@ONTimeSports",
      sourceName: "ON Time Sports coverage",
      sourceUrl: "https://www.ontime.live/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected free coverage",
      commentaryLanguages: ["Arabic"],
    },
    {
      countryCode: "eg",
      countryName: "Egypt",
      broadcaster: "beIN Sports",
      access: "Paid",
      url: "https://www.beinsports.com/",
      sourceName: "beIN Sports MENA coverage",
      sourceUrl: "https://www.beinsports.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage",
      commentaryLanguages: ["Arabic"],
    },
  ],

  sn: [
    {
      countryCode: "sn",
      countryName: "Senegal",
      broadcaster: "RTS",
      access: "Free",
      url: "https://www.rts.sn/",
      sourceName: "RTS Senegal sports coverage",
      sourceUrl: "https://www.rts.sn/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["French"],
    },
    {
      countryCode: "sn",
      countryName: "Senegal",
      broadcaster: "beIN Sports",
      access: "Paid",
      url: "https://www.beinsports.com/",
      sourceName: "beIN Sports MENA coverage",
      sourceUrl: "https://www.beinsports.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage",
      commentaryLanguages: ["Arabic"],
    },
  ],

  ci: [
    {
      countryCode: "ci",
      countryName: "Ivory Coast",
      broadcaster: "RTI",
      access: "Free",
      url: "https://www.rti.ci/",
      sourceName: "RTI sports coverage",
      sourceUrl: "https://www.rti.ci/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["French"],
    },
    {
      countryCode: "ci",
      countryName: "Ivory Coast",
      broadcaster: "beIN Sports",
      access: "Paid",
      url: "https://www.beinsports.com/",
      sourceName: "beIN Sports MENA coverage",
      sourceUrl: "https://www.beinsports.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage",
      commentaryLanguages: ["Arabic"],
    },
  ],

  ng: [
    {
      countryCode: "ng",
      countryName: "Nigeria",
      broadcaster: "NTA",
      access: "Free",
      url: "https://nta.ng/",
      sourceName: "NTA sports coverage",
      sourceUrl: "https://nta.ng/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "ng",
      countryName: "Nigeria",
      broadcaster: "SuperSport",
      access: "Paid",
      url: "https://www.supersport.com/",
      sourceName: "SuperSport coverage",
      sourceUrl: "https://www.supersport.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full coverage",
      commentaryLanguages: ["English"],
    },
  ],

  gh: [
    {
      countryCode: "gh",
      countryName: "Ghana",
      broadcaster: "GTV",
      access: "Free",
      url: "https://www.gbcghanaonline.com/gtv/",
      sourceName: "GTV sports coverage",
      sourceUrl: "https://www.gbcghanaonline.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "gh",
      countryName: "Ghana",
      broadcaster: "SuperSport",
      access: "Paid",
      url: "https://www.supersport.com/",
      sourceName: "SuperSport coverage",
      sourceUrl: "https://www.supersport.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full coverage",
      commentaryLanguages: ["English"],
    },
  ],

  za: [
    {
      countryCode: "za",
      countryName: "South Africa",
      broadcaster: "New World TV",
      access: "Paid",
      url: "https://www.newworldtv.com/",
      sourceName: "FIFA World Cup 2026 Media Partners",
      sourceUrl: "https://inside.fifa.com/",
      lastChecked: "2026-06-11",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [],
      notes:
        "Official FIFA media partner for South Africa. Access model to verify before marking as free.",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "za",
      countryName: "South Africa",
      broadcaster: "Sporty TV",
      access: "Paid",
      url: "https://sporty.com/",
      sourceName: "FIFA World Cup 2026 Media Partners",
      sourceUrl: "https://inside.fifa.com/",
      lastChecked: "2026-06-11",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [],
      notes:
        "Official FIFA media partner for South Africa. Access model to verify before marking as free.",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "za",
      countryName: "South Africa",
      broadcaster: "SuperSport International",
      access: "Paid",
      url: "https://www.supersport.com/",
      sourceName: "FIFA World Cup 2026 Media Partners",
      sourceUrl: "https://inside.fifa.com/",
      lastChecked: "2026-06-11",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [],
      notes:
        "Official FIFA media partner for South Africa. Access model to verify before marking as free.",
      commentaryLanguages: ["English"],
    },
  ],

  cm: [
    {
      countryCode: "cm",
      countryName: "Cameroon",
      broadcaster: "CRTV",
      access: "Free",
      url: "https://www.crtv.cm/",
      sourceName: "CRTV sports coverage",
      sourceUrl: "https://www.crtv.cm/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["French"],
    },
    {
      countryCode: "cm",
      countryName: "Cameroon",
      broadcaster: "SuperSport",
      access: "Paid",
      url: "https://www.supersport.com/",
      sourceName: "SuperSport coverage",
      sourceUrl: "https://www.supersport.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full coverage",
      commentaryLanguages: ["English"],
    },
  ],

  cd: [
    {
      countryCode: "cd",
      countryName: "DR Congo",
      broadcaster: "RTNC",
      access: "Free",
      url: "https://www.rtnc.cd/",
      sourceName: "RTNC sports coverage",
      sourceUrl: "https://www.rtnc.cd/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["French"],
    },
    {
      countryCode: "cd",
      countryName: "DR Congo",
      broadcaster: "SuperSport",
      access: "Paid",
      url: "https://www.supersport.com/",
      sourceName: "SuperSport coverage",
      sourceUrl: "https://www.supersport.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full coverage",
      commentaryLanguages: ["English"],
    },
  ],

  de: [
    {
      countryCode: "de",
      countryName: "Germany",
      broadcaster: "ARD",
      access: "Free",
      url: "https://www.ardmediathek.de/",
      sourceName: "ARD and ZDF official World Cup 2026 match split",
      sourceUrl:
        "https://presseportal.zdf.de/pressemitteilung/fifa-fussball-wm-2026-eroeffnungsspiel-und-finale-live-im-zdf",
      lastChecked: "2026-06-14",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: ["germany-vs-curacao-2026-06-14"],
      notes: "Selected free-to-air FIFA World Cup 2026 matches in Germany. Confirmed for Germany vs Curacao on Das Erste and ARD Mediathek on 2026-06-14.",
      commentaryLanguages: ["German"],
    },
    {
      countryCode: "de",
      countryName: "Germany",
      broadcaster: "ZDF",
      access: "Free",
      url: "https://www.zdf.de/sport",
      sourceName: "ZDF official FIFA World Cup 2026 livestream schedule",
      sourceUrl:
        "https://www.zdf.de/video/livestreams/fifa-weltmeisterschaft-live-livestream-highlights-100/spanien-argentinien-finale-livestream-100",
      lastChecked: "2026-07-17",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: ["spain-vs-argentina-2026-07-19"],
      notes: "Selected free-to-air FIFA World Cup 2026 matches in Germany. ZDF official livestream schedule confirms Spain vs Argentina on 2026-07-19 on ZDF / ZDFmediathek.",
      commentaryLanguages: ["German"],
    },
    {
      countryCode: "de",
      countryName: "Germany",
      broadcaster: "MagentaTV",
      access: "Paid",
      url: "https://www.magentatv.de/",
      sourceName: "MagentaTV FIFA World Cup 2026 rights",
      sourceUrl:
        "https://www.heise.de/en/news/ARD-and-ZDF-to-broadcast-60-matches-of-the-2026-World-Cup-10730703.html",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage in Germany",
      commentaryLanguages: ["German"],
    },
  ],

  it: [
    {
      countryCode: "it",
      countryName: "Italy",
      broadcaster: "RAI",
      access: "Free",
      url: "https://www.raiplay.it/",
      sourceName: "RAI FIFA World Cup 2026 rights",
      sourceUrl:
        "https://www.insideworldfootball.com/2026/03/02/rai-agree-free-air-package-2026-world-cup-italy-still-qualify/",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free-to-air package of selected FIFA World Cup 2026 matches in Italy",
      commentaryLanguages: ["Italian"],
    },
    {
      countryCode: "it",
      countryName: "Italy",
      broadcaster: "DAZN Italy",
      access: "Paid",
      url: "https://www.dazn.com/it-IT/home",
      sourceName: "DAZN Group official FIFA World Cup 2026 Italy announcement",
      sourceUrl:
        "https://dazngroup.com/press-room/in-italy-dazn-will-be-the-only-place-to-watch-the-entire-fifa-world-cup-2026/",
      lastChecked: "2026-06-26",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      matchSlugs: [],
      notes: "Paid full tournament coverage in Italy. DAZN Group official announcement confirms DAZN will broadcast all 104 FIFA World Cup 2026 matches in Italy.",
      commentaryLanguages: ["Italian"],
    },
  ],

  mx: [
    {
      countryCode: "mx",
      countryName: "Mexico",
      broadcaster: "Televisa",
      access: "Free",
      url: "https://www.televisa.com/",
      sourceName: "TUDN official TelevisaUnivision World Cup schedule",
      sourceUrl: 
        "https://www.tudn.com/mundial-2026/calendario-mundial-2026-los-partidos-que-van-por-tv-abierta-y-por-vix",
      lastChecked: "2026-07-17",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [
        "czechia-vs-mexico-2026-06-24",
        "ecuador-vs-germany-2026-06-25",
        "uruguay-vs-spain-2026-06-27",
        "mexico-vs-ecuador-2026-06-30",
        "belgium-vs-senegal-2026-07-01",
        "spain-vs-austria-2026-07-02",
        "argentina-vs-cabo-verde-2026-07-03",
        "mexico-vs-england-2026-07-05",
        "argentina-vs-egypt-2026-07-07",
        "france-vs-morocco-2026-07-09",
        "norway-vs-england-2026-07-11",
        "france-vs-spain-2026-07-14",
        "spain-vs-argentina-2026-07-19",
      ],
      notes: "Free-to-air FIFA World Cup coverage in Mexico through TelevisaUnivision channels. Official TUDN schedule confirms Match 104 on 2026-07-19 on Las Estrellas, Canal 5, TUDN and ViX, identified as Spain vs Argentina. Match 103 / France vs England is ViX-only and remains excluded from this open-TV Televisa object.",
      commentaryLanguages: ["Spanish"],
    },
    {
      countryCode: "mx",
      countryName: "Mexico",
      broadcaster: "TV Azteca",
      access: "Free",
      url: "https://www.tvazteca.com/",
      sourceName: "TV Azteca official Mexico vs England match page",
      sourceUrl:
        "https://www.tvazteca.com/azteca7/mundial2026/mexico-vs-inglaterra-azteca-7-horario-fecha-en-vivo-partido-octavos-mundial-2026/",
      lastChecked: "2026-07-04",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [
        "czechia-vs-mexico-2026-06-24",
        "ecuador-vs-germany-2026-06-25",
        "uruguay-vs-spain-2026-06-27",
        "germany-vs-paraguay-2026-06-29",
        "mexico-vs-ecuador-2026-06-30",
        "mexico-vs-england-2026-07-05",
      ],
      notes: "Free-to-air / digital FIFA World Cup 2026 coverage in Mexico. TV Azteca official page confirms Mexico vs England can be watched free on Azteca 7 on 2026-07-05.",
      commentaryLanguages: ["Spanish"],
    },
    {
      countryCode: "mx",
      countryName: "Mexico",
      broadcaster: "TUDN",
      access: "Paid",
      url: "https://www.tudn.com/",
      sourceName: "TUDN football coverage",
      sourceUrl: "https://www.tudn.com/",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid FIFA World Cup coverage in Mexico",
      commentaryLanguages: ["Spanish"],
    },
  ],

  br: [
    {
      countryCode: "br",
      countryName: "Brazil",
      broadcaster: "Globo",
      access: "Free",
      url: "https://globoplay.globo.com/",
      sourceName: "ge.globo Brazil vs Norway match page",
      sourceUrl:
        "https://ge.globo.com/futebol/copa-do-mundo/noticia/2026/06/30/brasil-x-noruega-nas-oitavas-de-final-da-copa-do-mundo-veja-data-e-onde-assistir.ghtml",
      lastChecked: "2026-07-04",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [
        "brazil-vs-morocco-2026-06-13",
        "netherlands-vs-japan-2026-06-14",
        "brazil-vs-norway-2026-07-05",
      ],
      notes: "Free-to-air FIFA World Cup coverage in Brazil. ge.globo confirms Brazil vs Norway on 2026-07-05 via TV Globo, ge tv and ge.globo; sportv remains excluded here because it is modeled separately as full paid coverage.",
      commentaryLanguages: ["Portuguese"],
    },
    {
      countryCode: "br",
      countryName: "Brazil",
      broadcaster: "SporTV",
      access: "Paid",
      url: "https://sportv.globo.com/",
      sourceName: "Brazil FIFA World Cup 2026 broadcasting guide",
      sourceUrl:
        "https://www.lance.com.br/lancepedia/transmissao-tv-copa-do-mundo-2026.html",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid FIFA World Cup coverage in Brazil",
      commentaryLanguages: ["Portuguese"],
    },
    {
      countryCode: "br",
      countryName: "Brazil",
      broadcaster: "SBT",
      access: "Free",
      url: "https://www.sbt.com.br/",
      sourceName: "SBT and N Sports official Brazil World Cup coverage",
      sourceUrl:
        "https://sports.sbt.com.br/noticia/sbt-sports/sbt-e-n-sports-transmitem-todos-jogos-do-brasil-na-copa",
      lastChecked: "2026-07-04",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [
        "brazil-vs-morocco-2026-06-13",
        "netherlands-vs-japan-2026-06-14",
        "england-vs-croatia-2026-06-17",
        "switzerland-vs-bosnia-and-herzegovina-2026-06-18",
        "brazil-vs-haiti-2026-06-19",
        "germany-vs-cote-d-ivoire-2026-06-20",
        "scotland-vs-brazil-2026-06-24",
        "brazil-vs-japan-2026-06-29",
        "spain-vs-austria-2026-07-02",
        "argentina-vs-cabo-verde-2026-07-03",
        "brazil-vs-norway-2026-07-05",
      ],
      notes: "Selected free-to-air FIFA World Cup matches in Brazil on SBT and +SBT. Official SBT / N Sports coverage confirms all Brazil matches; Brazil vs Norway is Brazil's 2026-07-05 Round of 16 match.",
      commentaryLanguages: ["Portuguese"],
    },
    {
      countryCode: "br",
      countryName: "Brazil",
      broadcaster: "N Sports",
      access: "Free",
      url: "https://www.nsports.com.br/",
      sourceName: "SBT and N Sports official Brazil World Cup coverage",
      sourceUrl:
        "https://sports.sbt.com.br/noticia/sbt-sports/sbt-e-n-sports-transmitem-todos-jogos-do-brasil-na-copa",
      lastChecked: "2026-07-04",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [
        "brazil-vs-morocco-2026-06-13",
        "netherlands-vs-japan-2026-06-14",
        "england-vs-croatia-2026-06-17",
        "switzerland-vs-bosnia-and-herzegovina-2026-06-18",
        "brazil-vs-haiti-2026-06-19",
        "germany-vs-cote-d-ivoire-2026-06-20",
        "scotland-vs-brazil-2026-06-24",
        "brazil-vs-japan-2026-06-29",
        "spain-vs-austria-2026-07-02",
        "argentina-vs-cabo-verde-2026-07-03",
        "brazil-vs-norway-2026-07-05",
      ],
      notes: "Streaming / pay-TV coverage associated with SBT World Cup coverage through the SBT and N Sports partnership. Official SBT / N Sports coverage confirms all Brazil matches; Brazil vs Norway is Brazil's 2026-07-05 Round of 16 match.",
      commentaryLanguages: ["Portuguese"],
    },
    {
      countryCode: "br",
      countryName: "Brazil",
      broadcaster: "CazéTV",
      access: "Free",
      url: "https://www.youtube.com/@CazeTV",
      sourceName: "CazéTV FIFA World Cup 2026 rights",
      sourceUrl:
        "https://apnews.com/article/08feed47be7b423bafcfe9ae941bed1b",
      lastChecked: "2026-06-10",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Free streaming coverage of all 104 FIFA World Cup 2026 matches in Brazil",
      commentaryLanguages: ["Portuguese"],
    },
  ],

  cl: [
    {
      countryCode: "cl",
      countryName: "Chile",
      broadcaster: "Chilevisión",
      access: "Free",
      url: "https://www.chilevision.cl/",
      sourceName: "Chilevisión official World Cup 2026 match list",
      sourceUrl:
        "https://www.chilevision.cl/chv-deportes/futbol-internacional/para-no-perderse-nada-todos-los-partidos-que-transmitira-chilevision-en-el-mundial-2026/",
      lastChecked: "2026-07-02",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [
        "qatar-vs-switzerland-2026-06-13",
        "brazil-vs-morocco-2026-06-13",
        "netherlands-vs-japan-2026-06-14",
        "cote-divoire-vs-ecuador-2026-06-14",
        "france-vs-senegal-2026-06-16",
        "argentina-vs-algeria-2026-06-16",
        "argentina-vs-algeria-2026-06-17",
        "england-vs-croatia-2026-06-17",
        "uzbekistan-vs-colombia-2026-06-18",
        "switzerland-vs-bosnia-and-herzegovina-2026-06-18",
        "canada-vs-qatar-2026-06-18",
        "usa-vs-australia-2026-06-19",
        "scotland-vs-morocco-2026-06-19",
        "tunisia-vs-japan-2026-06-21",
        "germany-vs-cote-d-ivoire-2026-06-20",
        "scotland-vs-brazil-2026-06-24",
        "czechia-vs-mexico-2026-06-24",
        "ecuador-vs-germany-2026-06-25",
        "tunisia-vs-netherlands-2026-06-25",
        "paraguay-vs-australia-2026-06-25",
        "norway-vs-france-2026-06-26",
        "uruguay-vs-spain-2026-06-27",
        "colombia-vs-portugal-2026-06-27",
        "belgium-vs-senegal-2026-07-01",
        "spain-vs-austria-2026-07-02",
        "portugal-vs-croatia-2026-07-02",
        "argentina-vs-cabo-verde-2026-07-03",
        "colombia-vs-ghana-2026-07-03",
      ],
      notes: "Selected free-to-air FIFA World Cup 2026 matches in Chile on Chilevisión, Chilevision.cl, and the MiCHV app. Official Chilevisión Round of 32 schedule confirms Argentina vs Cabo Verde and Colombia vs Ghana for the 2026-07-03 update window. Australia vs Egypt is listed in the fixture article but not marked as transmitted by CHV.",
      commentaryLanguages: ["Spanish"],
    },
  ],

  co: [
    {
      countryCode: "co",
      countryName: "Colombia",
      broadcaster: "Caracol TV",
      access: "Free",
      url: "https://www.caracoltv.com/programacion",
      sourceName: "Gol Caracol official World Cup 2026 match schedule",
      sourceUrl:
        "https://www.noticiascaracol.com/golcaracol/seleccion-colombia/que-partidos-del-mundial-2026-se-veran-en-vivo-en-gol-caracol-y-ditu-dia-y-hora-para-colombia-rg10",
      lastChecked: "2026-07-02",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [
        "brazil-vs-morocco-2026-06-13",
        "netherlands-vs-japan-2026-06-14",
        "uruguay-vs-spain-2026-06-27",
        "colombia-vs-ghana-2026-07-03",
      ],
      notes: "Selected free-to-air FIFA World Cup 2026 matches in Colombia. Official Gol Caracol schedule confirms Colombia vs Ghana on 2026-07-03 via Caracol Televisión, GolCaracol.com, and Ditu.",
      commentaryLanguages: ["Spanish"],
    },
    {
      countryCode: "co",
      countryName: "Colombia",
      broadcaster: "Canal RCN",
      access: "Free",
      url: "https://www.canalrcn.com/",
      sourceName: "Deportes RCN official World Cup 2026 match list",
      sourceUrl:
        "https://www.deportesrcn.com/futbol/la-copa-del-mundo-por-rcn-los-35-partidos-que-se-transmitiran-por-futbol-rcn-152123",
      lastChecked: "2026-06-26",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [
        "germany-vs-cote-d-ivoire-2026-06-20",
        "scotland-vs-brazil-2026-06-24",
        "uruguay-vs-spain-2026-06-27",
        "colombia-vs-portugal-2026-06-27",
      ],
      notes:
        "Selected free-to-air FIFA World Cup 2026 matches in Colombia. Deportes RCN official match list confirms Uruguay vs Spain and Colombia vs Portugal in the 2026-06-26 / 2026-06-27 update window via Canal RCN.",
      commentaryLanguages: ["Spanish"],
    },
  ],

  ar: [
    {
      countryCode: "ar",
      countryName: "Argentina",
      broadcaster: "Telefe",
      access: "Free",
      url: "https://mitelefe.com/",
      sourceName: "Argentina FIFA World Cup 2026 broadcasting guide",
      sourceUrl:
        "https://www.livesoccertv.com/competitions/international/world-cup/watch/argentina/",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected free-to-air FIFA World Cup matches in Argentina",
      commentaryLanguages: ["Spanish"],
    },
    {
      countryCode: "ar",
      countryName: "Argentina",
      broadcaster: "TV Pública",
      access: "Free",
      url: "https://www.tvpublica.com.ar/",
      sourceName: "Argentina FIFA World Cup 2026 broadcasting guide",
      sourceUrl:
        "https://www.livesoccertv.com/competitions/international/world-cup/watch/argentina/",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected free-to-air FIFA World Cup matches in Argentina",
      commentaryLanguages: ["Spanish"],
    },
    {
      countryCode: "ar",
      countryName: "Argentina",
      broadcaster: "TyC Sports",
      access: "Paid",
      url: "https://www.tycsports.com/",
      sourceName: "TyC Sports official World Cup 2026 match list",
      sourceUrl:
        "https://www.tycsports.com/mundial/tyc-sports-partidos-copa-mundial-de-la-fifa-2026-op-id733555.html",
      lastChecked: "2026-07-02",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [
        "iraq-vs-norway-2026-06-16",
        "argentina-vs-algeria-2026-06-16",
        "austria-vs-jordan-2026-06-16",
        "argentina-vs-cabo-verde-2026-07-03",
      ],
      notes:
        "TyC Sports confirmed selected FIFA World Cup 2026 matches, including all Argentina matches. Confirmed for Argentina vs Cabo Verde on 2026-07-03 via TyC Sports and TyC Sports Play.",
      commentaryLanguages: ["Spanish"],
    },
    {
      countryCode: "ar",
      countryName: "Argentina",
      broadcaster: "DirecTV / DSports",
      access: "Paid",
      url: "https://www.directv.com.ar/",
      sourceName: "Argentina FIFA World Cup 2026 broadcasting guide",
      sourceUrl:
        "https://www.livesoccertv.com/competitions/international/world-cup/watch/argentina/",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage in Argentina",
      commentaryLanguages: ["Spanish"],
    },
  ],

  jp: [
    {
      countryCode: "jp",
      countryName: "Japan",
      broadcaster: "NHK",
      access: "Free",
      url: "https://www.nhk.jp/",
      sourceName: "Japan FIFA World Cup 2026 broadcasting guide",
      sourceUrl:
        "https://www.livesoccertv.com/competitions/international/world-cup/watch/japan/",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected free-to-air FIFA World Cup matches in Japan",
      commentaryLanguages: ["Japanese"],
    },
    {
      countryCode: "jp",
      countryName: "Japan",
      broadcaster: "Nippon TV",
      access: "Free",
      url: "https://www.ntv.co.jp/",
      sourceName: "Japan FIFA World Cup 2026 broadcasting guide",
      sourceUrl:
        "https://www.livesoccertv.com/competitions/international/world-cup/watch/japan/",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected free-to-air FIFA World Cup matches in Japan",
      commentaryLanguages: ["Japanese"],
    },
    {
      countryCode: "jp",
      countryName: "Japan",
      broadcaster: "Fuji TV",
      access: "Free",
      url: "https://www.fujitv.co.jp/",
      sourceName: "Japan FIFA World Cup 2026 broadcasting guide",
      sourceUrl:
        "https://www.livesoccertv.com/competitions/international/world-cup/watch/japan/",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected free-to-air FIFA World Cup matches in Japan",
      commentaryLanguages: ["Japanese"],
    },
    {
      countryCode: "jp",
      countryName: "Japan",
      broadcaster: "DAZN Japan",
      access: "Paid",
      url: "https://www.dazn.com/ja-JP/home",
      sourceName: "Japan FIFA World Cup 2026 broadcasting guide",
      sourceUrl:
        "https://www.livesoccertv.com/competitions/international/world-cup/watch/japan/",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage in Japan",
      commentaryLanguages: ["Japanese"],
    },
  ],

  kr: [
    {
      countryCode: "kr",
      countryName: "South Korea",
      broadcaster: "JTBC",
      access: "Free",
      url: "https://jtbc.co.kr/",
      sourceName: "FIFA World Cup 2026 Media Partners",
      sourceUrl: "https://inside.fifa.com/",
      lastChecked: "2026-06-11",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [],
      notes:
        "Official FIFA media partner for Korea Republic. Exact match allocation and access model to verify.",
      commentaryLanguages: ["Korean"],
    },
    {
      countryCode: "kr",
      countryName: "South Korea",
      broadcaster: "KBS",
      access: "Free",
      url: "https://program.kbs.co.kr/",
      sourceName: "FIFA World Cup 2026 Media Partners",
      sourceUrl: "https://inside.fifa.com/",
      lastChecked: "2026-06-11",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [],
      notes:
        "Official FIFA media partner for Korea Republic. Exact match allocation and access model to verify.",
      commentaryLanguages: ["Korean"],
    },
    {
      countryCode: "kr",
      countryName: "South Korea",
      broadcaster: "NAVER Corporation",
      access: "Free",
      url: "https://sports.news.naver.com/",
      sourceName: "FIFA World Cup 2026 Media Partners",
      sourceUrl: "https://inside.fifa.com/",
      lastChecked: "2026-06-11",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [],
      notes:
        "Official FIFA digital media partner for Korea Republic. Exact access model to verify.",
      commentaryLanguages: ["Korean"],
    },
  ],

  cz: [
    {
      countryCode: "cz",
      countryName: "Czechia",
      broadcaster: "Ceská Televize",
      access: "Free",
      url: "https://www.ceskatelevize.cz/",
      sourceName: "FIFA World Cup 2026 Media Partners",
      sourceUrl: "https://inside.fifa.com/",
      lastChecked: "2026-06-11",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [],
      notes:
        "Official FIFA media partner for Czechia. Exact match allocation and access model to verify.",
      commentaryLanguages: ["Czech"],
    },
    {
      countryCode: "cz",
      countryName: "Czechia",
      broadcaster: "TV Nova",
      access: "Free",
      url: "https://tv.nova.cz/",
      sourceName: "FIFA World Cup 2026 Media Partners",
      sourceUrl: "https://inside.fifa.com/",
      lastChecked: "2026-06-11",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [],
      notes:
        "Official FIFA media partner for Czechia. Exact match allocation and access model to verify.",
      commentaryLanguages: ["Czech"],
    },
  ],

  ba: [
    {
      countryCode: "ba",
      countryName: "Bosnia and Herzegovina",
      broadcaster: "Arena Channels Group",
      access: "Paid",
      url: "https://www.tvarenasport.com/",
      sourceName: "FIFA World Cup 2026 Media Partners",
      sourceUrl: "https://inside.fifa.com/",
      lastChecked: "2026-06-11",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "confirmed",
      matchSlugs: [],
      notes:
        "Official FIFA media partner for Bosnia and Herzegovina. Access model to verify before marking as free.",
      commentaryLanguages: ["Bosnian", "Serbian", "Croatian"],
    },
  ],
};

export const priorityCountryCodes = [
  "gb",
  "ie",
  "au",
  "ch",
  "at",
  "be",
  "bg",
  "fr",
  "ca",
  "us",
  "de",
  "it",
  "es",
  "nl",
  "pt",
  "tr",
  "mx",
  "br",
  "cl",
  "co",
  "ar",
  "jp",
  "kr",
  "cz",
  "ba",
  "za",
  "in",
] as const;

export function getAllBroadcasts(): BroadcastInfo[] {
  return Object.values(broadcastsByCountry).flat();
}