import type { BroadcastInfo } from "./matches";

export const broadcastsByCountry: Record<string, BroadcastInfo[]> = {
  gb: [
    {
      countryCode: "gb",
      countryName: "United Kingdom",
      broadcaster: "BBC / ITV",
      access: "Free",
      url: "https://www.bbc.co.uk/iplayer",
      sourceName: "BBC / ITV official broadcast rights",
      sourceUrl: "https://www.bbc.co.uk/sport/football",
      lastChecked: "2026-04-05",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Free full tournament coverage in the UK",
      commentaryLanguages: ["English"],
    },
  ],

  au: [
    {
      countryCode: "au",
      countryName: "Australia",
      broadcaster: "SBS",
      access: "Free",
      url: "https://www.sbs.com.au/ondemand/fifa-world-cup-2026",
      sourceName: "SBS official World Cup coverage",
      sourceUrl: "https://www.sbs.com.au/ondemand/fifa-world-cup-2026",
      lastChecked: "2026-04-07",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Free full tournament coverage in Australia",
      commentaryLanguages: ["English"],
    },
  ],

  ch: [
    {
      countryCode: "ch",
      countryName: "Switzerland",
      broadcaster: "SRF",
      access: "Free",
      url: "https://www.srf.ch/play/tv",
      sourceName: "SRF / RTS official broadcast rights",
      sourceUrl: "https://www.rts.ch/sport/football/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Free coverage for German-speaking Switzerland",
      commentaryLanguages: ["German"],
    },
    {
      countryCode: "ch",
      countryName: "Switzerland",
      broadcaster: "RTS",
      access: "Free",
      url: "https://www.rts.ch/play/tv",
      sourceName: "SRF / RTS official broadcast rights",
      sourceUrl: "https://www.rts.ch/sport/football/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Free coverage for French-speaking Switzerland",
      commentaryLanguages: ["French"],
    },
  ],

  be: [
    {
      countryCode: "be",
      countryName: "Belgium",
      broadcaster: "RTBF",
      access: "Free",
      url: "https://www.rtbf.be/auvio/",
      sourceName: "RTBF official broadcast rights",
      sourceUrl: "https://www.rtbf.be/sport/football/",
      lastChecked: "2026-04-07",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Free full tournament coverage in Belgium",
      commentaryLanguages: ["French"],
    },
    {
      countryCode: "be",
      countryName: "Belgium",
      broadcaster: "VRT",
      access: "Free",
      url: "https://www.vrt.be/vrtmax/",
      sourceName: "VRT official broadcast rights",
      sourceUrl: "https://www.vrt.be/vrtmax/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Free full tournament coverage in Belgium",
      commentaryLanguages: ["Dutch"],
    },
  ],

  fr: [
    {
      countryCode: "fr",
      countryName: "France",
      broadcaster: "M6",
      access: "Free",
      url: "https://www.m6.fr/",
      sourceName: "M6 official FIFA World Cup 2026 rights",
      sourceUrl:
        "https://inside.fifa.com/news/groupe-m6-awarded-free-to-air-media-rights-for-the-fifa-world-cup-26-tm-and",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected free-to-air FIFA World Cup 2026 matches in France",
      commentaryLanguages: ["French"],
    },
    {
      countryCode: "fr",
      countryName: "France",
      broadcaster: "beIN SPORTS",
      access: "Paid",
      url: "https://www.beinsports.com/fr-fr/football/coupe-du-monde-de-la-fifa-2026",
      affiliateUrl: undefined,
      sourceName: "beIN SPORTS France World Cup 2026 page",
      sourceUrl:
        "https://www.beinsports.com/fr-fr/football/coupe-du-monde-de-la-fifa-2026",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage in France",
      commentaryLanguages: ["French"],
    },
  ],

  ca: [
    {
      countryCode: "ca",
      countryName: "Canada",
      broadcaster: "TSN",
      access: "Paid",
      url: "https://www.tsn.ca/",
      sourceName: "Bell Media FIFA World Cup 26 announcement",
      sourceUrl:
        "https://www.bellmedia.ca/the-lede/press/fifa-world-cup-26-is-one-year-away-and-tsn-counts-down-to-the-tournament-with-preview-specials-all-new-podcasts-and-more/",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Main English-language FIFA World Cup coverage in Canada",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "ca",
      countryName: "Canada",
      broadcaster: "CTV",
      access: "Free",
      url: "https://www.ctv.ca/",
      sourceName: "Bell Media FIFA World Cup 26 announcement",
      sourceUrl:
        "https://www.bellmedia.ca/the-lede/press/fifa-world-cup-26-is-one-year-away-and-tsn-counts-down-to-the-tournament-with-preview-specials-all-new-podcasts-and-more/",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected free-to-air FIFA World Cup coverage in Canada",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "ca",
      countryName: "Canada",
      broadcaster: "RDS",
      access: "Paid",
      url: "https://www.rds.ca/",
      sourceName: "Bell Media FIFA World Cup 26 announcement",
      sourceUrl:
        "https://www.bellmedia.ca/fr/ventes-publicitaires/ressources/nouvelles/opportunites-publicitaires-pour-la-coupe-du-monde-fifa-2026/",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "French-language FIFA World Cup coverage in Canada",
      commentaryLanguages: ["French"],
    },
  ],

  us: [
    {
      countryCode: "us",
      countryName: "United States",
      broadcaster: "FOX",
      access: "Free",
      url: "https://www.foxsports.com/soccer/fifa-world-cup-men",
      sourceName: "FOX Sports FIFA World Cup coverage",
      sourceUrl: "https://www.foxsports.com/",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected English-language free over-the-air matches in the United States",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "us",
      countryName: "United States",
      broadcaster: "FS1",
      access: "Paid",
      url: "https://www.foxsports.com/live/fs1",
      sourceName: "FOX Sports FIFA World Cup coverage",
      sourceUrl: "https://www.foxsports.com/",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "English-language FIFA World Cup coverage in the United States",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "us",
      countryName: "United States",
      broadcaster: "Telemundo",
      access: "Free",
      url: "https://www.telemundo.com/deportes",
      sourceName: "NBCUniversal Telemundo World Cup coverage",
      sourceUrl:
        "https://www.nbcuniversal.com/article/telemundo-unveils-most-extensive-spanish-language-fifa-world-cuptm-presentation-broadcast-television",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Main Spanish-language free-to-air FIFA World Cup coverage",
      commentaryLanguages: ["Spanish"],
    },
    {
      countryCode: "us",
      countryName: "United States",
      broadcaster: "Universo",
      access: "Paid",
      url: "https://www.telemundo.com/universo",
      sourceName: "NBCUniversal Universo coverage",
      sourceUrl:
        "https://www.nbcuniversal.com/article/telemundo-unveils-most-extensive-spanish-language-fifa-world-cuptm-presentation-broadcast-television",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Spanish-language cable coverage in the United States",
      commentaryLanguages: ["Spanish"],
    },
    {
      countryCode: "us",
      countryName: "United States",
      broadcaster: "Peacock",
      access: "Paid",
      url: "https://www.peacocktv.com/",
      sourceName: "NBCUniversal Peacock World Cup streaming",
      sourceUrl:
        "https://www.nbcuniversal.com/article/telemundo-unveils-most-extensive-spanish-language-fifa-world-cuptm-presentation-broadcast-television",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Spanish-language streaming coverage in the United States",
      commentaryLanguages: ["Spanish"],
    },
  ],

  es: [
    {
      countryCode: "es",
      countryName: "Spain",
      broadcaster: "RTVE",
      access: "Free",
      url: "https://www.rtve.es/play/",
      sourceName: "RTVE official coverage",
      sourceUrl: "https://www.rtve.es/deportes/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free-to-air matches including selected key fixtures",
      commentaryLanguages: ["Spanish"],
    },
    {
      countryCode: "es",
      countryName: "Spain",
      broadcaster: "Movistar+",
      access: "Paid",
      url: "https://www.movistarplus.es/",
      sourceName: "Movistar+ football coverage",
      sourceUrl: "https://www.movistarplus.es/deportes/futbol",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Full tournament coverage via subscription",
      commentaryLanguages: ["Spanish"],
    },
  ],

  pt: [
    {
      countryCode: "pt",
      countryName: "Portugal",
      broadcaster: "Sport TV",
      access: "Paid",
      url: "https://www.sporttv.pt/",
      sourceName: "Sport TV FIFA World Cup 2026 rights",
      sourceUrl:
        "https://www.broadbandtvnews.com/2025/12/05/sport-tv-to-air-all-104-fifa-world-cup-2026-matches-in-portugal/",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage in Portugal",
      commentaryLanguages: ["Portuguese"],
    },
  ],

  se: [
    {
      countryCode: "se",
      countryName: "Sweden",
      broadcaster: "SVT",
      access: "Free",
      url: "https://www.svtplay.se/",
      sourceName: "SVT World Cup coverage",
      sourceUrl: "https://www.svt.se/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Shared rights, broadcasts many matches",
      commentaryLanguages: ["Swedish"],
    },
    {
      countryCode: "se",
      countryName: "Sweden",
      broadcaster: "TV4",
      access: "Free",
      url: "https://www.tv4play.se/",
      sourceName: "TV4 sports rights",
      sourceUrl: "https://www.tv4.se/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Co-broadcast with SVT",
      commentaryLanguages: ["Swedish"],
    },
  ],

  no: [
    {
      countryCode: "no",
      countryName: "Norway",
      broadcaster: "NRK",
      access: "Free",
      url: "https://tv.nrk.no/",
      sourceName: "NRK sports rights",
      sourceUrl: "https://www.nrk.no/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free matches including major fixtures",
      commentaryLanguages: ["Norwegian"],
    },
    {
      countryCode: "no",
      countryName: "Norway",
      broadcaster: "TV2",
      access: "Paid",
      url: "https://www.tv2.no/play/",
      sourceName: "TV2 premium sports",
      sourceUrl: "https://www.tv2.no/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Full coverage via subscription",
      commentaryLanguages: ["Norwegian"],
    },
  ],

  dk: [
    {
      countryCode: "dk",
      countryName: "Denmark",
      broadcaster: "DR",
      access: "Free",
      url: "https://www.dr.dk/drtv/",
      sourceName: "DR World Cup coverage",
      sourceUrl: "https://www.dr.dk/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Shared free coverage",
      commentaryLanguages: ["Danish"],
    },
    {
      countryCode: "dk",
      countryName: "Denmark",
      broadcaster: "TV2",
      access: "Free",
      url: "https://play.tv2.dk/",
      sourceName: "TV2 Denmark sports rights",
      sourceUrl: "https://www.tv2.dk/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Co-broadcast with DR",
      commentaryLanguages: ["Danish"],
    },
  ],

  fi: [
    {
      countryCode: "fi",
      countryName: "Finland",
      broadcaster: "YLE",
      access: "Free",
      url: "https://areena.yle.fi/",
      sourceName: "YLE sports rights",
      sourceUrl: "https://yle.fi/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Full or near full tournament coverage",
      commentaryLanguages: ["Finnish"],
    },
  ],

  is: [
    {
      countryCode: "is",
      countryName: "Iceland",
      broadcaster: "RUV",
      access: "Free",
      url: "https://www.ruv.is/sjonvarp",
      sourceName: "RUV World Cup coverage",
      sourceUrl: "https://www.ruv.is/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Full tournament coverage",
      commentaryLanguages: ["Icelandic"],
    },
  ],

  nl: [
    {
      countryCode: "nl",
      countryName: "Netherlands",
      broadcaster: "NOS",
      access: "Free",
      url: "https://nos.nl/sport",
      sourceName: "NOS FIFA World Cup rights",
      sourceUrl:
        "https://www.insideworldfootball.com/2024/09/16/nos-keeps-hold-world-cup-rights-2026-2030/",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Free FIFA World Cup coverage in the Netherlands",
      commentaryLanguages: ["Dutch"],
    },
  ],

  in: [
    {
      countryCode: "in",
      countryName: "India",
      broadcaster: "DD Sports",
      access: "Free",
      url: "https://prasarbharati.gov.in/",
      sourceName: "Prasar Bharati sports rights",
      sourceUrl: "https://prasarbharati.gov.in/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected matches on free TV",
      commentaryLanguages: ["Hindi", "English"],
    },
    {
      countryCode: "in",
      countryName: "India",
      broadcaster: "JioCinema",
      access: "Free",
      url: "https://www.jiocinema.com/",
      sourceName: "JioCinema FIFA coverage",
      sourceUrl: "https://www.jiocinema.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Full tournament streaming free in India",
      commentaryLanguages: ["Hindi", "English", "Regional"],
    },
  ],

  cn: [
    {
      countryCode: "cn",
      countryName: "China",
      broadcaster: "CCTV",
      access: "Free",
      url: "https://tv.cctv.com/",
      sourceName: "CCTV sports rights",
      sourceUrl: "https://tv.cctv.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Official broadcaster with wide free coverage",
      commentaryLanguages: ["Chinese"],
    },
    {
      countryCode: "cn",
      countryName: "China",
      broadcaster: "Migu",
      access: "Paid",
      url: "https://www.miguvideo.com/",
      sourceName: "Migu sports streaming",
      sourceUrl: "https://www.miguvideo.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Premium streaming platform",
      commentaryLanguages: ["Chinese"],
    },
  ],

  ma: [
    {
      countryCode: "ma",
      countryName: "Morocco",
      broadcaster: "SNRT",
      access: "Free",
      url: "https://snrt.ma/",
      sourceName: "SNRT sports coverage",
      sourceUrl: "https://snrt.ma/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["Arabic", "French"],
    },
    {
      countryCode: "ma",
      countryName: "Morocco",
      broadcaster: "beIN Sports",
      access: "Paid",
      url: "https://www.beinsports.com/",
      sourceName: "beIN Sports MENA coverage",
      sourceUrl: "https://www.beinsports.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage",
      commentaryLanguages: ["Arabic"],
    },
  ],

  dz: [
    {
      countryCode: "dz",
      countryName: "Algeria",
      broadcaster: "ENTV",
      access: "Free",
      url: "https://www.entv.dz/",
      sourceName: "ENTV sports coverage",
      sourceUrl: "https://www.entv.dz/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["Arabic"],
    },
    {
      countryCode: "dz",
      countryName: "Algeria",
      broadcaster: "beIN Sports",
      access: "Paid",
      url: "https://www.beinsports.com/",
      sourceName: "beIN Sports MENA coverage",
      sourceUrl: "https://www.beinsports.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage",
      commentaryLanguages: ["Arabic"],
    },
  ],

  tn: [
    {
      countryCode: "tn",
      countryName: "Tunisia",
      broadcaster: "Wataniya",
      access: "Free",
      url: "https://www.watania1.tn/",
      sourceName: "Wataniya sports coverage",
      sourceUrl: "https://www.watania1.tn/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["Arabic"],
    },
    {
      countryCode: "tn",
      countryName: "Tunisia",
      broadcaster: "beIN Sports",
      access: "Paid",
      url: "https://www.beinsports.com/",
      sourceName: "beIN Sports MENA coverage",
      sourceUrl: "https://www.beinsports.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage",
      commentaryLanguages: ["Arabic"],
    },
  ],

  eg: [
    {
      countryCode: "eg",
      countryName: "Egypt",
      broadcaster: "ON Time Sports",
      access: "Free",
      url: "https://www.youtube.com/@ONTimeSports",
      sourceName: "ON Time Sports coverage",
      sourceUrl: "https://www.ontime.live/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected free coverage",
      commentaryLanguages: ["Arabic"],
    },
    {
      countryCode: "eg",
      countryName: "Egypt",
      broadcaster: "beIN Sports",
      access: "Paid",
      url: "https://www.beinsports.com/",
      sourceName: "beIN Sports MENA coverage",
      sourceUrl: "https://www.beinsports.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage",
      commentaryLanguages: ["Arabic"],
    },
  ],

  sn: [
    {
      countryCode: "sn",
      countryName: "Senegal",
      broadcaster: "RTS",
      access: "Free",
      url: "https://www.rts.sn/",
      sourceName: "RTS Senegal sports coverage",
      sourceUrl: "https://www.rts.sn/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["French"],
    },
    {
      countryCode: "sn",
      countryName: "Senegal",
      broadcaster: "beIN Sports",
      access: "Paid",
      url: "https://www.beinsports.com/",
      sourceName: "beIN Sports MENA coverage",
      sourceUrl: "https://www.beinsports.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage",
      commentaryLanguages: ["Arabic"],
    },
  ],

  ci: [
    {
      countryCode: "ci",
      countryName: "Ivory Coast",
      broadcaster: "RTI",
      access: "Free",
      url: "https://www.rti.ci/",
      sourceName: "RTI sports coverage",
      sourceUrl: "https://www.rti.ci/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["French"],
    },
    {
      countryCode: "ci",
      countryName: "Ivory Coast",
      broadcaster: "beIN Sports",
      access: "Paid",
      url: "https://www.beinsports.com/",
      sourceName: "beIN Sports MENA coverage",
      sourceUrl: "https://www.beinsports.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage",
      commentaryLanguages: ["Arabic"],
    },
  ],

  ng: [
    {
      countryCode: "ng",
      countryName: "Nigeria",
      broadcaster: "NTA",
      access: "Free",
      url: "https://nta.ng/",
      sourceName: "NTA sports coverage",
      sourceUrl: "https://nta.ng/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "ng",
      countryName: "Nigeria",
      broadcaster: "SuperSport",
      access: "Paid",
      url: "https://www.supersport.com/",
      sourceName: "SuperSport coverage",
      sourceUrl: "https://www.supersport.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full coverage",
      commentaryLanguages: ["English"],
    },
  ],

  gh: [
    {
      countryCode: "gh",
      countryName: "Ghana",
      broadcaster: "GTV",
      access: "Free",
      url: "https://www.gbcghanaonline.com/gtv/",
      sourceName: "GTV sports coverage",
      sourceUrl: "https://www.gbcghanaonline.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "gh",
      countryName: "Ghana",
      broadcaster: "SuperSport",
      access: "Paid",
      url: "https://www.supersport.com/",
      sourceName: "SuperSport coverage",
      sourceUrl: "https://www.supersport.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full coverage",
      commentaryLanguages: ["English"],
    },
  ],

  za: [
    {
      countryCode: "za",
      countryName: "South Africa",
      broadcaster: "SABC",
      access: "Free",
      url: "https://www.sabcplus.com/",
      sourceName: "SABC sports coverage",
      sourceUrl: "https://www.sabc.co.za/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected free coverage",
      commentaryLanguages: ["English"],
    },
    {
      countryCode: "za",
      countryName: "South Africa",
      broadcaster: "SuperSport",
      access: "Paid",
      url: "https://www.supersport.com/",
      sourceName: "SuperSport coverage",
      sourceUrl: "https://www.supersport.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full coverage",
      commentaryLanguages: ["English"],
    },
  ],

  cm: [
    {
      countryCode: "cm",
      countryName: "Cameroon",
      broadcaster: "CRTV",
      access: "Free",
      url: "https://www.crtv.cm/",
      sourceName: "CRTV sports coverage",
      sourceUrl: "https://www.crtv.cm/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["French"],
    },
    {
      countryCode: "cm",
      countryName: "Cameroon",
      broadcaster: "SuperSport",
      access: "Paid",
      url: "https://www.supersport.com/",
      sourceName: "SuperSport coverage",
      sourceUrl: "https://www.supersport.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full coverage",
      commentaryLanguages: ["English"],
    },
  ],

  cd: [
    {
      countryCode: "cd",
      countryName: "DR Congo",
      broadcaster: "RTNC",
      access: "Free",
      url: "https://www.rtnc.cd/",
      sourceName: "RTNC sports coverage",
      sourceUrl: "https://www.rtnc.cd/",
      lastChecked: "2026-04-13",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free national coverage for selected matches",
      commentaryLanguages: ["French"],
    },
    {
      countryCode: "cd",
      countryName: "DR Congo",
      broadcaster: "SuperSport",
      access: "Paid",
      url: "https://www.supersport.com/",
      sourceName: "SuperSport coverage",
      sourceUrl: "https://www.supersport.com/",
      lastChecked: "2026-04-13",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full coverage",
      commentaryLanguages: ["English"],
    },
  ],

  de: [
    {
      countryCode: "de",
      countryName: "Germany",
      broadcaster: "ARD",
      access: "Free",
      url: "https://www.ardmediathek.de/",
      sourceName: "ARD and ZDF FIFA World Cup 2026 sublicensing agreement",
      sourceUrl:
        "https://presseportal.zdf.de/pressemitteilung/ard-und-zdf-uebertragen-60-spiele-der-fifa-fussball-wm-2026",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected free-to-air matches in Germany",
      commentaryLanguages: ["German"],
    },
    {
      countryCode: "de",
      countryName: "Germany",
      broadcaster: "ZDF",
      access: "Free",
      url: "https://www.zdf.de/sport",
      sourceName: "ARD and ZDF FIFA World Cup 2026 sublicensing agreement",
      sourceUrl:
        "https://presseportal.zdf.de/pressemitteilung/ard-und-zdf-uebertragen-60-spiele-der-fifa-fussball-wm-2026",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected free-to-air matches in Germany",
      commentaryLanguages: ["German"],
    },
    {
      countryCode: "de",
      countryName: "Germany",
      broadcaster: "MagentaTV",
      access: "Paid",
      url: "https://www.magentatv.de/",
      sourceName: "MagentaTV FIFA World Cup 2026 rights",
      sourceUrl:
        "https://www.heise.de/en/news/ARD-and-ZDF-to-broadcast-60-matches-of-the-2026-World-Cup-10730703.html",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage in Germany",
      commentaryLanguages: ["German"],
    },
  ],

  it: [
    {
      countryCode: "it",
      countryName: "Italy",
      broadcaster: "RAI",
      access: "Free",
      url: "https://www.raiplay.it/",
      sourceName: "RAI FIFA World Cup 2026 rights",
      sourceUrl:
        "https://www.insideworldfootball.com/2026/03/02/rai-agree-free-air-package-2026-world-cup-italy-still-qualify/",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free-to-air package of selected FIFA World Cup 2026 matches in Italy",
      commentaryLanguages: ["Italian"],
    },
  ],

  mx: [
    {
      countryCode: "mx",
      countryName: "Mexico",
      broadcaster: "Televisa",
      access: "Free",
      url: "https://www.televisa.com/",
      sourceName: "Televisa FIFA World Cup 2026 coverage",
      sourceUrl:
        "https://elpais.com/mexico/2026-03-28/mexico-portugal-cierres-viales-horario-y-donde-ver-el-partido-de-reinauguracion-del-estadio-azteca.html",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free-to-air FIFA World Cup coverage in Mexico",
      commentaryLanguages: ["Spanish"],
    },
    {
      countryCode: "mx",
      countryName: "Mexico",
      broadcaster: "TV Azteca",
      access: "Free",
      url: "https://www.tvazteca.com/",
      sourceName: "TV Azteca FIFA World Cup 2026 announcement",
      sourceUrl:
        "https://www.mediotiempo.com/futbol/copa-mundial/tv-azteca-transmitira-mundial-2026-revelan-juegos-invitados-especiales",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free-to-air FIFA World Cup coverage in Mexico",
      commentaryLanguages: ["Spanish"],
    },
    {
      countryCode: "mx",
      countryName: "Mexico",
      broadcaster: "TUDN",
      access: "Paid",
      url: "https://www.tudn.com/",
      sourceName: "TUDN football coverage",
      sourceUrl: "https://www.tudn.com/",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid FIFA World Cup coverage in Mexico",
      commentaryLanguages: ["Spanish"],
    },
  ],

  br: [
    {
      countryCode: "br",
      countryName: "Brazil",
      broadcaster: "Globo",
      access: "Free",
      url: "https://globoplay.globo.com/",
      sourceName: "Brazil FIFA World Cup 2026 broadcasting guide",
      sourceUrl:
        "https://www.lance.com.br/lancepedia/transmissao-tv-copa-do-mundo-2026.html",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Free-to-air FIFA World Cup coverage in Brazil",
      commentaryLanguages: ["Portuguese"],
    },
    {
      countryCode: "br",
      countryName: "Brazil",
      broadcaster: "SporTV",
      access: "Paid",
      url: "https://sportv.globo.com/",
      sourceName: "Brazil FIFA World Cup 2026 broadcasting guide",
      sourceUrl:
        "https://www.lance.com.br/lancepedia/transmissao-tv-copa-do-mundo-2026.html",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid FIFA World Cup coverage in Brazil",
      commentaryLanguages: ["Portuguese"],
    },
    {
      countryCode: "br",
      countryName: "Brazil",
      broadcaster: "SBT",
      access: "Free",
      url: "https://www.sbt.com.br/",
      sourceName: "Brazil FIFA World Cup 2026 broadcasting guide",
      sourceUrl:
        "https://www.lance.com.br/lancepedia/transmissao-tv-copa-do-mundo-2026.html",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected free-to-air FIFA World Cup matches in Brazil",
      commentaryLanguages: ["Portuguese"],
    },
  ],

  ar: [
    {
      countryCode: "ar",
      countryName: "Argentina",
      broadcaster: "Telefe",
      access: "Free",
      url: "https://mitelefe.com/",
      sourceName: "Argentina FIFA World Cup 2026 broadcasting guide",
      sourceUrl:
        "https://www.livesoccertv.com/competitions/international/world-cup/watch/argentina/",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected free-to-air FIFA World Cup matches in Argentina",
      commentaryLanguages: ["Spanish"],
    },
    {
      countryCode: "ar",
      countryName: "Argentina",
      broadcaster: "TV Pública",
      access: "Free",
      url: "https://www.tvpublica.com.ar/",
      sourceName: "Argentina FIFA World Cup 2026 broadcasting guide",
      sourceUrl:
        "https://www.livesoccertv.com/competitions/international/world-cup/watch/argentina/",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected free-to-air FIFA World Cup matches in Argentina",
      commentaryLanguages: ["Spanish"],
    },
    {
      countryCode: "ar",
      countryName: "Argentina",
      broadcaster: "TyC Sports",
      access: "Paid",
      url: "https://www.tycsports.com/",
      sourceName: "Argentina FIFA World Cup 2026 broadcasting guide",
      sourceUrl:
        "https://www.livesoccertv.com/competitions/international/world-cup/watch/argentina/",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Paid FIFA World Cup coverage in Argentina",
      commentaryLanguages: ["Spanish"],
    },
    {
      countryCode: "ar",
      countryName: "Argentina",
      broadcaster: "DirecTV / DSports",
      access: "Paid",
      url: "https://www.directv.com.ar/",
      sourceName: "Argentina FIFA World Cup 2026 broadcasting guide",
      sourceUrl:
        "https://www.livesoccertv.com/competitions/international/world-cup/watch/argentina/",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage in Argentina",
      commentaryLanguages: ["Spanish"],
    },
  ],

  jp: [
    {
      countryCode: "jp",
      countryName: "Japan",
      broadcaster: "NHK",
      access: "Free",
      url: "https://www.nhk.jp/",
      sourceName: "Japan FIFA World Cup 2026 broadcasting guide",
      sourceUrl:
        "https://www.livesoccertv.com/competitions/international/world-cup/watch/japan/",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected free-to-air FIFA World Cup matches in Japan",
      commentaryLanguages: ["Japanese"],
    },
    {
      countryCode: "jp",
      countryName: "Japan",
      broadcaster: "Nippon TV",
      access: "Free",
      url: "https://www.ntv.co.jp/",
      sourceName: "Japan FIFA World Cup 2026 broadcasting guide",
      sourceUrl:
        "https://www.livesoccertv.com/competitions/international/world-cup/watch/japan/",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected free-to-air FIFA World Cup matches in Japan",
      commentaryLanguages: ["Japanese"],
    },
    {
      countryCode: "jp",
      countryName: "Japan",
      broadcaster: "Fuji TV",
      access: "Free",
      url: "https://www.fujitv.co.jp/",
      sourceName: "Japan FIFA World Cup 2026 broadcasting guide",
      sourceUrl:
        "https://www.livesoccertv.com/competitions/international/world-cup/watch/japan/",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "Selected free-to-air FIFA World Cup matches in Japan",
      commentaryLanguages: ["Japanese"],
    },
    {
      countryCode: "jp",
      countryName: "Japan",
      broadcaster: "DAZN Japan",
      access: "Paid",
      url: "https://www.dazn.com/ja-JP/home",
      sourceName: "Japan FIFA World Cup 2026 broadcasting guide",
      sourceUrl:
        "https://www.livesoccertv.com/competitions/international/world-cup/watch/japan/",
      lastChecked: "2026-05-15",
      hasFullCoverage: true,
      coverageType: "full",
      coverageStatus: "confirmed",
      notes: "Paid full tournament coverage in Japan",
      commentaryLanguages: ["Japanese"],
    },
  ],

  kr: [
    {
      countryCode: "kr",
      countryName: "South Korea",
      broadcaster: "JTBC",
      access: "Free",
      url: "https://jtbc.co.kr/",
      sourceName: "JTBC and KBS FIFA World Cup 2026 broadcast agreement",
      sourceUrl:
        "https://koreajoongangdaily.joins.com/news/2026-04-20/sports/football/JTBC-KBS-finalize-deal-to-jointly-broadcast-FIFA-World-Cup-2026-in-Korea/2573475",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "FIFA World Cup coverage in South Korea",
      commentaryLanguages: ["Korean"],
    },
    {
      countryCode: "kr",
      countryName: "South Korea",
      broadcaster: "KBS",
      access: "Free",
      url: "https://program.kbs.co.kr/",
      sourceName: "JTBC and KBS FIFA World Cup 2026 broadcast agreement",
      sourceUrl:
        "https://koreajoongangdaily.joins.com/news/2026-04-20/sports/football/JTBC-KBS-finalize-deal-to-jointly-broadcast-FIFA-World-Cup-2026-in-Korea/2573475",
      lastChecked: "2026-05-15",
      hasFullCoverage: false,
      coverageType: "partial",
      coverageStatus: "to_update",
      matchSlugs: [],
      notes: "FIFA World Cup coverage in South Korea",
      commentaryLanguages: ["Korean"],
    },
  ],
};

export const priorityCountryCodes = [
  "gb",
  "au",
  "ch",
  "be",
  "fr",
  "ca",
  "us",
  "de",
  "it",
  "es",
  "nl",
  "pt",
  "mx",
  "br",
  "ar",
  "jp",
  "kr",
] as const;

export function getAllBroadcasts(): BroadcastInfo[] {
  return Object.values(broadcastsByCountry).flat();
}