import type { EventData } from "@/lib/events";

export type CompetitionCategory = "continental"|"domestic-league"|"domestic-cup"|"international"|"grand-slam"|"tour"|"league"|"championship"|"organization"|"other";
export type CompetitionCatalogEntry = {sport:string;slug:string;displayName:string;category:CompetitionCategory;region?:string;countryCode?:string;featuredRank?:number;aliases?:string[]};

const CATALOG: CompetitionCatalogEntry[] = [
{sport:"football",slug:"champions-league",displayName:"UEFA Champions League",category:"continental",region:"Europe",featuredRank:1,aliases:["Champions League","UCL","C1","Ligue des champions"]},{sport:"football",slug:"europa-league",displayName:"UEFA Europa League",category:"continental",region:"Europe",featuredRank:2,aliases:["Europa League","UEL","C3"]},{sport:"football",slug:"conference-league",displayName:"UEFA Conference League",category:"continental",region:"Europe",featuredRank:3,aliases:["Conference League","UECL"]},{sport:"football",slug:"premier-league",displayName:"Premier League",category:"domestic-league",countryCode:"GB",featuredRank:10,aliases:["EPL","English Premier League"]},{sport:"football",slug:"ligue-1",displayName:"Ligue 1 McDonald's",category:"domestic-league",countryCode:"FR",featuredRank:11,aliases:["Ligue 1","L1"]},{sport:"football",slug:"laliga",displayName:"LALIGA EA SPORTS",category:"domestic-league",countryCode:"ES",featuredRank:12,aliases:["LaLiga","Liga","Spanish league"]},{sport:"football",slug:"bundesliga",displayName:"Bundesliga",category:"domestic-league",countryCode:"DE",featuredRank:13},{sport:"football",slug:"serie-a",displayName:"Serie A",category:"domestic-league",countryCode:"IT",featuredRank:14},{sport:"football",slug:"mls",displayName:"Major League Soccer",category:"domestic-league",region:"North America",featuredRank:15,aliases:["MLS"]},{sport:"football",slug:"fa-cup",displayName:"FA Cup",category:"domestic-cup",countryCode:"GB"},{sport:"football",slug:"coupe-de-france",displayName:"Coupe de France",category:"domestic-cup",countryCode:"FR"},{sport:"football",slug:"copa-del-rey",displayName:"Copa del Rey",category:"domestic-cup",countryCode:"ES"},{sport:"football",slug:"world-cup",displayName:"FIFA World Cup",category:"international",featuredRank:20,aliases:["World Cup","Coupe du monde","FIFA WC"]},{sport:"football",slug:"euro",displayName:"UEFA European Championship",category:"international",aliases:["Euro","UEFA Euro"]},{sport:"football",slug:"copa-america",displayName:"Copa América",category:"international"},
{sport:"basketball",slug:"nba",displayName:"NBA",category:"league",region:"North America",featuredRank:1,aliases:["National Basketball Association"]},{sport:"basketball",slug:"euroleague",displayName:"EuroLeague",category:"league",region:"Europe",featuredRank:2,aliases:["Euro League"]},{sport:"basketball",slug:"wnba",displayName:"WNBA",category:"league",region:"North America",featuredRank:3},{sport:"basketball",slug:"ncaa",displayName:"NCAA Basketball",category:"league",countryCode:"US",featuredRank:4,aliases:["College basketball"]},
{sport:"hockey",slug:"nhl",displayName:"NHL",category:"league",region:"North America",featuredRank:1,aliases:["National Hockey League","LNH"]},{sport:"hockey",slug:"iihf-world-championship",displayName:"IIHF World Championship",category:"international",featuredRank:2,aliases:["World Hockey Championship","Mondial hockey"]},
{sport:"tennis",slug:"australian-open",displayName:"Australian Open",category:"grand-slam",featuredRank:1,aliases:["AO"]},{sport:"tennis",slug:"roland-garros",displayName:"Roland-Garros",category:"grand-slam",featuredRank:2,aliases:["French Open","RG"]},{sport:"tennis",slug:"wimbledon",displayName:"Wimbledon",category:"grand-slam",featuredRank:3},{sport:"tennis",slug:"us-open",displayName:"US Open",category:"grand-slam",featuredRank:4},
{sport:"rugby",slug:"six-nations",displayName:"Six Nations",category:"international",featuredRank:1,aliases:["6 Nations"]},{sport:"rugby",slug:"top-14",displayName:"Top 14",category:"domestic-league",countryCode:"FR",featuredRank:2},{sport:"rugby",slug:"champions-cup",displayName:"Champions Cup",category:"continental",region:"Europe",featuredRank:3},{sport:"rugby",slug:"rugby-world-cup",displayName:"Rugby World Cup",category:"international",featuredRank:4,aliases:["RWC","Coupe du monde rugby"]},
{sport:"baseball",slug:"mlb",displayName:"MLB",category:"league",region:"North America",featuredRank:1,aliases:["Major League Baseball"]},{sport:"baseball",slug:"world-baseball-classic",displayName:"World Baseball Classic",category:"international",featuredRank:2,aliases:["WBC"]},{sport:"baseball",slug:"npb",displayName:"NPB",category:"league",countryCode:"JP",featuredRank:3},{sport:"baseball",slug:"kbo",displayName:"KBO League",category:"league",countryCode:"KR",featuredRank:4},
{sport:"american-football",slug:"nfl",displayName:"NFL",category:"league",countryCode:"US",featuredRank:1,aliases:["National Football League"]},{sport:"american-football",slug:"ncaa-football",displayName:"NCAA Football",category:"league",countryCode:"US",featuredRank:2,aliases:["College football"]},
{sport:"cycling",slug:"tour-de-france",displayName:"Tour de France",category:"tour",countryCode:"FR",featuredRank:1,aliases:["TDF"]},{sport:"cycling",slug:"giro-ditalia",displayName:"Giro d'Italia",category:"tour",countryCode:"IT",featuredRank:2,aliases:["Giro"]},{sport:"cycling",slug:"vuelta-a-espana",displayName:"Vuelta a España",category:"tour",countryCode:"ES",featuredRank:3,aliases:["Vuelta"]},
{sport:"ufc",slug:"ufc",displayName:"UFC",category:"organization",featuredRank:1,aliases:["Ultimate Fighting Championship","MMA UFC"]}
];

export const getCompetitionCatalogEntry=(sport:string,slug:string)=>CATALOG.find(e=>e.sport===sport&&e.slug===slug);
export const displayCompetitionName=(sport:string,slug:string,fallback:string)=>getCompetitionCatalogEntry(sport,slug)?.displayName??fallback;
export const classifyCompetition=(sport:string,slug:string):CompetitionCategory=>getCompetitionCatalogEntry(sport,slug)?.category??"other";
export const competitionCatalogForSport=(sport:string)=>CATALOG.filter(e=>e.sport===sport).sort((a,b)=>(a.featuredRank??999)-(b.featuredRank??999));
export const allCompetitionCatalogEntries=()=>[...CATALOG];

export function buildCompetitionGroups(events:EventData[],sport:string){const map=new Map<string,{slug:string;name:string;category:CompetitionCategory;eventCount:number;nextEventDate:string|null}>();const now=Date.now();for(const event of events.filter(e=>e.sport===sport)){const next=event.status!=="finished"&&Date.parse(event.eventDate)>=now?event.eventDate:null;const row=map.get(event.competitionSlug);if(!row){map.set(event.competitionSlug,{slug:event.competitionSlug,name:displayCompetitionName(sport,event.competitionSlug,event.competition),category:classifyCompetition(sport,event.competitionSlug),eventCount:1,nextEventDate:next});continue;}row.eventCount++;if(next&&(!row.nextEventDate||Date.parse(next)<Date.parse(row.nextEventDate)))row.nextEventDate=next;}return Array.from(map.values()).sort((a,b)=>(getCompetitionCatalogEntry(sport,a.slug)?.featuredRank??999)-(getCompetitionCatalogEntry(sport,b.slug)?.featuredRank??999)||a.name.localeCompare(b.name));}
