export function fifaCodeToIso2(code: string): string {
  const map: Record<string, string> = {
    ALG: "dz",
    ARG: "ar",
    AUS: "au",
    AUT: "at",
    BEL: "be",
    BIH: "ba",
    BRA: "br",
    CAN: "ca",
    CHL: "cl",
    COL: "co",
    CRO: "hr",
    CUW: "cw",
    CIV: "ci",
    CPV: "cv",
    CZE: "cz",
    ECU: "ec",
    EGY: "eg",
    ENG: "gb",
    ESP: "es",
    FRA: "fr",
    GER: "de",
    GHA: "gh",
    HAI: "ht",
    IRN: "ir",
    IRQ: "iq",
    ITA: "it",
    JOR: "jo",
    JPN: "jp",
    KOR: "kr",
    KSA: "sa",
    MAR: "ma",
    MEX: "mx",
    NED: "nl",
    NOR: "no",
    NZL: "nz",
    PAN: "pa",
    PAR: "py",
    POR: "pt",
    QAT: "qa",
    RSA: "za",
    SCO: "sc",
    SEN: "sn",
    SUI: "ch",
    SWE: "se",
    TUN: "tn",
    TUR: "tr",
    UAE: "ae",
    URU: "uy",
    USA: "us",
    UZB: "uz",
    COD: "cd",
  };

  const normalized = (code || "").trim().toUpperCase();
  return map[normalized] || normalized.slice(0, 2).toLowerCase();
}