import "server-only";

import { cache } from "react";
import { isParticipantPatternStyle,isParticipantRenderFamily,safeVisualColor,type ParticipantVisualProfile } from "./participant-visuals";

const DEFAULT_SUPABASE_URL="https://jywqhiiwsmudthaujhmi.supabase.co";
const DEFAULT_SUPABASE_PUBLISHABLE_KEY="sb_publishable_30SkJ3gyUbPvH5sGFXpyHg_a4Qlzdi-";
const REQUEST_TIMEOUT_MS=4_000;
type Row=Record<string,unknown>;

export type PublicCompetitionTeam={id:string;slug:string;name:string;shortName?:string;visual?:ParticipantVisualProfile};
export type PublicCompetition={id:string;slug:string;name:string;displayName?:string;seasonLabel?:string;sport:string;sportName:string;competitionType?:string;regionLabel?:string;countryCode?:string;sortPriority?:number;metadataStatus?:string;teams:PublicCompetitionTeam[]};
function config(){const url=(process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL||DEFAULT_SUPABASE_URL).replace(/\/$/,"");const key=process.env.SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.SUPABASE_ANON_KEY||DEFAULT_SUPABASE_PUBLISHABLE_KEY;return{url,key};}
function headers(key:string){return{apikey:key,Authorization:`Bearer ${key}`};}
async function getJson(url:string,key:string):Promise<unknown>{const response=await fetch(url,{headers:headers(key),signal:AbortSignal.timeout(REQUEST_TIMEOUT_MS),next:{revalidate:300,tags:["public-competition-memberships"]}});if(!response.ok)throw new Error(`Supabase request failed with ${response.status}`);return response.json();}
function rows(value:unknown):Row[]{return Array.isArray(value)?value.filter((item):item is Row=>Boolean(item)&&typeof item==="object"&&!Array.isArray(item)):[];}
function text(value:unknown):string{return typeof value==="string"?value.trim():"";}
function number(value:unknown):number|undefined{return typeof value==="number"&&Number.isFinite(value)?value:undefined;}
function parseVisual(row:Row):ParticipantVisualProfile|undefined{if(!isParticipantRenderFamily(row.render_family)||!isParticipantPatternStyle(row.pattern_style))return undefined;const rawStatus=text(row.visual_status);const visualStatus:ParticipantVisualProfile["visualStatus"]=rawStatus==="verified"||rawStatus==="reviewed"||rawStatus==="needs_review"?rawStatus:"generated";return{renderFamily:row.render_family,primaryColor:safeVisualColor(row.primary_color,"#123A63"),secondaryColor:safeVisualColor(row.secondary_color,"#F8FAFC"),accentColor:safeVisualColor(row.accent_color,"#2F9CFF"),patternStyle:row.pattern_style,visualStatus,seasonLabel:text(row.season_label)||undefined,sourceName:text(row.source_name)||undefined,sourceUrl:text(row.source_url)||undefined,observedAt:text(row.observed_at)||undefined};}

async function loadPublicCompetition(sportSlug:string,competitionSlug:string):Promise<PublicCompetition|null>{try{const{url,key}=config();const sportRows=rows(await getJson(`${url}/rest/v1/sports?slug=eq.${encodeURIComponent(sportSlug)}&select=id,slug,name&limit=1`,key));const sport=sportRows[0];const sportId=text(sport?.id);const sportName=text(sport?.name)||sportSlug;if(!sportId)return null;const competitionRows=rows(await getJson(`${url}/rest/v1/competitions?sport_id=eq.${encodeURIComponent(sportId)}&slug=eq.${encodeURIComponent(competitionSlug)}&select=id,slug,name,display_name,season_label,competition_type,region_label,country_code,sort_priority,metadata_status&limit=1`,key));const competition=competitionRows[0];const competitionId=text(competition?.id);const competitionName=text(competition?.name);if(!competitionId||!competitionName)return null;const membershipRows=rows(await getJson(`${url}/rest/v1/competition_memberships?competition_id=eq.${encodeURIComponent(competitionId)}&membership_status=eq.confirmed&select=participant_id`,key));const participantIds=Array.from(new Set(membershipRows.map(row=>text(row.participant_id)).filter(Boolean)));let teams:PublicCompetitionTeam[]=[];if(participantIds.length){const filter=participantIds.map(id=>`\"${id.replaceAll('"','')}\"`).join(",");const[participantRows,visualRows]=await Promise.all([getJson(`${url}/rest/v1/participants?id=in.(${encodeURIComponent(filter)})&is_active=eq.true&select=id,slug,name,short_name&order=name.asc`,key).then(rows),getJson(`${url}/rest/v1/participant_visual_profiles?participant_id=in.(${encodeURIComponent(filter)})&select=participant_id,render_family,primary_color,secondary_color,accent_color,pattern_style,visual_status,season_label,source_name,source_url,observed_at`,key).then(rows)]);const visualByParticipant=new Map<string,ParticipantVisualProfile>();for(const row of visualRows){const participantId=text(row.participant_id);const visual=parseVisual(row);if(participantId&&visual)visualByParticipant.set(participantId,visual);}teams=participantRows.flatMap(row=>{const id=text(row.id),slug=text(row.slug),name=text(row.name);if(!id||!slug||!name)return[];return[{id,slug,name,shortName:text(row.short_name)||undefined,visual:visualByParticipant.get(id)}];});}
return{id:competitionId,slug:text(competition.slug)||competitionSlug,name:competitionName,displayName:text(competition.display_name)||undefined,seasonLabel:text(competition.season_label)||undefined,sport:sportSlug,sportName,competitionType:text(competition.competition_type)||undefined,regionLabel:text(competition.region_label)||undefined,countryCode:text(competition.country_code)||undefined,sortPriority:number(competition.sort_priority),metadataStatus:text(competition.metadata_status)||undefined,teams};}catch(error){console.error("Permanent competition data could not be loaded",error instanceof Error?error.message:"unknown error");return null;}}
export const getPublicCompetition=cache(loadPublicCompetition);
