import "server-only";
import { cache } from "react";

const DEFAULT_SUPABASE_URL="https://jywqhiiwsmudthaujhmi.supabase.co";
const DEFAULT_SUPABASE_PUBLISHABLE_KEY="sb_publishable_30SkJ3gyUbPvH5sGFXpyHg_a4Qlzdi-";
type Row=Record<string,unknown>;
export type PublicSportCompetition={id:string;slug:string;name:string;displayName:string;seasonLabel?:string;competitionType?:string;regionLabel?:string;countryCode?:string;sortPriority?:number;metadataStatus?:string};
function text(v:unknown){return typeof v==="string"?v.trim():"";}function num(v:unknown){return typeof v==="number"&&Number.isFinite(v)?v:undefined;}
function rows(v:unknown):Row[]{return Array.isArray(v)?v.filter((x):x is Row=>Boolean(x)&&typeof x==="object"&&!Array.isArray(x)):[];}
async function load(sportSlug:string):Promise<PublicSportCompetition[]>{try{const url=(process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL||DEFAULT_SUPABASE_URL).replace(/\/$/,"");const key=process.env.SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.SUPABASE_ANON_KEY||DEFAULT_SUPABASE_PUBLISHABLE_KEY;const headers={apikey:key,Authorization:`Bearer ${key}`};const sports=rows(await fetch(`${url}/rest/v1/sports?slug=eq.${encodeURIComponent(sportSlug)}&select=id&limit=1`,{headers,signal:AbortSignal.timeout(4000),next:{revalidate:3600,tags:["public-sport-competitions"]}}).then(r=>{if(!r.ok)throw new Error(String(r.status));return r.json();}));const sportId=text(sports[0]?.id);if(!sportId)return[];const result=rows(await fetch(`${url}/rest/v1/competitions?sport_id=eq.${encodeURIComponent(sportId)}&is_active=eq.true&select=id,slug,name,display_name,season_label,competition_type,region_label,country_code,sort_priority,metadata_status&order=sort_priority.asc.nullslast,name.asc`,{headers,signal:AbortSignal.timeout(4000),next:{revalidate:3600,tags:["public-sport-competitions"]}}).then(r=>{if(!r.ok)throw new Error(String(r.status));return r.json();}));return result.flatMap(row=>{const id=text(row.id),slug=text(row.slug),name=text(row.name);if(!id||!slug||!name)return[];return[{id,slug,name,displayName:text(row.display_name)||name,seasonLabel:text(row.season_label)||undefined,competitionType:text(row.competition_type)||undefined,regionLabel:text(row.region_label)||undefined,countryCode:text(row.country_code)||undefined,sortPriority:num(row.sort_priority),metadataStatus:text(row.metadata_status)||undefined}];});}catch(error){console.error("Sport competitions could not be loaded",error instanceof Error?error.message:"unknown error");return[];}}
export const getPublicSportCompetitions=cache(load);
