// lib/world-cup-2026-group-stage.ts

export type RawWorldCupGroupStageMatch = {
  matchNumber: number;
  stage: "Group";
  group: string;
  matchDate: string; // heure ET du PDF officiel
  homeTeam: string;
  awayTeam: string;
  slug: string;
  hostCity: string;
  hostCountry: string;
};

export const groupStageMatches: RawWorldCupGroupStageMatch[] = [
  {
    matchNumber: 1,
    stage: "Group",
    group: "A",
    matchDate: "2026-06-11T15:00:00-04:00",
    homeTeam: "Mexico",
    awayTeam: "South Africa",
    slug: "mexico-vs-south-africa",
    hostCity: "Mexico City",
    hostCountry: "Mexico",
  },
  {
    matchNumber: 2,
    stage: "Group",
    group: "A",
    matchDate: "2026-06-11T22:00:00-04:00",
    homeTeam: "South Korea",
    awayTeam: "Czechia",
    slug: "south-korea-vs-czechia",
    hostCity: "Guadalajara",
    hostCountry: "Mexico",
  },
  {
    matchNumber: 3,
    stage: "Group",
    group: "B",
    matchDate: "2026-06-12T15:00:00-04:00",
    homeTeam: "Canada",
    awayTeam: "Bosnia and Herzegovina",
    slug: "canada-vs-bosnia-and-herzegovina",
    hostCity: "Toronto",
    hostCountry: "Canada",
  },
  {
    matchNumber: 4,
    stage: "Group",
    group: "D",
    matchDate: "2026-06-12T21:00:00-04:00",
    homeTeam: "USA",
    awayTeam: "Paraguay",
    slug: "usa-vs-paraguay",
    hostCity: "Los Angeles",
    hostCountry: "USA",
  },
  {
    matchNumber: 5,
    stage: "Group",
    group: "C",
    matchDate: "2026-06-13T21:00:00-04:00",
    homeTeam: "Haiti",
    awayTeam: "Scotland",
    slug: "haiti-vs-scotland",
    hostCity: "Boston",
    hostCountry: "USA",
  },
  {
    matchNumber: 6,
    stage: "Group",
    group: "D",
    matchDate: "2026-06-13T00:00:00-04:00",
    homeTeam: "Australia",
    awayTeam: "Turkey",
    slug: "australia-vs-turkey",
    hostCity: "Vancouver",
    hostCountry: "Canada",
  },
  {
    matchNumber: 7,
    stage: "Group",
    group: "C",
    matchDate: "2026-06-13T18:00:00-04:00",
    homeTeam: "Brazil",
    awayTeam: "Morocco",
    slug: "brazil-vs-morocco",
    hostCity: "New York / New Jersey",
    hostCountry: "USA",
  },
  {
    matchNumber: 8,
    stage: "Group",
    group: "B",
    matchDate: "2026-06-13T15:00:00-04:00",
    homeTeam: "Qatar",
    awayTeam: "Switzerland",
    slug: "qatar-vs-switzerland",
    hostCity: "San Francisco Bay Area",
    hostCountry: "USA",
  },
  {
    matchNumber: 9,
    stage: "Group",
    group: "E",
    matchDate: "2026-06-13T19:00:00-04:00",
    homeTeam: "Ivory Coast",
    awayTeam: "Ecuador",
    slug: "ivory-coast-vs-ecuador",
    hostCity: "Philadelphia",
    hostCountry: "USA",
  },
  {
    matchNumber: 10,
    stage: "Group",
    group: "E",
    matchDate: "2026-06-13T13:00:00-04:00",
    homeTeam: "Germany",
    awayTeam: "Curacao",
    slug: "germany-vs-curacao",
    hostCity: "Houston",
    hostCountry: "USA",
  },
  {
    matchNumber: 11,
    stage: "Group",
    group: "F",
    matchDate: "2026-06-13T16:00:00-04:00",
    homeTeam: "Netherlands",
    awayTeam: "Japan",
    slug: "netherlands-vs-japan",
    hostCity: "Dallas",
    hostCountry: "USA",
  },
  {
    matchNumber: 12,
    stage: "Group",
    group: "F",
    matchDate: "2026-06-13T22:00:00-04:00",
    homeTeam: "Sweden",
    awayTeam: "Tunisia",
    slug: "sweden-vs-tunisia",
    hostCity: "Monterrey",
    hostCountry: "Mexico",
  },
  {
    matchNumber: 13,
    stage: "Group",
    group: "H",
    matchDate: "2026-06-15T18:00:00-04:00",
    homeTeam: "Saudi Arabia",
    awayTeam: "Uruguay",
    slug: "saudi-arabia-vs-uruguay",
    hostCity: "Miami",
    hostCountry: "USA",
  },
  {
    matchNumber: 14,
    stage: "Group",
    group: "H",
    matchDate: "2026-06-15T12:00:00-04:00",
    homeTeam: "Spain",
    awayTeam: "Cape Verde",
    slug: "spain-vs-cape-verde",
    hostCity: "Atlanta",
    hostCountry: "USA",
  },
  {
    matchNumber: 15,
    stage: "Group",
    group: "G",
    matchDate: "2026-06-15T21:00:00-04:00",
    homeTeam: "IR Iran",
    awayTeam: "New Zealand",
    slug: "ir-iran-vs-new-zealand",
    hostCity: "Los Angeles",
    hostCountry: "USA",
  },
  {
    matchNumber: 16,
    stage: "Group",
    group: "G",
    matchDate: "2026-06-15T15:00:00-04:00",
    homeTeam: "Belgium",
    awayTeam: "Egypt",
    slug: "belgium-vs-egypt",
    hostCity: "Seattle",
    hostCountry: "USA",
  },
  {
    matchNumber: 17,
    stage: "Group",
    group: "I",
    matchDate: "2026-06-16T15:00:00-04:00",
    homeTeam: "France",
    awayTeam: "Senegal",
    slug: "france-vs-senegal",
    hostCity: "New York / New Jersey",
    hostCountry: "USA",
  },
  {
    matchNumber: 18,
    stage: "Group",
    group: "I",
    matchDate: "2026-06-16T18:00:00-04:00",
    homeTeam: "Iraq",
    awayTeam: "Norway",
    slug: "iraq-vs-norway",
    hostCity: "Boston",
    hostCountry: "USA",
  },
  {
    matchNumber: 19,
    stage: "Group",
    group: "J",
    matchDate: "2026-06-17T21:00:00-04:00",
    homeTeam: "Argentina",
    awayTeam: "Algeria",
    slug: "argentina-vs-algeria",
    hostCity: "Kansas City",
    hostCountry: "USA",
  },
  {
    matchNumber: 20,
    stage: "Group",
    group: "J",
    matchDate: "2026-06-17T00:00:00-04:00",
    homeTeam: "Austria",
    awayTeam: "Jordan",
    slug: "austria-vs-jordan",
    hostCity: "San Francisco Bay Area",
    hostCountry: "USA",
  },
  {
    matchNumber: 21,
    stage: "Group",
    group: "L",
    matchDate: "2026-06-17T19:00:00-04:00",
    homeTeam: "Ghana",
    awayTeam: "Panama",
    slug: "ghana-vs-panama",
    hostCity: "Toronto",
    hostCountry: "Canada",
  },
  {
    matchNumber: 22,
    stage: "Group",
    group: "L",
    matchDate: "2026-06-17T16:00:00-04:00",
    homeTeam: "England",
    awayTeam: "Croatia",
    slug: "england-vs-croatia",
    hostCity: "Dallas",
    hostCountry: "USA",
  },
  {
    matchNumber: 23,
    stage: "Group",
    group: "K",
    matchDate: "2026-06-18T13:00:00-04:00",
    homeTeam: "Portugal",
    awayTeam: "DR Congo",
    slug: "portugal-vs-dr-congo",
    hostCity: "Houston",
    hostCountry: "USA",
  },
  {
    matchNumber: 24,
    stage: "Group",
    group: "K",
    matchDate: "2026-06-18T22:00:00-04:00",
    homeTeam: "Uzbekistan",
    awayTeam: "Colombia",
    slug: "uzbekistan-vs-colombia",
    hostCity: "Mexico City",
    hostCountry: "Mexico",
  },
  {
    matchNumber: 25,
    stage: "Group",
    group: "A",
    matchDate: "2026-06-19T12:00:00-04:00",
    homeTeam: "Czechia",
    awayTeam: "South Africa",
    slug: "czechia-vs-south-africa",
    hostCity: "Atlanta",
    hostCountry: "USA",
  },
  {
    matchNumber: 26,
    stage: "Group",
    group: "B",
    matchDate: "2026-06-19T15:00:00-04:00",
    homeTeam: "Switzerland",
    awayTeam: "Bosnia and Herzegovina",
    slug: "switzerland-vs-bosnia-and-herzegovina",
    hostCity: "Los Angeles",
    hostCountry: "USA",
  },
  {
    matchNumber: 27,
    stage: "Group",
    group: "B",
    matchDate: "2026-06-19T18:00:00-04:00",
    homeTeam: "Canada",
    awayTeam: "Qatar",
    slug: "canada-vs-qatar",
    hostCity: "Vancouver",
    hostCountry: "Canada",
  },
  {
    matchNumber: 28,
    stage: "Group",
    group: "A",
    matchDate: "2026-06-19T21:00:00-04:00",
    homeTeam: "Mexico",
    awayTeam: "South Korea",
    slug: "mexico-vs-south-korea",
    hostCity: "Guadalajara",
    hostCountry: "Mexico",
  },
  {
    matchNumber: 29,
    stage: "Group",
    group: "C",
    matchDate: "2026-06-20T20:30:00-04:00",
    homeTeam: "Brazil",
    awayTeam: "Haiti",
    slug: "brazil-vs-haiti",
    hostCity: "Philadelphia",
    hostCountry: "USA",
  },
  {
    matchNumber: 30,
    stage: "Group",
    group: "C",
    matchDate: "2026-06-20T18:00:00-04:00",
    homeTeam: "Scotland",
    awayTeam: "Morocco",
    slug: "scotland-vs-morocco",
    hostCity: "Boston",
    hostCountry: "USA",
  },
  {
    matchNumber: 31,
    stage: "Group",
    group: "D",
    matchDate: "2026-06-20T23:00:00-04:00",
    homeTeam: "Turkey",
    awayTeam: "Paraguay",
    slug: "turkey-vs-paraguay",
    hostCity: "San Francisco Bay Area",
    hostCountry: "USA",
  },
  {
    matchNumber: 32,
    stage: "Group",
    group: "D",
    matchDate: "2026-06-20T15:00:00-04:00",
    homeTeam: "USA",
    awayTeam: "Australia",
    slug: "usa-vs-australia",
    hostCity: "Seattle",
    hostCountry: "USA",
  },
  {
    matchNumber: 33,
    stage: "Group",
    group: "E",
    matchDate: "2026-06-20T16:00:00-04:00",
    homeTeam: "Germany",
    awayTeam: "Ivory Coast",
    slug: "germany-vs-ivory-coast",
    hostCity: "Toronto",
    hostCountry: "Canada",
  },
  {
    matchNumber: 34,
    stage: "Group",
    group: "E",
    matchDate: "2026-06-20T20:00:00-04:00",
    homeTeam: "Ecuador",
    awayTeam: "Curacao",
    slug: "ecuador-vs-curacao",
    hostCity: "Kansas City",
    hostCountry: "USA",
  },
  {
    matchNumber: 35,
    stage: "Group",
    group: "F",
    matchDate: "2026-06-20T13:00:00-04:00",
    homeTeam: "Netherlands",
    awayTeam: "Sweden",
    slug: "netherlands-vs-sweden",
    hostCity: "Houston",
    hostCountry: "USA",
  },
  {
    matchNumber: 36,
    stage: "Group",
    group: "F",
    matchDate: "2026-06-21T00:00:00-04:00",
    homeTeam: "Tunisia",
    awayTeam: "Japan",
    slug: "tunisia-vs-japan",
    hostCity: "Monterrey",
    hostCountry: "Mexico",
  },
  {
    matchNumber: 37,
    stage: "Group",
    group: "H",
    matchDate: "2026-06-21T18:00:00-04:00",
    homeTeam: "Uruguay",
    awayTeam: "Cape Verde",
    slug: "uruguay-vs-cape-verde",
    hostCity: "Miami",
    hostCountry: "USA",
  },
  {
    matchNumber: 38,
    stage: "Group",
    group: "H",
    matchDate: "2026-06-21T12:00:00-04:00",
    homeTeam: "Spain",
    awayTeam: "Saudi Arabia",
    slug: "spain-vs-saudi-arabia",
    hostCity: "Atlanta",
    hostCountry: "USA",
  },
  {
    matchNumber: 39,
    stage: "Group",
    group: "G",
    matchDate: "2026-06-21T15:00:00-04:00",
    homeTeam: "Belgium",
    awayTeam: "IR Iran",
    slug: "belgium-vs-ir-iran",
    hostCity: "Los Angeles",
    hostCountry: "USA",
  },
  {
    matchNumber: 40,
    stage: "Group",
    group: "G",
    matchDate: "2026-06-21T21:00:00-04:00",
    homeTeam: "New Zealand",
    awayTeam: "Egypt",
    slug: "new-zealand-vs-egypt",
    hostCity: "Vancouver",
    hostCountry: "Canada",
  },
  {
    matchNumber: 41,
    stage: "Group",
    group: "I",
    matchDate: "2026-06-22T20:00:00-04:00",
    homeTeam: "Norway",
    awayTeam: "Senegal",
    slug: "norway-vs-senegal",
    hostCity: "New York / New Jersey",
    hostCountry: "USA",
  },
  {
    matchNumber: 42,
    stage: "Group",
    group: "I",
    matchDate: "2026-06-22T17:00:00-04:00",
    homeTeam: "France",
    awayTeam: "Iraq",
    slug: "france-vs-iraq",
    hostCity: "Philadelphia",
    hostCountry: "USA",
  },
  {
    matchNumber: 43,
    stage: "Group",
    group: "J",
    matchDate: "2026-06-22T13:00:00-04:00",
    homeTeam: "Argentina",
    awayTeam: "Austria",
    slug: "argentina-vs-austria",
    hostCity: "Dallas",
    hostCountry: "USA",
  },
  {
    matchNumber: 44,
    stage: "Group",
    group: "J",
    matchDate: "2026-06-22T23:00:00-04:00",
    homeTeam: "Jordan",
    awayTeam: "Algeria",
    slug: "jordan-vs-algeria",
    hostCity: "San Francisco Bay Area",
    hostCountry: "USA",
  },
  {
    matchNumber: 45,
    stage: "Group",
    group: "L",
    matchDate: "2026-06-23T16:00:00-04:00",
    homeTeam: "England",
    awayTeam: "Ghana",
    slug: "england-vs-ghana",
    hostCity: "Boston",
    hostCountry: "USA",
  },
  {
    matchNumber: 46,
    stage: "Group",
    group: "L",
    matchDate: "2026-06-23T19:00:00-04:00",
    homeTeam: "Panama",
    awayTeam: "Croatia",
    slug: "panama-vs-croatia",
    hostCity: "Toronto",
    hostCountry: "Canada",
  },
  {
    matchNumber: 47,
    stage: "Group",
    group: "K",
    matchDate: "2026-06-23T13:00:00-04:00",
    homeTeam: "Portugal",
    awayTeam: "Uzbekistan",
    slug: "portugal-vs-uzbekistan",
    hostCity: "Houston",
    hostCountry: "USA",
  },
  {
    matchNumber: 48,
    stage: "Group",
    group: "K",
    matchDate: "2026-06-23T22:00:00-04:00",
    homeTeam: "Colombia",
    awayTeam: "DR Congo",
    slug: "colombia-vs-dr-congo",
    hostCity: "Guadalajara",
    hostCountry: "Mexico",
  },
  {
    matchNumber: 49,
    stage: "Group",
    group: "C",
    matchDate: "2026-06-24T18:00:00-04:00",
    homeTeam: "Scotland",
    awayTeam: "Brazil",
    slug: "scotland-vs-brazil",
    hostCity: "Miami",
    hostCountry: "USA",
  },
  {
    matchNumber: 50,
    stage: "Group",
    group: "C",
    matchDate: "2026-06-24T18:00:00-04:00",
    homeTeam: "Morocco",
    awayTeam: "Haiti",
    slug: "morocco-vs-haiti",
    hostCity: "Atlanta",
    hostCountry: "USA",
  },
  {
    matchNumber: 51,
    stage: "Group",
    group: "B",
    matchDate: "2026-06-24T15:00:00-04:00",
    homeTeam: "Switzerland",
    awayTeam: "Canada",
    slug: "switzerland-vs-canada",
    hostCity: "Vancouver",
    hostCountry: "Canada",
  },
  {
    matchNumber: 52,
    stage: "Group",
    group: "B",
    matchDate: "2026-06-24T15:00:00-04:00",
    homeTeam: "Bosnia and Herzegovina",
    awayTeam: "Qatar",
    slug: "bosnia-and-herzegovina-vs-qatar",
    hostCity: "Seattle",
    hostCountry: "USA",
  },
  {
    matchNumber: 53,
    stage: "Group",
    group: "A",
    matchDate: "2026-06-24T21:00:00-04:00",
    homeTeam: "Czechia",
    awayTeam: "Mexico",
    slug: "czechia-vs-mexico",
    hostCity: "Mexico City",
    hostCountry: "Mexico",
  },
  {
    matchNumber: 54,
    stage: "Group",
    group: "A",
    matchDate: "2026-06-24T21:00:00-04:00",
    homeTeam: "South Africa",
    awayTeam: "South Korea",
    slug: "south-africa-vs-south-korea",
    hostCity: "Monterrey",
    hostCountry: "Mexico",
  },
  {
    matchNumber: 55,
    stage: "Group",
    group: "E",
    matchDate: "2026-06-24T16:00:00-04:00",
    homeTeam: "Curacao",
    awayTeam: "Ivory Coast",
    slug: "curacao-vs-ivory-coast",
    hostCity: "Philadelphia",
    hostCountry: "USA",
  },
  {
    matchNumber: 56,
    stage: "Group",
    group: "E",
    matchDate: "2026-06-24T16:00:00-04:00",
    homeTeam: "Ecuador",
    awayTeam: "Germany",
    slug: "ecuador-vs-germany",
    hostCity: "New York / New Jersey",
    hostCountry: "USA",
  },
  {
    matchNumber: 57,
    stage: "Group",
    group: "F",
    matchDate: "2026-06-25T19:00:00-04:00",
    homeTeam: "Japan",
    awayTeam: "Sweden",
    slug: "japan-vs-sweden",
    hostCity: "Dallas",
    hostCountry: "USA",
  },
  {
    matchNumber: 58,
    stage: "Group",
    group: "F",
    matchDate: "2026-06-25T19:00:00-04:00",
    homeTeam: "Tunisia",
    awayTeam: "Netherlands",
    slug: "tunisia-vs-netherlands",
    hostCity: "Kansas City",
    hostCountry: "USA",
  },
  {
    matchNumber: 59,
    stage: "Group",
    group: "D",
    matchDate: "2026-06-25T22:00:00-04:00",
    homeTeam: "Turkey",
    awayTeam: "USA",
    slug: "turkey-vs-usa",
    hostCity: "Los Angeles",
    hostCountry: "USA",
  },
  {
    matchNumber: 60,
    stage: "Group",
    group: "D",
    matchDate: "2026-06-25T22:00:00-04:00",
    homeTeam: "Paraguay",
    awayTeam: "Australia",
    slug: "paraguay-vs-australia",
    hostCity: "San Francisco Bay Area",
    hostCountry: "USA",
  },
  {
    matchNumber: 61,
    stage: "Group",
    group: "I",
    matchDate: "2026-06-26T15:00:00-04:00",
    homeTeam: "Norway",
    awayTeam: "France",
    slug: "norway-vs-france",
    hostCity: "Boston",
    hostCountry: "USA",
  },
  {
    matchNumber: 62,
    stage: "Group",
    group: "I",
    matchDate: "2026-06-26T15:00:00-04:00",
    homeTeam: "Senegal",
    awayTeam: "Iraq",
    slug: "senegal-vs-iraq",
    hostCity: "Toronto",
    hostCountry: "Canada",
  },
  {
    matchNumber: 63,
    stage: "Group",
    group: "G",
    matchDate: "2026-06-26T23:00:00-04:00",
    homeTeam: "Egypt",
    awayTeam: "IR Iran",
    slug: "egypt-vs-ir-iran",
    hostCity: "Seattle",
    hostCountry: "USA",
  },
  {
    matchNumber: 64,
    stage: "Group",
    group: "G",
    matchDate: "2026-06-26T23:00:00-04:00",
    homeTeam: "New Zealand",
    awayTeam: "Belgium",
    slug: "new-zealand-vs-belgium",
    hostCity: "Vancouver",
    hostCountry: "Canada",
  },
  {
    matchNumber: 65,
    stage: "Group",
    group: "H",
    matchDate: "2026-06-26T20:00:00-04:00",
    homeTeam: "Cape Verde",
    awayTeam: "Saudi Arabia",
    slug: "cape-verde-vs-saudi-arabia",
    hostCity: "Houston",
    hostCountry: "USA",
  },
  {
    matchNumber: 66,
    stage: "Group",
    group: "H",
    matchDate: "2026-06-26T20:00:00-04:00",
    homeTeam: "Uruguay",
    awayTeam: "Spain",
    slug: "uruguay-vs-spain",
    hostCity: "Guadalajara",
    hostCountry: "Mexico",
  },
  {
    matchNumber: 67,
    stage: "Group",
    group: "L",
    matchDate: "2026-06-26T17:00:00-04:00",
    homeTeam: "Panama",
    awayTeam: "England",
    slug: "panama-vs-england",
    hostCity: "New York / New Jersey",
    hostCountry: "USA",
  },
  {
    matchNumber: 68,
    stage: "Group",
    group: "L",
    matchDate: "2026-06-26T17:00:00-04:00",
    homeTeam: "Croatia",
    awayTeam: "Ghana",
    slug: "croatia-vs-ghana",
    hostCity: "Philadelphia",
    hostCountry: "USA",
  },
  {
    matchNumber: 69,
    stage: "Group",
    group: "J",
    matchDate: "2026-06-27T22:00:00-04:00",
    homeTeam: "Algeria",
    awayTeam: "Austria",
    slug: "algeria-vs-austria",
    hostCity: "Kansas City",
    hostCountry: "USA",
  },
  {
    matchNumber: 70,
    stage: "Group",
    group: "J",
    matchDate: "2026-06-27T22:00:00-04:00",
    homeTeam: "Jordan",
    awayTeam: "Argentina",
    slug: "jordan-vs-argentina",
    hostCity: "Dallas",
    hostCountry: "USA",
  },
  {
    matchNumber: 71,
    stage: "Group",
    group: "K",
    matchDate: "2026-06-27T19:30:00-04:00",
    homeTeam: "Colombia",
    awayTeam: "Portugal",
    slug: "colombia-vs-portugal",
    hostCity: "Miami",
    hostCountry: "USA",
  },
  {
    matchNumber: 72,
    stage: "Group",
    group: "K",
    matchDate: "2026-06-27T19:30:00-04:00",
    homeTeam: "DR Congo",
    awayTeam: "Uzbekistan",
    slug: "dr-congo-vs-uzbekistan",
    hostCity: "Atlanta",
    hostCountry: "USA",
  },
];