import assert from 'node:assert/strict';
import test from 'node:test';
import {assessBroadcastCandidate,buildReviewException} from './broadcast-review-routing.mjs';
const id=n=>`${String(n).padStart(8,'0')}-0000-4000-8000-000000000001`;
function input(){return {eventId:id(1),eventTitle:'Toronto vs Montreal',competition:'Test League',competitionKey:'test-league',territoryCode:'CA',provider:'test-provider',eventStart:'2026-09-20T18:00:00Z',sourceObservedAt:'2026-09-15T12:00:00Z',sourceId:id(2),importItemId:id(3),sourcePolicy:{is_enabled:true,automatic_collection_enabled:true,reuse_status:'approved',commercial_use_allowed:true},candidate:{broadcaster_id:id(4),territory_id:id(5),access_type:'Paid',broadcast_type:'live',evidence_scope:'event',source_url:'https://example.ca/schedule/match',official_url:'https://example.ca/watch'}};}
test('clean event-level evidence can stay automatic',()=>{assert.equal(assessBroadcastCandidate(input(),{now:new Date('2026-09-15T13:00:00Z')}).route,'automatic');});
test('competition-only rights are sent to review',()=>{const x=input();x.candidate.evidence_scope='competition';const r=assessBroadcastCandidate(x,{now:new Date('2026-09-15T13:00:00Z')});assert.equal(r.route,'review');assert.ok(r.reasons.includes('evidence_not_event_specific'));});
test('conflict with published data requires explanation',()=>{const x=input();x.existing={...x.candidate,access_type:'Free'};const r=assessBroadcastCandidate(x,{now:new Date('2026-09-15T13:00:00Z')});assert.equal(r.route,'review');assert.equal(r.requiresExplanation,true);});
test('unapproved collection source is blocked, not put in manual queue',()=>{const x=input();x.sourcePolicy.automatic_collection_enabled=false;assert.equal(assessBroadcastCandidate(x).route,'blocked');});
test('review exception is deterministic and contains no publication action',()=>{const x=input();x.crossSourceConflict=true;const a=assessBroadcastCandidate(x,{now:new Date('2026-09-15T13:00:00Z')});const row=buildReviewException(x,a);assert.match(row.exception_key,/^broadcast:/);assert.equal(row.event_id,x.eventId);assert.equal(row.requires_explanation,true);assert.equal(Object.hasOwn(row,'is_published'),false);});
test('stale evidence near an event is reviewed',()=>{const x=input();x.eventStart='2026-09-16T18:00:00Z';x.sourceObservedAt='2026-09-10T12:00:00Z';const r=assessBroadcastCandidate(x,{now:new Date('2026-09-15T13:00:00Z')});assert.equal(r.route,'review');assert.ok(r.reasons.includes('evidence_stale'));});
test('probation provider is always double checked',()=>{const x=input();x.providerTrust={level:'probation',auditRate:1};const r=assessBroadcastCandidate(x,{now:new Date('2026-09-15T13:00:00Z')});assert.equal(r.route,'review');assert.ok(r.reasons.includes('provider_probation'));});
test('trusted provider can auto-pass when not selected for sample audit',()=>{const x=input();x.providerTrust={level:'trusted',auditRate:0};const r=assessBroadcastCandidate(x,{now:new Date('2026-09-15T13:00:00Z')});assert.equal(r.route,'automatic');assert.equal(r.providerTrustLevel,'trusted');});
test('trusted provider selected for audit goes to review',()=>{const x=input();x.providerTrust={level:'trusted',auditRate:1};const r=assessBroadcastCandidate(x,{now:new Date('2026-09-15T13:00:00Z')});assert.equal(r.route,'review');assert.ok(r.reasons.includes('provider_sample_audit'));});
test('suspended provider is blocked',()=>{const x=input();x.providerTrust={level:'suspended',auditRate:1};const r=assessBroadcastCandidate(x,{now:new Date('2026-09-15T13:00:00Z')});assert.equal(r.route,'blocked');assert.ok(r.reasons.includes('provider_suspended'));});
test('watch provider is reviewed, not automatically published',()=>{const x=input();x.providerTrust={level:'watch',auditRate:.5};const r=assessBroadcastCandidate(x,{now:new Date('2026-09-15T13:00:00Z')});assert.equal(r.route,'review');assert.ok(r.reasons.includes('provider_watch'));});
