// source/world-cup-2026-schedule.ts

export type WorldCup2026Match = {
  stage:
    | "Group Stage"
    | "Round of 32"
    | "Round of 16"
    | "Quarter-final"
    | "Semi-final"
    | "Third Place"
    | "Final";
  group?: string;
  roundLabel?: string;
  dateGmt: string;
  timeGmt: string;
  homeTeam: string;
  awayTeam: string;
  city: string;
  stadium: string;
};

export const worldCup2026Schedule: WorldCup2026Match[] = [
  {
    stage: "Group Stage",
    group: "A",
    dateGmt: "2026-06-11",
    timeGmt: "19:00",
    homeTeam: "Mexico",
    awayTeam: "South Africa",
    city: "Mexico City",
    stadium: "Mexico City Stadium",
  },
  {
    stage: "Group Stage",
    group: "A",
    dateGmt: "2026-06-12",
    timeGmt: "02:00",
    homeTeam: "Korea Republic",
    awayTeam: "Czechia",
    city: "Guadalajara",
    stadium: "Estadio Guadalajara",
  },
  {
    stage: "Group Stage",
    group: "B",
    dateGmt: "2026-06-12",
    timeGmt: "19:00",
    homeTeam: "Canada",
    awayTeam: "Bosnia and Herzegovina",
    city: "Toronto",
    stadium: "Toronto Stadium",
  },
  {
    stage: "Group Stage",
    group: "D",
    dateGmt: "2026-06-13",
    timeGmt: "01:00",
    homeTeam: "USA",
    awayTeam: "Paraguay",
    city: "Los Angeles",
    stadium: "Los Angeles Stadium",
  },
  {
    stage: "Group Stage",
    group: "C",
    dateGmt: "2026-06-14",
    timeGmt: "01:00",
    homeTeam: "Haiti",
    awayTeam: "Scotland",
    city: "Boston",
    stadium: "Boston Stadium",
  },
{
  stage: "Group Stage",
  group: "D",
  dateGmt: "2026-06-14",
  timeGmt: "04:00",
  homeTeam: "Australia",
  awayTeam: "Türkiye",
  city: "Vancouver",
  stadium: "BC Place Vancouver",
},
  {
    stage: "Group Stage",
    group: "C",
    dateGmt: "2026-06-13",
    timeGmt: "22:00",
    homeTeam: "Brazil",
    awayTeam: "Morocco",
    city: "New York / New Jersey",
    stadium: "New York New Jersey Stadium",
  },
  {
    stage: "Group Stage",
    group: "B",
    dateGmt: "2026-06-13",
    timeGmt: "19:00",
    homeTeam: "Qatar",
    awayTeam: "Switzerland",
    city: "San Francisco Bay Area",
    stadium: "San Francisco Bay Area Stadium",
  },
  {
    stage: "Group Stage",
    group: "E",
    dateGmt: "2026-06-14",
    timeGmt: "23:00",
    homeTeam: "Côte d'Ivoire",
    awayTeam: "Ecuador",
    city: "Philadelphia",
    stadium: "Philadelphia Stadium",
  },
  {
    stage: "Group Stage",
    group: "E",
    dateGmt: "2026-06-14",
    timeGmt: "17:00",
    homeTeam: "Germany",
    awayTeam: "Curaçao",
    city: "Houston",
    stadium: "Houston Stadium",
  },
  {
    stage: "Group Stage",
    group: "F",
    dateGmt: "2026-06-14",
    timeGmt: "20:00",
    homeTeam: "Netherlands",
    awayTeam: "Japan",
    city: "Dallas",
    stadium: "Dallas Stadium",
  },
  {
    stage: "Group Stage",
    group: "F",
    dateGmt: "2026-06-15",
    timeGmt: "02:00",
    homeTeam: "Sweden",
    awayTeam: "Tunisia",
    city: "Monterrey",
    stadium: "Estadio Monterrey",
  },
  {
    stage: "Group Stage",
    group: "H",
    dateGmt: "2026-06-15",
    timeGmt: "22:00",
    homeTeam: "Saudi Arabia",
    awayTeam: "Uruguay",
    city: "Miami",
    stadium: "Miami Stadium",
  },
  {
    stage: "Group Stage",
    group: "H",
    dateGmt: "2026-06-15",
    timeGmt: "16:00",
    homeTeam: "Spain",
    awayTeam: "Cabo Verde",
    city: "Atlanta",
    stadium: "Atlanta Stadium",
  },
  {
    stage: "Group Stage",
    group: "G",
    dateGmt: "2026-06-15",
    timeGmt: "19:00",
    homeTeam: "Belgium",
    awayTeam: "Egypt",
    city: "Seattle",
    stadium: "Seattle Stadium",
  },
  {
    stage: "Group Stage",
    group: "G",
    dateGmt: "2026-06-16",
    timeGmt: "01:00",
    homeTeam: "IR Iran",
    awayTeam: "New Zealand",
    city: "Los Angeles",
    stadium: "Los Angeles Stadium",
  },
  {
    stage: "Group Stage",
    group: "I",
    dateGmt: "2026-06-16",
    timeGmt: "19:00",
    homeTeam: "France",
    awayTeam: "Senegal",
    city: "New York / New Jersey",
    stadium: "New York New Jersey Stadium",
  },
  {
    stage: "Group Stage",
    group: "I",
    dateGmt: "2026-06-16",
    timeGmt: "22:00",
    homeTeam: "Iraq",
    awayTeam: "Norway",
    city: "Boston",
    stadium: "Boston Stadium",
  },
  {
    stage: "Group Stage",
    group: "J",
    dateGmt: "2026-06-17",
    timeGmt: "01:00",
    homeTeam: "Argentina",
    awayTeam: "Algeria",
    city: "Kansas City",
    stadium: "Kansas City Stadium",
  },
  {
    stage: "Group Stage",
    group: "J",
    dateGmt: "2026-06-16",
    timeGmt: "04:00",
    homeTeam: "Austria",
    awayTeam: "Jordan",
    city: "San Francisco Bay Area",
    stadium: "San Francisco Bay Area Stadium",
  },
  {
    stage: "Group Stage",
    group: "K",
    dateGmt: "2026-06-17",
    timeGmt: "17:00",
    homeTeam: "Portugal",
    awayTeam: "Congo DR",
    city: "Houston",
    stadium: "Houston Stadium",
  },
  {
    stage: "Group Stage",
    group: "L",
    dateGmt: "2026-06-17",
    timeGmt: "20:00",
    homeTeam: "England",
    awayTeam: "Croatia",
    city: "Dallas",
    stadium: "Dallas Stadium",
  },
  {
    stage: "Group Stage",
    group: "L",
    dateGmt: "2026-06-17",
    timeGmt: "23:00",
    homeTeam: "Ghana",
    awayTeam: "Panama",
    city: "Toronto",
    stadium: "Toronto Stadium",
  },
  {
    stage: "Group Stage",
    group: "K",
    dateGmt: "2026-06-18",
    timeGmt: "02:00",
    homeTeam: "Uzbekistan",
    awayTeam: "Colombia",
    city: "Mexico City",
    stadium: "Mexico City Stadium",
  },
  {
    stage: "Group Stage",
    group: "A",
    dateGmt: "2026-06-18",
    timeGmt: "16:00",
    homeTeam: "Czechia",
    awayTeam: "South Africa",
    city: "Atlanta",
    stadium: "Atlanta Stadium",
  },
  {
    stage: "Group Stage",
    group: "B",
    dateGmt: "2026-06-18",
    timeGmt: "19:00",
    homeTeam: "Switzerland",
    awayTeam: "Bosnia and Herzegovina",
    city: "Los Angeles",
    stadium: "Los Angeles Stadium",
  },
  {
    stage: "Group Stage",
    group: "B",
    dateGmt: "2026-06-18",
    timeGmt: "22:00",
    homeTeam: "Canada",
    awayTeam: "Qatar",
    city: "Vancouver",
    stadium: "BC Place Vancouver",
  },
  {
    stage: "Group Stage",
    group: "A",
    dateGmt: "2026-06-19",
    timeGmt: "01:00",
    homeTeam: "Mexico",
    awayTeam: "Korea Republic",
    city: "Guadalajara",
    stadium: "Estadio Guadalajara",
  },
  {
    stage: "Group Stage",
    group: "D",
    dateGmt: "2026-06-19",
    timeGmt: "19:00",
    homeTeam: "USA",
    awayTeam: "Australia",
    city: "Seattle",
    stadium: "Seattle Stadium",
  },
  {
    stage: "Group Stage",
    group: "C",
    dateGmt: "2026-06-19",
    timeGmt: "22:00",
    homeTeam: "Scotland",
    awayTeam: "Morocco",
    city: "Boston",
    stadium: "Boston Stadium",
  },
  {
    stage: "Group Stage",
    group: "C",
    dateGmt: "2026-06-20",
    timeGmt: "00:30",
    homeTeam: "Brazil",
    awayTeam: "Haiti",
    city: "Philadelphia",
    stadium: "Philadelphia Stadium",
  },
  {
    stage: "Group Stage",
    group: "D",
    dateGmt: "2026-06-20",
    timeGmt: "03:00",
    homeTeam: "Türkiye",
    awayTeam: "Paraguay",
    city: "San Francisco Bay Area",
    stadium: "San Francisco Bay Area Stadium",
  },
  {
    stage: "Group Stage",
    group: "F",
    dateGmt: "2026-06-20",
    timeGmt: "17:00",
    homeTeam: "Netherlands",
    awayTeam: "Sweden",
    city: "Houston",
    stadium: "Houston Stadium",
  },
  {
    stage: "Group Stage",
    group: "E",
    dateGmt: "2026-06-20",
    timeGmt: "20:00",
    homeTeam: "Germany",
    awayTeam: "Côte d'Ivoire",
    city: "Toronto",
    stadium: "Toronto Stadium",
  },
  {
    stage: "Group Stage",
    group: "E",
    dateGmt: "2026-06-21",
    timeGmt: "00:00",
    homeTeam: "Ecuador",
    awayTeam: "Curaçao",
    city: "Kansas City",
    stadium: "Kansas City Stadium",
  },
  {
    stage: "Group Stage",
    group: "F",
    dateGmt: "2026-06-21",
    timeGmt: "04:00",
    homeTeam: "Tunisia",
    awayTeam: "Japan",
    city: "Monterrey",
    stadium: "Estadio Monterrey",
  },
  {
    stage: "Group Stage",
    group: "H",
    dateGmt: "2026-06-21",
    timeGmt: "16:00",
    homeTeam: "Spain",
    awayTeam: "Saudi Arabia",
    city: "Atlanta",
    stadium: "Atlanta Stadium",
  },
  {
    stage: "Group Stage",
    group: "G",
    dateGmt: "2026-06-21",
    timeGmt: "19:00",
    homeTeam: "Belgium",
    awayTeam: "IR Iran",
    city: "Los Angeles",
    stadium: "Los Angeles Stadium",
  },
  {
    stage: "Group Stage",
    group: "H",
    dateGmt: "2026-06-21",
    timeGmt: "22:00",
    homeTeam: "Uruguay",
    awayTeam: "Cabo Verde",
    city: "Miami",
    stadium: "Miami Stadium",
  },
  {
    stage: "Group Stage",
    group: "G",
    dateGmt: "2026-06-22",
    timeGmt: "01:00",
    homeTeam: "New Zealand",
    awayTeam: "Egypt",
    city: "Vancouver",
    stadium: "BC Place Vancouver",
  },
  {
    stage: "Group Stage",
    group: "J",
    dateGmt: "2026-06-22",
    timeGmt: "17:00",
    homeTeam: "Argentina",
    awayTeam: "Austria",
    city: "Dallas",
    stadium: "Dallas Stadium",
  },
  {
    stage: "Group Stage",
    group: "I",
    dateGmt: "2026-06-22",
    timeGmt: "21:00",
    homeTeam: "France",
    awayTeam: "Iraq",
    city: "Philadelphia",
    stadium: "Philadelphia Stadium",
  },
  {
    stage: "Group Stage",
    group: "I",
    dateGmt: "2026-06-23",
    timeGmt: "00:00",
    homeTeam: "Norway",
    awayTeam: "Senegal",
    city: "New York / New Jersey",
    stadium: "New York New Jersey Stadium",
  },
  {
    stage: "Group Stage",
    group: "J",
    dateGmt: "2026-06-23",
    timeGmt: "03:00",
    homeTeam: "Jordan",
    awayTeam: "Algeria",
    city: "Kansas City",
    stadium: "Kansas City Stadium",
  },
  {
    stage: "Group Stage",
    group: "K",
    dateGmt: "2026-06-23",
    timeGmt: "17:00",
    homeTeam: "Portugal",
    awayTeam: "Uzbekistan",
    city: "Houston",
    stadium: "Houston Stadium",
  },
  {
    stage: "Group Stage",
    group: "L",
    dateGmt: "2026-06-23",
    timeGmt: "20:00",
    homeTeam: "England",
    awayTeam: "Ghana",
    city: "Boston",
    stadium: "Boston Stadium",
  },
  {
    stage: "Group Stage",
    group: "L",
    dateGmt: "2026-06-23",
    timeGmt: "23:00",
    homeTeam: "Panama",
    awayTeam: "Croatia",
    city: "Toronto",
    stadium: "Toronto Stadium",
  },
  {
    stage: "Group Stage",
    group: "K",
    dateGmt: "2026-06-24",
    timeGmt: "02:00",
    homeTeam: "Colombia",
    awayTeam: "Congo DR",
    city: "Guadalajara",
    stadium: "Estadio Guadalajara",
  },
  {
    stage: "Group Stage",
    group: "B",
    dateGmt: "2026-06-24",
    timeGmt: "19:00",
    homeTeam: "Switzerland",
    awayTeam: "Canada",
    city: "Vancouver",
    stadium: "BC Place Vancouver",
  },
  {
    stage: "Group Stage",
    group: "B",
    dateGmt: "2026-06-24",
    timeGmt: "19:00",
    homeTeam: "Bosnia and Herzegovina",
    awayTeam: "Qatar",
    city: "Seattle",
    stadium: "Seattle Stadium",
  },
  {
    stage: "Group Stage",
    group: "C",
    dateGmt: "2026-06-24",
    timeGmt: "22:00",
    homeTeam: "Scotland",
    awayTeam: "Brazil",
    city: "Miami",
    stadium: "Miami Stadium",
  },
  {
    stage: "Group Stage",
    group: "C",
    dateGmt: "2026-06-24",
    timeGmt: "22:00",
    homeTeam: "Morocco",
    awayTeam: "Haiti",
    city: "Atlanta",
    stadium: "Atlanta Stadium",
  },
  {
    stage: "Group Stage",
    group: "A",
    dateGmt: "2026-06-25",
    timeGmt: "01:00",
    homeTeam: "Czechia",
    awayTeam: "Mexico",
    city: "Mexico City",
    stadium: "Mexico City Stadium",
  },
  {
    stage: "Group Stage",
    group: "A",
    dateGmt: "2026-06-25",
    timeGmt: "01:00",
    homeTeam: "South Africa",
    awayTeam: "Korea Republic",
    city: "Monterrey",
    stadium: "Estadio Monterrey",
  },
  {
    stage: "Group Stage",
    group: "E",
    dateGmt: "2026-06-25",
    timeGmt: "20:00",
    homeTeam: "Curaçao",
    awayTeam: "Côte d'Ivoire",
    city: "Philadelphia",
    stadium: "Philadelphia Stadium",
  },
  {
    stage: "Group Stage",
    group: "E",
    dateGmt: "2026-06-25",
    timeGmt: "20:00",
    homeTeam: "Ecuador",
    awayTeam: "Germany",
    city: "New York / New Jersey",
    stadium: "New York New Jersey Stadium",
  },
  {
    stage: "Group Stage",
    group: "F",
    dateGmt: "2026-06-25",
    timeGmt: "23:00",
    homeTeam: "Japan",
    awayTeam: "Sweden",
    city: "Dallas",
    stadium: "Dallas Stadium",
  },
  {
    stage: "Group Stage",
    group: "F",
    dateGmt: "2026-06-25",
    timeGmt: "23:00",
    homeTeam: "Tunisia",
    awayTeam: "Netherlands",
    city: "Kansas City",
    stadium: "Kansas City Stadium",
  },
  {
    stage: "Group Stage",
    group: "D",
    dateGmt: "2026-06-26",
    timeGmt: "02:00",
    homeTeam: "Türkiye",
    awayTeam: "USA",
    city: "Los Angeles",
    stadium: "Los Angeles Stadium",
  },
  {
    stage: "Group Stage",
    group: "D",
    dateGmt: "2026-06-26",
    timeGmt: "02:00",
    homeTeam: "Paraguay",
    awayTeam: "Australia",
    city: "San Francisco Bay Area",
    stadium: "San Francisco Bay Area Stadium",
  },
  {
    stage: "Group Stage",
    group: "I",
    dateGmt: "2026-06-26",
    timeGmt: "19:00",
    homeTeam: "Norway",
    awayTeam: "France",
    city: "Boston",
    stadium: "Boston Stadium",
  },
  {
    stage: "Group Stage",
    group: "I",
    dateGmt: "2026-06-26",
    timeGmt: "19:00",
    homeTeam: "Senegal",
    awayTeam: "Iraq",
    city: "Toronto",
    stadium: "Toronto Stadium",
  },
  {
    stage: "Group Stage",
    group: "H",
    dateGmt: "2026-06-27",
    timeGmt: "00:00",
    homeTeam: "Cabo Verde",
    awayTeam: "Saudi Arabia",
    city: "Houston",
    stadium: "Houston Stadium",
  },
  {
    stage: "Group Stage",
    group: "H",
    dateGmt: "2026-06-27",
    timeGmt: "00:00",
    homeTeam: "Uruguay",
    awayTeam: "Spain",
    city: "Guadalajara",
    stadium: "Estadio Guadalajara",
  },
  {
    stage: "Group Stage",
    group: "G",
    dateGmt: "2026-06-27",
    timeGmt: "03:00",
    homeTeam: "Egypt",
    awayTeam: "IR Iran",
    city: "Seattle",
    stadium: "Seattle Stadium",
  },
  {
    stage: "Group Stage",
    group: "G",
    dateGmt: "2026-06-27",
    timeGmt: "03:00",
    homeTeam: "New Zealand",
    awayTeam: "Belgium",
    city: "Vancouver",
    stadium: "BC Place Vancouver",
  },
  {
    stage: "Group Stage",
    group: "L",
    dateGmt: "2026-06-27",
    timeGmt: "21:00",
    homeTeam: "Panama",
    awayTeam: "England",
    city: "New York / New Jersey",
    stadium: "New York New Jersey Stadium",
  },
  {
    stage: "Group Stage",
    group: "L",
    dateGmt: "2026-06-27",
    timeGmt: "21:00",
    homeTeam: "Croatia",
    awayTeam: "Ghana",
    city: "Philadelphia",
    stadium: "Philadelphia Stadium",
  },
  {
    stage: "Group Stage",
    group: "K",
    dateGmt: "2026-06-27",
    timeGmt: "23:30",
    homeTeam: "Colombia",
    awayTeam: "Portugal",
    city: "Miami",
    stadium: "Miami Stadium",
  },
  {
    stage: "Group Stage",
    group: "K",
    dateGmt: "2026-06-27",
    timeGmt: "23:30",
    homeTeam: "Congo DR",
    awayTeam: "Uzbekistan",
    city: "Atlanta",
    stadium: "Atlanta Stadium",
  },
  {
    stage: "Group Stage",
    group: "J",
    dateGmt: "2026-06-28",
    timeGmt: "02:00",
    homeTeam: "Algeria",
    awayTeam: "Austria",
    city: "Kansas City",
    stadium: "Kansas City Stadium",
  },
  {
    stage: "Group Stage",
    group: "J",
    dateGmt: "2026-06-28",
    timeGmt: "02:00",
    homeTeam: "Jordan",
    awayTeam: "Argentina",
    city: "Dallas",
    stadium: "Dallas Stadium",
  },
  {
    stage: "Round of 32",
    roundLabel: "2A vs 2B",
    dateGmt: "2026-06-28",
    timeGmt: "19:00",
    homeTeam: "2A",
    awayTeam: "2B",
    city: "Los Angeles",
    stadium: "Los Angeles Stadium",
  },
  {
    stage: "Round of 32",
    roundLabel: "1C vs 2F",
    dateGmt: "2026-06-29",
    timeGmt: "17:00",
    homeTeam: "1C",
    awayTeam: "2F",
    city: "Houston",
    stadium: "Houston Stadium",
  },
  {
    stage: "Round of 32",
    roundLabel: "1E vs 3ABCDF",
    dateGmt: "2026-06-29",
    timeGmt: "20:30",
    homeTeam: "1E",
    awayTeam: "3ABCDF",
    city: "Boston",
    stadium: "Boston Stadium",
  },
  {
    stage: "Round of 32",
    roundLabel: "1F vs 2C",
    dateGmt: "2026-06-30",
    timeGmt: "01:00",
    homeTeam: "1F",
    awayTeam: "2C",
    city: "Monterrey",
    stadium: "Estadio Monterrey",
  },
  {
    stage: "Round of 32",
    roundLabel: "2E vs 2I",
    dateGmt: "2026-06-30",
    timeGmt: "17:00",
    homeTeam: "2E",
    awayTeam: "2I",
    city: "Dallas",
    stadium: "Dallas Stadium",
  },
  {
    stage: "Round of 32",
    roundLabel: "1I vs 3CDFGH",
    dateGmt: "2026-06-30",
    timeGmt: "21:00",
    homeTeam: "1I",
    awayTeam: "3CDFGH",
    city: "New York / New Jersey",
    stadium: "New York New Jersey Stadium",
  },
  {
    stage: "Round of 32",
    roundLabel: "1A vs 3CEFHI",
    dateGmt: "2026-07-01",
    timeGmt: "01:00",
    homeTeam: "1A",
    awayTeam: "3CEFHI",
    city: "Mexico City",
    stadium: "Mexico City Stadium",
  },
  {
    stage: "Round of 32",
    roundLabel: "1L vs 3EHIJK",
    dateGmt: "2026-07-01",
    timeGmt: "16:00",
    homeTeam: "1L",
    awayTeam: "3EHIJK",
    city: "Atlanta",
    stadium: "Atlanta Stadium",
  },
  {
    stage: "Round of 32",
    roundLabel: "1G vs 3AEHIJ",
    dateGmt: "2026-07-01",
    timeGmt: "20:00",
    homeTeam: "1G",
    awayTeam: "3AEHIJ",
    city: "Seattle",
    stadium: "Seattle Stadium",
  },
  {
    stage: "Round of 32",
    roundLabel: "1D vs 3BEFIJ",
    dateGmt: "2026-07-02",
    timeGmt: "00:00",
    homeTeam: "1D",
    awayTeam: "3BEFIJ",
    city: "San Francisco Bay Area",
    stadium: "San Francisco Bay Area Stadium",
  },
  {
    stage: "Round of 32",
    roundLabel: "1H vs 2J",
    dateGmt: "2026-07-02",
    timeGmt: "19:00",
    homeTeam: "1H",
    awayTeam: "2J",
    city: "Toronto",
    stadium: "Toronto Stadium",
  },
  {
    stage: "Round of 32",
    roundLabel: "2K vs 2L",
    dateGmt: "2026-07-02",
    timeGmt: "23:00",
    homeTeam: "2K",
    awayTeam: "2L",
    city: "Vancouver",
    stadium: "BC Place Vancouver",
  },
  {
    stage: "Round of 32",
    roundLabel: "1B vs 3EFGIJ",
    dateGmt: "2026-07-03",
    timeGmt: "03:00",
    homeTeam: "1B",
    awayTeam: "3EFGIJ",
    city: "Los Angeles",
    stadium: "Los Angeles Stadium",
  },
  {
    stage: "Round of 32",
    roundLabel: "2D vs 2G",
    dateGmt: "2026-07-03",
    timeGmt: "18:00",
    homeTeam: "2D",
    awayTeam: "2G",
    city: "Miami",
    stadium: "Miami Stadium",
  },
  {
    stage: "Round of 32",
    roundLabel: "1J vs 2H",
    dateGmt: "2026-07-03",
    timeGmt: "22:00",
    homeTeam: "1J",
    awayTeam: "2H",
    city: "Kansas City",
    stadium: "Kansas City Stadium",
  },
  {
    stage: "Round of 32",
    roundLabel: "1K vs 3DEIJL",
    dateGmt: "2026-07-04",
    timeGmt: "01:30",
    homeTeam: "1K",
    awayTeam: "3DEIJL",
    city: "Guadalajara",
    stadium: "Estadio Guadalajara",
  },
  {
    stage: "Round of 16",
    roundLabel: "W73 vs W75",
    dateGmt: "2026-07-04",
    timeGmt: "17:00",
    homeTeam: "W73",
    awayTeam: "W75",
    city: "Houston",
    stadium: "Houston Stadium",
  },
  {
    stage: "Round of 16",
    roundLabel: "W74 vs W77",
    dateGmt: "2026-07-04",
    timeGmt: "21:00",
    homeTeam: "W74",
    awayTeam: "W77",
    city: "Philadelphia",
    stadium: "Philadelphia Stadium",
  },
  {
    stage: "Round of 16",
    roundLabel: "W76 vs W78",
    dateGmt: "2026-07-05",
    timeGmt: "20:00",
    homeTeam: "W76",
    awayTeam: "W78",
    city: "New York / New Jersey",
    stadium: "New York New Jersey Stadium",
  },
  {
    stage: "Round of 16",
    roundLabel: "W79 vs W80",
    dateGmt: "2026-07-06",
    timeGmt: "00:00",
    homeTeam: "W79",
    awayTeam: "W80",
    city: "Mexico City",
    stadium: "Mexico City Stadium",
  },
  {
    stage: "Round of 16",
    roundLabel: "W83 vs W84",
    dateGmt: "2026-07-06",
    timeGmt: "19:00",
    homeTeam: "W83",
    awayTeam: "W84",
    city: "Dallas",
    stadium: "Dallas Stadium",
  },
  {
    stage: "Round of 16",
    roundLabel: "W81 vs W82",
    dateGmt: "2026-07-07",
    timeGmt: "00:00",
    homeTeam: "W81",
    awayTeam: "W82",
    city: "Seattle",
    stadium: "Seattle Stadium",
  },
  {
    stage: "Round of 16",
    roundLabel: "W86 vs W88",
    dateGmt: "2026-07-07",
    timeGmt: "16:00",
    homeTeam: "W86",
    awayTeam: "W88",
    city: "Atlanta",
    stadium: "Atlanta Stadium",
  },
  {
    stage: "Round of 16",
    roundLabel: "W85 vs W87",
    dateGmt: "2026-07-07",
    timeGmt: "20:00",
    homeTeam: "W85",
    awayTeam: "W87",
    city: "Vancouver",
    stadium: "BC Place Vancouver",
  },
  {
    stage: "Quarter-final",
    roundLabel: "W89 vs W90",
    dateGmt: "2026-07-09",
    timeGmt: "20:00",
    homeTeam: "W89",
    awayTeam: "W90",
    city: "Boston",
    stadium: "Boston Stadium",
  },
  {
    stage: "Quarter-final",
    roundLabel: "W93 vs W94",
    dateGmt: "2026-07-10",
    timeGmt: "19:00",
    homeTeam: "W93",
    awayTeam: "W94",
    city: "Los Angeles",
    stadium: "Los Angeles Stadium",
  },
  {
    stage: "Quarter-final",
    roundLabel: "W91 vs W92",
    dateGmt: "2026-07-11",
    timeGmt: "21:00",
    homeTeam: "W91",
    awayTeam: "W92",
    city: "Miami",
    stadium: "Miami Stadium",
  },
  {
    stage: "Quarter-final",
    roundLabel: "W95 vs W96",
    dateGmt: "2026-07-12",
    timeGmt: "01:00",
    homeTeam: "W95",
    awayTeam: "W96",
    city: "Kansas City",
    stadium: "Kansas City Stadium",
  },
  {
    stage: "Semi-final",
    roundLabel: "W97 vs W98",
    dateGmt: "2026-07-14",
    timeGmt: "19:00",
    homeTeam: "W97",
    awayTeam: "W98",
    city: "Dallas",
    stadium: "Dallas Stadium",
  },
  {
    stage: "Semi-final",
    roundLabel: "W99 vs W100",
    dateGmt: "2026-07-15",
    timeGmt: "19:00",
    homeTeam: "W99",
    awayTeam: "W100",
    city: "Atlanta",
    stadium: "Atlanta Stadium",
  },
  {
    stage: "Third Place",
    roundLabel: "RU101 vs RU102",
    dateGmt: "2026-07-18",
    timeGmt: "21:00",
    homeTeam: "RU101",
    awayTeam: "RU102",
    city: "Miami",
    stadium: "Miami Stadium",
  },
  {
    stage: "Final",
    roundLabel: "W101 vs W102",
    dateGmt: "2026-07-19",
    timeGmt: "19:00",
    homeTeam: "W101",
    awayTeam: "W102",
    city: "New York / New Jersey",
    stadium: "New York New Jersey Stadium",
  },
];