// source/world-cup-2026-schedule.ts

export type WorldCup2026Match = {
  stage:
    | "Group Stage"
    | "Round of 32"
    | "Round of 16"
    | "Quarter-final"
    | "Semi-final"
    | "Third Place"
    | "Final";
  group?: string;
  roundLabel?: string;
  dateGmt: string;
  timeGmt: string;
  homeTeam: string;
  awayTeam: string;
  city: string;
  stadium: string;
};

export const worldCup2026Schedule: WorldCup2026Match[] = [
  {
    stage: "Group Stage",
    group: "A",
    dateGmt: "2026-06-11",
    timeGmt: "19:00",
    homeTeam: "Mexico",
    awayTeam: "South Africa",
    city: "Mexico City",
    stadium: "Mexico City Stadium",
  },
  {
    stage: "Group Stage",
    group: "A",
    dateGmt: "2026-06-12",
    timeGmt: "02:00",
    homeTeam: "Korea Republic",
    awayTeam: "Czechia",
    city: "Guadalajara",
    stadium: "Estadio Guadalajara",
  },
  {
    stage: "Group Stage",
    group: "B",
    dateGmt: "2026-06-12",
    timeGmt: "19:00",
    homeTeam: "Canada",
    awayTeam: "Bosnia and Herzegovina",
    city: "Toronto",
    stadium: "Toronto Stadium",
  },
  {
    stage: "Group Stage",
    group: "D",
    dateGmt: "2026-06-13",
    timeGmt: "01:00",
    homeTeam: "USA",
    awayTeam: "Paraguay",
    city: "Los Angeles",
    stadium: "Los Angeles Stadium",
  },
  {
    stage: "Group Stage",
    group: "C",
    dateGmt: "2026-06-14",
    timeGmt: "01:00",
    homeTeam: "Haiti",
    awayTeam: "Scotland",
    city: "Boston",
    stadium: "Boston Stadium",
  },
{
  stage: "Group Stage",
  group: "D",
  dateGmt: "2026-06-14",
  timeGmt: "04:00",
  homeTeam: "Australia",
  awayTeam: "Türkiye",
  city: "Vancouver",
  stadium: "BC Place Vancouver",
},
  {
    stage: "Group Stage",
    group: "C",
    dateGmt: "2026-06-13",
    timeGmt: "22:00",
    homeTeam: "Brazil",
    awayTeam: "Morocco",
    city: "New York / New Jersey",
    stadium: "New York New Jersey Stadium",
  },
  {
    stage: "Group Stage",
    group: "B",
    dateGmt: "2026-06-13",
    timeGmt: "19:00",
    homeTeam: "Qatar",
    awayTeam: "Switzerland",
    city: "San Francisco Bay Area",
    stadium: "San Francisco Bay Area Stadium",
  },
  {
    stage: "Group Stage",
    group: "E",
    dateGmt: "2026-06-14",
    timeGmt: "23:00",
    homeTeam: "Côte d'Ivoire",
    awayTeam: "Ecuador",
    city: "Philadelphia",
    stadium: "Philadelphia Stadium",
  },
  {
    stage: "Group Stage",
    group: "E",
    dateGmt: "2026-06-14",
    timeGmt: "17:00",
    homeTeam: "Germany",
    awayTeam: "Curaçao",
    city: "Houston",
    stadium: "Houston Stadium",
  },
  {
    stage: "Group Stage",
    group: "F",
    dateGmt: "2026-06-14",
    timeGmt: "20:00",
    homeTeam: "Netherlands",
    awayTeam: "Japan",
    city: "Dallas",
    stadium: "Dallas Stadium",
  },
  {
    stage: "Group Stage",
    group: "F",
    dateGmt: "2026-06-15",
    timeGmt: "02:00",
    homeTeam: "Sweden",
    awayTeam: "Tunisia",
    city: "Monterrey",
    stadium: "Estadio Monterrey",
  },
  {
    stage: "Group Stage",
    group: "H",
    dateGmt: "2026-06-15",
    timeGmt: "22:00",
    homeTeam: "Saudi Arabia",
    awayTeam: "Uruguay",
    city: "Miami",
    stadium: "Miami Stadium",
  },
  {
    stage: "Group Stage",
    group: "H",
    dateGmt: "2026-06-15",
    timeGmt: "16:00",
    homeTeam: "Spain",
    awayTeam: "Cabo Verde",
    city: "Atlanta",
    stadium: "Atlanta Stadium",
  },
  {
    stage: "Group Stage",
    group: "G",
    dateGmt: "2026-06-15",
    timeGmt: "19:00",
    homeTeam: "Belgium",
    awayTeam: "Egypt",
    city: "Seattle",
    stadium: "Seattle Stadium",
  },
  {
    stage: "Group Stage",
    group: "G",
    dateGmt: "2026-06-16",
    timeGmt: "01:00",
    homeTeam: "IR Iran",
    awayTeam: "New Zealand",
    city: "Los Angeles",
    stadium: "Los Angeles Stadium",
  },
  {
    stage: "Group Stage",
    group: "I",
    dateGmt: "2026-06-16",
    timeGmt: "19:00",
    homeTeam: "France",
    awayTeam: "Senegal",
    city: "New York / New Jersey",
    stadium: "New York New Jersey Stadium",
  },
  {
    stage: "Group Stage",
    group: "I",
    dateGmt: "2026-06-16",
    timeGmt: "22:00",
    homeTeam: "Iraq",
    awayTeam: "Norway",
    city: "Boston",
    stadium: "Boston Stadium",
  },
  {
    stage: "Group Stage",
    group: "J",
    dateGmt: "2026-06-17",
    timeGmt: "01:00",
    homeTeam: "Argentina",
    awayTeam: "Algeria",
    city: "Kansas City",
    stadium: "Kansas City Stadium",
  },
  {
    stage: "Group Stage",
    group: "J",
    dateGmt: "2026-06-16",
    timeGmt: "04:00",
    homeTeam: "Austria",
    awayTeam: "Jordan",
    city: "San Francisco Bay Area",
    stadium: "San Francisco Bay Area Stadium",
  },
  {
    stage: "Group Stage",
    group: "K",
    dateGmt: "2026-06-17",
    timeGmt: "17:00",
    homeTeam: "Portugal",
    awayTeam: "Congo DR",
    city: "Houston",
    stadium: "Houston Stadium",
  },
  {
    stage: "Group Stage",
    group: "L",
    dateGmt: "2026-06-17",
    timeGmt: "20:00",
    homeTeam: "England",
    awayTeam: "Croatia",
    city: "Dallas",
    stadium: "Dallas Stadium",
  },
  {
    stage: "Group Stage",
    group: "L",
    dateGmt: "2026-06-17",
    timeGmt: "23:00",
    homeTeam: "Ghana",
    awayTeam: "Panama",
    city: "Toronto",
    stadium: "Toronto Stadium",
  },
  {
    stage: "Group Stage",
    group: "K",
    dateGmt: "2026-06-18",
    timeGmt: "02:00",
    homeTeam: "Uzbekistan",
    awayTeam: "Colombia",
    city: "Mexico City",
    stadium: "Mexico City Stadium",
  },
  {
    stage: "Group Stage",
    group: "A",
    dateGmt: "2026-06-18",
    timeGmt: "16:00",
    homeTeam: "Czechia",
    awayTeam: "South Africa",
    city: "Atlanta",
    stadium: "Atlanta Stadium",
  },
  {
    stage: "Group Stage",
    group: "B",
    dateGmt: "2026-06-18",
    timeGmt: "19:00",
    homeTeam: "Switzerland",
    awayTeam: "Bosnia and Herzegovina",
    city: "Los Angeles",
    stadium: "Los Angeles Stadium",
  },
  {
    stage: "Group Stage",
    group: "B",
    dateGmt: "2026-06-18",
    timeGmt: "22:00",
    homeTeam: "Canada",
    awayTeam: "Qatar",
    city: "Vancouver",
    stadium: "BC Place Vancouver",
  },
  {
    stage: "Group Stage",
    group: "A",
    dateGmt: "2026-06-19",
    timeGmt: "01:00",
    homeTeam: "Mexico",
    awayTeam: "Korea Republic",
    city: "Guadalajara",
    stadium: "Estadio Guadalajara",
  },
  {
    stage: "Group Stage",
    group: "D",
    dateGmt: "2026-06-19",
    timeGmt: "19:00",
    homeTeam: "USA",
    awayTeam: "Australia",
    city: "Seattle",
    stadium: "Seattle Stadium",
  },
  {
    stage: "Group Stage",
    group: "C",
    dateGmt: "2026-06-19",
    timeGmt: "22:00",
    homeTeam: "Scotland",
    awayTeam: "Morocco",
    city: "Boston",
    stadium: "Boston Stadium",
  },
  {
    stage: "Group Stage",
    group: "C",
    dateGmt: "2026-06-20",
    timeGmt: "00:30",
    homeTeam: "Brazil",
    awayTeam: "Haiti",
    city: "Philadelphia",
    stadium: "Philadelphia Stadium",
  },
  {
    stage: "Group Stage",
    group: "D",
    dateGmt: "2026-06-20",
    timeGmt: "03:00",
    homeTeam: "Türkiye",
    awayTeam: "Paraguay",
    city: "San Francisco Bay Area",
    stadium: "San Francisco Bay Area Stadium",
  },
  {
    stage: "Group Stage",
    group: "F",
    dateGmt: "2026-06-20",
    timeGmt: "17:00",
    homeTeam: "Netherlands",
    awayTeam: "Sweden",
    city: "Houston",
    stadium: "Houston Stadium",
  },
  {
    stage: "Group Stage",
    group: "E",
    dateGmt: "2026-06-20",
    timeGmt: "20:00",
    homeTeam: "Germany",
    awayTeam: "Côte d'Ivoire",
    city: "Toronto",
    stadium: "Toronto Stadium",
  },
  {
    stage: "Group Stage",
    group: "E",
    dateGmt: "2026-06-21",
    timeGmt: "00:00",
    homeTeam: "Ecuador",
    awayTeam: "Curaçao",
    city: "Kansas City",
    stadium: "Kansas City Stadium",
  },
  {
    stage: "Group Stage",
    group: "F",
    dateGmt: "2026-06-21",
    timeGmt: "04:00",
    homeTeam: "Tunisia",
    awayTeam: "Japan",
    city: "Monterrey",
    stadium: "Estadio Monterrey",
  },
  {
    stage: "Group Stage",
    group: "H",
    dateGmt: "2026-06-21",
    timeGmt: "16:00",
    homeTeam: "Spain",
    awayTeam: "Saudi Arabia",
    city: "Atlanta",
    stadium: "Atlanta Stadium",
  },
  {
    stage: "Group Stage",
    group: "G",
    dateGmt: "2026-06-21",
    timeGmt: "19:00",
    homeTeam: "Belgium",
    awayTeam: "IR Iran",
    city: "Los Angeles",
    stadium: "Los Angeles Stadium",
  },
  {
    stage: "Group Stage",
    group: "H",
    dateGmt: "2026-06-21",
    timeGmt: "22:00",
    homeTeam: "Uruguay",
    awayTeam: "Cabo Verde",
    city: "Miami",
    stadium: "Miami Stadium",
  },
  {
    stage: "Group Stage",
    group: "G",
    dateGmt: "2026-06-22",
    timeGmt: "01:00",
    homeTeam: "New Zealand",
    awayTeam: "Egypt",
    city: "Vancouver",
    stadium: "BC Place Vancouver",
  },
  {
    stage: "Group Stage",
    group: "J",
    dateGmt: "2026-06-22",
    timeGmt: "17:00",
    homeTeam: "Argentina",
    awayTeam: "Austria",
    city: "Dallas",
    stadium: "Dallas Stadium",
  },
  {
    stage: "Group Stage",
    group: "I",
    dateGmt: "2026-06-22",
    timeGmt: "21:00",
    homeTeam: "France",
    awayTeam: "Iraq",
    city: "Philadelphia",
    stadium: "Philadelphia Stadium",
  },
  {
    stage: "Group Stage",
    group: "I",
    dateGmt: "2026-06-23",
    timeGmt: "00:00",
    homeTeam: "Norway",
    awayTeam: "Senegal",
    city: "New York / New Jersey",
    stadium: "New York New Jersey Stadium",
  },
  {
    stage: "Group Stage",
    group: "J",
    dateGmt: "2026-06-23",
    timeGmt: "03:00",
    homeTeam: "Jordan",
    awayTeam: "Algeria",
    city: "Kansas City",
    stadium: "Kansas City Stadium",
  },
  {
    stage: "Group Stage",
    group: "K",
    dateGmt: "2026-06-23",
    timeGmt: "17:00",
    homeTeam: "Portugal",
    awayTeam: "Uzbekistan",
    city: "Houston",
    stadium: "Houston Stadium",
  },
  {
    stage: "Group Stage",
    group: "L",
    dateGmt: "2026-06-23",
    timeGmt: "20:00",
    homeTeam: "England",
    awayTeam: "Ghana",
    city: "Boston",
    stadium: "Boston Stadium",
  },
  {
    stage: "Group Stage",
    group: "L",
    dateGmt: "2026-06-23",
    timeGmt: "23:00",
    homeTeam: "Panama",
    awayTeam: "Croatia",
    city: "Toronto",
    stadium: "Toronto Stadium",
  },
  {
    stage: "Group Stage",
    group: "K",
    dateGmt: "2026-06-24",
    timeGmt: "02:00",
    homeTeam: "Colombia",
    awayTeam: "Congo DR",
    city: "Guadalajara",
    stadium: "Estadio Guadalajara",
  },
  {
    stage: "Group Stage",
    group: "B",
    dateGmt: "2026-06-24",
    timeGmt: "19:00",
    homeTeam: "Switzerland",
    awayTeam: "Canada",
    city: "Vancouver",
    stadium: "BC Place Vancouver",
  },
  {
    stage: "Group Stage",
    group: "B",
    dateGmt: "2026-06-24",
    timeGmt: "19:00",
    homeTeam: "Bosnia and Herzegovina",
    awayTeam: "Qatar",
    city: "Seattle",
    stadium: "Seattle Stadium",
  },
  {
    stage: "Group Stage",
    group: "C",
    dateGmt: "2026-06-24",
    timeGmt: "22:00",
    homeTeam: "Scotland",
    awayTeam: "Brazil",
    city: "Miami",
    stadium: "Miami Stadium",
  },
  {
    stage: "Group Stage",
    group: "C",
    dateGmt: "2026-06-24",
    timeGmt: "22:00",
    homeTeam: "Morocco",
    awayTeam: "Haiti",
    city: "Atlanta",
    stadium: "Atlanta Stadium",
  },
  {
    stage: "Group Stage",
    group: "A",
    dateGmt: "2026-06-25",
    timeGmt: "01:00",
    homeTeam: "Czechia",
    awayTeam: "Mexico",
    city: "Mexico City",
    stadium: "Mexico City Stadium",
  },
  {
    stage: "Group Stage",
    group: "A",
    dateGmt: "2026-06-25",
    timeGmt: "01:00",
    homeTeam: "South Africa",
    awayTeam: "Korea Republic",
    city: "Monterrey",
    stadium: "Estadio Monterrey",
  },
  {
    stage: "Group Stage",
    group: "E",
    dateGmt: "2026-06-25",
    timeGmt: "20:00",
    homeTeam: "Curaçao",
    awayTeam: "Côte d'Ivoire",
    city: "Philadelphia",
    stadium: "Philadelphia Stadium",
  },
  {
    stage: "Group Stage",
    group: "E",
    dateGmt: "2026-06-25",
    timeGmt: "20:00",
    homeTeam: "Ecuador",
    awayTeam: "Germany",
    city: "New York / New Jersey",
    stadium: "New York New Jersey Stadium",
  },
  {
    stage: "Group Stage",
    group: "F",
    dateGmt: "2026-06-25",
    timeGmt: "23:00",
    homeTeam: "Japan",
    awayTeam: "Sweden",
    city: "Dallas",
    stadium: "Dallas Stadium",
  },
  {
    stage: "Group Stage",
    group: "F",
    dateGmt: "2026-06-25",
    timeGmt: "23:00",
    homeTeam: "Tunisia",
    awayTeam: "Netherlands",
    city: "Kansas City",
    stadium: "Kansas City Stadium",
  },
  {
    stage: "Group Stage",
    group: "D",
    dateGmt: "2026-06-26",
    timeGmt: "02:00",
    homeTeam: "Türkiye",
    awayTeam: "USA",
    city: "Los Angeles",
    stadium: "Los Angeles Stadium",
  },
  {
    stage: "Group Stage",
    group: "D",
    dateGmt: "2026-06-26",
    timeGmt: "02:00",
    homeTeam: "Paraguay",
    awayTeam: "Australia",
    city: "San Francisco Bay Area",
    stadium: "San Francisco Bay Area Stadium",
  },
  {
    stage: "Group Stage",
    group: "I",
    dateGmt: "2026-06-26",
    timeGmt: "19:00",
    homeTeam: "Norway",
    awayTeam: "France",
    city: "Boston",
    stadium: "Boston Stadium",
  },
  {
    stage: "Group Stage",
    group: "I",
    dateGmt: "2026-06-26",
    timeGmt: "19:00",
    homeTeam: "Senegal",
    awayTeam: "Iraq",
    city: "Toronto",
    stadium: "Toronto Stadium",
  },
  {
    stage: "Group Stage",
    group: "H",
    dateGmt: "2026-06-27",
    timeGmt: "00:00",
    homeTeam: "Cabo Verde",
    awayTeam: "Saudi Arabia",
    city: "Houston",
    stadium: "Houston Stadium",
  },
  {
    stage: "Group Stage",
    group: "H",
    dateGmt: "2026-06-27",
    timeGmt: "00:00",
    homeTeam: "Uruguay",
    awayTeam: "Spain",
    city: "Guadalajara",
    stadium: "Estadio Guadalajara",
  },
  {
    stage: "Group Stage",
    group: "G",
    dateGmt: "2026-06-27",
    timeGmt: "03:00",
    homeTeam: "Egypt",
    awayTeam: "IR Iran",
    city: "Seattle",
    stadium: "Seattle Stadium",
  },
  {
    stage: "Group Stage",
    group: "G",
    dateGmt: "2026-06-27",
    timeGmt: "03:00",
    homeTeam: "New Zealand",
    awayTeam: "Belgium",
    city: "Vancouver",
    stadium: "BC Place Vancouver",
  },
  {
    stage: "Group Stage",
    group: "L",
    dateGmt: "2026-06-27",
    timeGmt: "21:00",
    homeTeam: "Panama",
    awayTeam: "England",
    city: "New York / New Jersey",
    stadium: "New York New Jersey Stadium",
  },
  {
    stage: "Group Stage",
    group: "L",
    dateGmt: "2026-06-27",
    timeGmt: "21:00",
    homeTeam: "Croatia",
    awayTeam: "Ghana",
    city: "Philadelphia",
    stadium: "Philadelphia Stadium",
  },
  {
    stage: "Group Stage",
    group: "K",
    dateGmt: "2026-06-27",
    timeGmt: "23:30",
    homeTeam: "Colombia",
    awayTeam: "Portugal",
    city: "Miami",
    stadium: "Miami Stadium",
  },
  {
    stage: "Group Stage",
    group: "K",
    dateGmt: "2026-06-27",
    timeGmt: "23:30",
    homeTeam: "Congo DR",
    awayTeam: "Uzbekistan",
    city: "Atlanta",
    stadium: "Atlanta Stadium",
  },
  {
    stage: "Group Stage",
    group: "J",
    dateGmt: "2026-06-28",
    timeGmt: "02:00",
    homeTeam: "Algeria",
    awayTeam: "Austria",
    city: "Kansas City",
    stadium: "Kansas City Stadium",
  },
  {
    stage: "Group Stage",
    group: "J",
    dateGmt: "2026-06-28",
    timeGmt: "02:00",
    homeTeam: "Jordan",
    awayTeam: "Argentina",
    city: "Dallas",
    stadium: "Dallas Stadium",
  },
{
  stage: "Round of 32",
  roundLabel: "South Africa vs Canada",
  homeTeam: "South Africa",
  awayTeam: "Canada",
  dateGmt: "2026-06-28",
  timeGmt: "19:00",
  city: "Los Angeles",
  stadium: "Los Angeles Stadium",
},
{
  stage: "Round of 32",
  roundLabel: "Brazil vs Japan",
  dateGmt: "2026-06-29",
  timeGmt: "17:00",
  homeTeam: "Brazil",
  awayTeam: "Japan",
  city: "Houston",
  stadium: "Houston Stadium",
},
{
  stage: "Round of 32",
  roundLabel: "Germany vs Paraguay",
  dateGmt: "2026-06-29",
  timeGmt: "20:30",
  homeTeam: "Germany",
  awayTeam: "Paraguay",
  city: "Boston",
  stadium: "Boston Stadium",
},
{
  stage: "Round of 32",
  roundLabel: "Netherlands vs Morocco",
  dateGmt: "2026-06-30",
  timeGmt: "01:00",
  homeTeam: "Netherlands",
  awayTeam: "Morocco",
  city: "Monterrey",
  stadium: "Estadio Monterrey",
},
{
  stage: "Round of 32",
  roundLabel: "France vs Sweden",
  dateGmt: "2026-06-30",
  timeGmt: "17:00",
  homeTeam: "France",
  awayTeam: "Sweden",
  city: "Dallas",
  stadium: "Dallas Stadium",
},
{
  stage: "Round of 32",
  roundLabel: "Côte d'Ivoire vs Norway",
  dateGmt: "2026-06-30",
  timeGmt: "21:00",
  homeTeam: "Côte d'Ivoire",
  awayTeam: "Norway",
  city: "New York / New Jersey",
  stadium: "New York New Jersey Stadium",
},
{
  stage: "Round of 32",
  roundLabel: "Mexico vs Ecuador",
  dateGmt: "2026-07-01",
  timeGmt: "01:00",
  homeTeam: "Mexico",
  awayTeam: "Ecuador",
  city: "Mexico City",
  stadium: "Mexico City Stadium",
},
{
  stage: "Round of 32",
  roundLabel: "England vs Congo DR",
  dateGmt: "2026-07-01",
  timeGmt: "16:00",
  homeTeam: "England",
  awayTeam: "Congo DR",
  city: "Atlanta",
  stadium: "Atlanta Stadium",
},
{
  stage: "Round of 32",
  roundLabel: "Belgium vs Senegal",
  dateGmt: "2026-07-01",
  timeGmt: "20:00",
  homeTeam: "Belgium",
  awayTeam: "Senegal",
  city: "Seattle",
  stadium: "Seattle Stadium",
},
{
  stage: "Round of 32",
  roundLabel: "USA vs Bosnia and Herzegovina",
  dateGmt: "2026-07-02",
  timeGmt: "00:00",
  homeTeam: "USA",
  awayTeam: "Bosnia and Herzegovina",
  city: "San Francisco Bay Area",
  stadium: "San Francisco Bay Area Stadium",
},
{
  stage: "Round of 32",
  roundLabel: "Spain vs Austria",
  dateGmt: "2026-07-02",
  timeGmt: "19:00",
  homeTeam: "Spain",
  awayTeam: "Austria",
  city: "Los Angeles",
  stadium: "Los Angeles Stadium",
},
{
  stage: "Round of 32",
  roundLabel: "Portugal vs Croatia",
  dateGmt: "2026-07-02",
  timeGmt: "23:00",
  homeTeam: "Portugal",
  awayTeam: "Croatia",
  city: "Toronto",
  stadium: "Toronto Stadium",
},
{
  stage: "Round of 32",
  roundLabel: "Switzerland vs Algeria",
  dateGmt: "2026-07-03",
  timeGmt: "03:00",
  homeTeam: "Switzerland",
  awayTeam: "Algeria",
  city: "Vancouver",
  stadium: "BC Place Vancouver",
},
{
  stage: "Round of 32",
  roundLabel: "Australia vs Egypt",
  dateGmt: "2026-07-03",
  timeGmt: "18:00",
  homeTeam: "Australia",
  awayTeam: "Egypt",
  city: "Miami",
  stadium: "Miami Stadium",
},
{
  stage: "Round of 32",
  roundLabel: "Argentina vs Cape Verde",
  dateGmt: "2026-07-03",
  timeGmt: "22:00",
  homeTeam: "Argentina",
  awayTeam: "Cape Verde",
  city: "Kansas City",
  stadium: "Kansas City Stadium",
},
{
  stage: "Round of 32",
  roundLabel: "Colombia vs Ghana",
  dateGmt: "2026-07-04",
  timeGmt: "01:30",
  homeTeam: "Colombia",
  awayTeam: "Ghana",
  city: "Guadalajara",
  stadium: "Estadio Guadalajara",
},
  {
  stage: "Round of 16",
  roundLabel: "Canada vs Morocco",
  dateGmt: "2026-07-04",
  timeGmt: "17:00",
  homeTeam: "Canada",
  awayTeam: "Morocco",
  city: "Houston",
  stadium: "Houston Stadium",
},
{
  stage: "Round of 16",
  roundLabel: "Paraguay vs France",
  dateGmt: "2026-07-04",
  timeGmt: "21:00",
  homeTeam: "Paraguay",
  awayTeam: "France",
  city: "Philadelphia",
  stadium: "Philadelphia Stadium",
},
{
  stage: "Round of 16",
  roundLabel: "Brazil vs Norway",
  dateGmt: "2026-07-05",
  timeGmt: "20:00",
  homeTeam: "Brazil",
  awayTeam: "Norway",
  city: "New York / New Jersey",
  stadium: "New York New Jersey Stadium",
},
{
  stage: "Round of 16",
  roundLabel: "Mexico vs England",
  dateGmt: "2026-07-06",
  timeGmt: "00:00",
  homeTeam: "Mexico",
  awayTeam: "England",
  city: "Mexico City",
  stadium: "Mexico City Stadium",
},
{
  stage: "Round of 16",
  roundLabel: "Portugal vs Spain",
  dateGmt: "2026-07-06",
  timeGmt: "19:00",
  homeTeam: "Portugal",
  awayTeam: "Spain",
  city: "Dallas",
  stadium: "Dallas Stadium",
},
{
  stage: "Round of 16",
  roundLabel: "USA vs Belgium",
  dateGmt: "2026-07-07",
  timeGmt: "00:00",
  homeTeam: "USA",
  awayTeam: "Belgium",
  city: "Seattle",
  stadium: "Seattle Stadium",
},
  {
  stage: "Round of 16",
  roundLabel: "Argentina vs Egypt",
  dateGmt: "2026-07-07",
  timeGmt: "16:00",
  homeTeam: "Argentina",
  awayTeam: "Egypt",
  city: "Atlanta",
  stadium: "Atlanta Stadium",
},
{
  stage: "Round of 16",
  roundLabel: "Switzerland vs Colombia",
  dateGmt: "2026-07-07",
  timeGmt: "20:00",
  homeTeam: "Switzerland",
  awayTeam: "Colombia",
  city: "Vancouver",
  stadium: "BC Place Vancouver",
},
{
  stage: "Quarter-final",
  roundLabel: "France vs Morocco",
  dateGmt: "2026-07-09",
  timeGmt: "20:00",
  homeTeam: "France",
  awayTeam: "Morocco",
  city: "Boston",
  stadium: "Boston Stadium",
},
{
  stage: "Quarter-final",
  roundLabel: "Spain vs Belgium",
  dateGmt: "2026-07-10",
  timeGmt: "19:00",
  homeTeam: "Spain",
  awayTeam: "Belgium",
  city: "Los Angeles",
  stadium: "Los Angeles Stadium",
},
{
  stage: "Quarter-final",
  roundLabel: "Norway vs England",
  dateGmt: "2026-07-11",
  timeGmt: "21:00",
  homeTeam: "Norway",
  awayTeam: "England",
  city: "Miami",
  stadium: "Miami Stadium",
},
{
  stage: "Quarter-final",
  roundLabel: "Argentina vs Switzerland",
  dateGmt: "2026-07-12",
  timeGmt: "01:00",
  homeTeam: "Argentina",
  awayTeam: "Switzerland",
  city: "Kansas City",
  stadium: "Kansas City Stadium",
},
  {
    stage: "Semi-final",
    roundLabel: "France vs Spain",
    dateGmt: "2026-07-14",
    timeGmt: "19:00",
    homeTeam: "France",
    awayTeam: "Spain",
    city: "Dallas",
    stadium: "Dallas Stadium",
  },
{
  stage: "Semi-final",
  roundLabel: "England vs Argentina",
  dateGmt: "2026-07-15",
  timeGmt: "19:00",
  homeTeam: "England",
  awayTeam: "Argentina",
  city: "Atlanta",
  stadium: "Atlanta Stadium",
},
 {
  stage: "Third Place",
  roundLabel: "France vs England",
  dateGmt: "2026-07-18",
  timeGmt: "21:00",
  homeTeam: "France",
  awayTeam: "England",
  city: "Miami",
  stadium: "Miami Stadium",
},
{
  stage: "Final",
  roundLabel: "Spain vs Argentina",
  dateGmt: "2026-07-19",
  timeGmt: "19:00",
  homeTeam: "Spain",
  awayTeam: "Argentina",
  city: "New York / New Jersey",
  stadium: "New York New Jersey Stadium",
},
];