import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Breadcrumbs from "@/components/Breadcrumbs";
import BroadcastOffers from "@/components/BroadcastOffers";
import LocalTime from "@/components/LocalTime";
import { getAllEvents, type EventData } from "@/lib/events";
import { getPublicEventsSnapshot } from "@/lib/public-events";
import { getFormula1SessionPlan2026, getFormula1Weekend2026 } from "@/source/formula-1-2026-season";

type PageProps={params:Promise<{grandPrix:string}>;searchParams?:Promise<{country?:string;access?:string}>};
function grandPrixEvents(events:EventData[],slug:string){return events.filter(e=>e.sport==="formula-1"&&e.eventGroupSlug===slug).sort((a,b)=>new Date(a.eventDate).getTime()-new Date(b.eventDate).getTime());}
function selectEdition(events:EventData[],now=new Date()){const editions=new Map<string,EventData[]>();for(const event of events){const key=event.eventEditionKey??new Date(event.eventDate).getUTCFullYear().toString();editions.set(key,[...(editions.get(key)??[]),event]);}const sorted=Array.from(editions.entries()).map(([key,items])=>({key,events:items.sort((a,b)=>new Date(a.eventDate).getTime()-new Date(b.eventDate).getTime())})).sort((a,b)=>new Date(a.events[0]?.eventDate??0).getTime()-new Date(b.events[0]?.eventDate??0).getTime());return sorted.find(x=>x.events.some(e=>e.status==="live"))?.events??sorted.find(x=>x.events.some(e=>new Date(e.eventDate).getTime()>=now.getTime()))?.events??sorted.at(-1)?.events??[];}
export async function generateStaticParams(){return Array.from(new Set(getAllEvents().filter(e=>e.sport==="formula-1"&&e.eventGroupSlug).map(e=>e.eventGroupSlug!))).map(grandPrix=>({grandPrix}));}
export async function generateMetadata({params}:PageProps):Promise<Metadata>{const{grandPrix}=await params;const snapshot=await getPublicEventsSnapshot();const events=selectEdition(grandPrixEvents(snapshot.events,grandPrix));const first=events[0];if(!first)return{title:"Grand Prix not found | WatchTVSport",robots:{index:false,follow:false}};const edition=first.eventEditionLabel?` ${first.eventEditionLabel}`:"";return{title:`${first.eventGroupName}${edition} F1 TV schedule & official broadcasters`,description:`Complete ${first.eventGroupName}${edition} Formula 1 weekend schedule and verified official broadcast information by country.`,alternates:{canonical:`/formula-1/grand-prix/${grandPrix}`},openGraph:{title:`${first.eventGroupName}${edition} – Where to watch F1`,description:`Official Formula 1 session times and broadcasters for ${first.eventGroupName}.`,url:`/formula-1/grand-prix/${grandPrix}`,type:"website"}};}
export default async function Formula1GrandPrixPage({params,searchParams}:PageProps){const{grandPrix}=await params;const resolved=(await searchParams)??{};const snapshot=await getPublicEventsSnapshot();const allEvents=grandPrixEvents(snapshot.events,grandPrix);const events=selectEdition(allEvents);const first=events[0];const weekend=getFormula1Weekend2026(grandPrix);if(!first||!weekend)notFound();const race=events.find(e=>e.sessionType==="race");const editionLabel=first.eventEditionLabel??"2026";const sessionPlan=getFormula1SessionPlan2026(weekend);const jsonLd={"@context":"https://schema.org","@type":"SportsEvent",name:`${first.eventGroupName} ${editionLabel}`,startDate:race?.eventDate??events[0]?.eventDate,location:{"@type":"Place",name:first.venue??weekend.venue,address:first.country??weekend.country},url:`https://watchtvsport.com/formula-1/grand-prix/${grandPrix}`};return <main id="main-content" className="v2-calendar"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Formula 1",href:"/formula-1"},{label:first.eventGroupName??weekend.name}]}/><section className="v2-calendar-hero" aria-labelledby="gp-title"><p className="v2-eyebrow">Formula 1 Grand Prix weekend</p><h1 id="gp-title">{first.eventGroupName??weekend.name}</h1><p className="v2-signature">Edition {editionLabel}</p><p className="v2-hero-copy">{[first.country??weekend.country,first.venue??weekend.venue].filter(Boolean).join(" · ")}. Every official session is represented; unconfirmed exact times remain explicitly TBC.</p>{race?<p className="v2-signature">Race: <LocalTime date={race.eventDate}/></p>:null}</section><section className="v2-results" aria-labelledby="sessions-title"><div className="v2-results-heading"><div><p className="v2-eyebrow">Weekend schedule</p><h2 id="sessions-title">Sessions</h2></div><p>{sessionPlan.length}</p></div><div className="v2-event-list">{sessionPlan.map(session=>{const event=events.find(e=>e.sequenceNumber===session.sequenceNumber);const confirmed=event?.broadcasts.filter(b=>b.coverageStatus==="confirmed").length??0;return <article className="v2-event-card" id={session.slug} key={session.slug}><div className="v2-event-main"><p className="v2-event-competition">{session.label}</p><h3>{session.label}</h3><p className="v2-event-stage">{event?<LocalTime date={event.eventDate}/>:"Exact time TBC"}</p></div><div className="v2-broadcast-link"><span>{confirmed} confirmed official listings</span><strong>{confirmed?"Broadcast options available":"Broadcast data pending"}</strong></div></article>})}</div></section><BroadcastOffers events={events} selectedCountry={resolved.country} selectedAccess={resolved.access} title="Where to watch this Grand Prix"/></main>}
